[174] Calculate Product Shipping Cost
Dufuna-CodeCamp/Dufuna-CodeCamp20 pull request #1010
Opened 2020-12-09 10:30 UTC by Tocyn

![Screen Shot 2020-12-09 at 11 19 31 AM](https://user-images.githubusercontent.com/70757475/101618091-c93ceb80-3a11-11eb-9cd9-44daee1d7c55.png)
![Screen Shot 2020-12-09 at 11 19 53 AM](https://user-images.githubusercontent.com/70757475/101618101-cb9f4580-3a11-11eb-99d3-a7d9f3f349bf.png)

2020-12-09 12:51 UTC, adaugochi requested changes
Kindly work on the design on your `Buy Now ` button. It looks too tiny. use CSS padding for the design

2020-12-09 12:51 UTC, adaugochi commented on submissions/oluwatosinOke/domManipulation/productpage.js
> +let sum = Number(price.innerHTML) * quantity.value;
Give this a better variable name.

2020-12-09 13:34 UTC, Tocyn commented
@adaugochi, 
Requested Changes have been effected.
![Screen Shot 2020-12-09 at 2 24 33 PM](https://user-images.githubusercontent.com/70757475/101636268-5f314000-3a2b-11eb-9321-fdb7a4276bc3.png)

2020-12-10 09:47 UTC, adaugochi approved these changes

2020-12-10 09:48 UTC, merged