[216] Product Array Algorithm
Dufuna-CodeCamp/Dufuna-CodeCamp20 pull request #1034
Opened 2020-12-12 13:50 UTC by Samju200

## Task: `Product Array Algorithm`
- `Changes you made to given task`

2020-12-13 14:23 UTC, adaugochi requested changes

2020-12-13 14:23 UTC, adaugochi commented on submissions/adeyemiJuwon/algorithm/productArray.js
> +const products = [
Use the data from the sheet

2020-12-13 14:23 UTC, adaugochi commented on submissions/adeyemiJuwon/algorithm/productArray.js
> +const product_prices = [1485.83, 819.52, 4.26, 6.95];
use the data from the sheet

2020-12-13 15:26 UTC, Samju200 commented on submissions/adeyemiJuwon/algorithm/productArray.js
> +const product_prices = [1485.83, 819.52, 4.26, 6.95];
Okay. Done
Thank you @adaugochi

2020-12-14 10:44 UTC, adaugochi approved these changes

2020-12-14 10:44 UTC, merged