[216] Product Array Algorithm
Dufuna-CodeCamp/Dufuna-CodeCamp20 pull request #1048
Opened 2020-12-20 01:15 UTC by faithakinbobola

I created product array algorithm

2020-12-20 01:24 UTC, faithakinbobola commented
@adaugochi I don't understand what is wrong with my code, the checks keep failing. I've tried all ways i can to correct it, it's still the same. Please help.

2020-12-21 09:00 UTC, ToluAkin requested changes

2020-12-21 09:00 UTC, ToluAkin commented on submissions/akinbobolaFaith/algorithms/product.js
> +var product_price = [500.00, 200.00, 750.00, 2000.00, 1600.00, 300.00, 800.00, 5000.00, 500.00, 600.00, 1200.00, 1200.00, 2000.00, 2000.00, 5000.00, 750.00, 200.00, 800.00, 900.00, 750.00];
@faithakinbobola Well done! I could not read through your code easily, you need to break the contents of the arrays to fit in the review box. Thanks.

2020-12-22 08:51 UTC, adaugochi requested changes

2020-12-22 08:51 UTC, adaugochi commented on submissions/akinbobolaFaith/algorithms/product.js
> +            product_price[i] = Math.pow(product_price[i], 2);
I don't think you were asked to look for the `power` of the value. Kindly read the criteria again

2020-12-26 08:04 UTC, adaugochi approved these changes

2020-12-26 08:04 UTC, merged