[216] Product Array Algorithm
Dufuna-CodeCamp/Dufuna-CodeCamp20 pull request #1053
Opened 2020-12-21 09:13 UTC by BenjaminKamena

## Task: `Created agorithm files`
- `Added agorithm files`

2020-12-21 10:19 UTC, ToluAkin requested changes
@BenjaminKamena Good Job! You should remove the unnecessary log files

2020-12-22 08:48 UTC, adaugochi requested changes

2020-12-22 08:48 UTC, adaugochi commented on submissions/benjaminKamena/dataStructure/agorithm.js
> +console.log(products.length);
Is there a reason why you are logging the products length?

2020-12-26 08:03 UTC, adaugochi approved these changes

2020-12-26 08:03 UTC, merged