[216] Product Array Algorithm
Dufuna-CodeCamp/Dufuna-CodeCamp20 pull request #1062
Opened 2020-12-26 11:22 UTC by Cynthia-Berry

## Task: `[216] Product Array Algorithm`
- `Traversing a product array and updating its price`

2020-12-26 14:37 UTC, adaugochi approved these changes

2020-12-26 14:38 UTC, adaugochi requested changes

2020-12-26 14:38 UTC, adaugochi commented on submissions/cynthiaNwakaeme/dataStructure-algorithm/productArray.js
> +    for(product = 0; product < array_name.length; product++) {
declare the `product` using `let` or `var` keyword

2020-12-26 18:33 UTC, BenjaminKamena approved these changes

2020-12-28 10:11 UTC, adaugochi approved these changes

2020-12-28 10:11 UTC, merged