[174] Calculate Product Shipping Cost - Fullstack
Dufuna-CodeCamp/Dufuna-CodeCamp20 pull request #1064
Opened 2020-12-29 22:42 UTC by Marienoir

## Task: `Calculate Product Shipping Cost `
- `I calculated the product shipping cost and validated the product file `

2020-12-30 08:57 UTC, adaugochi requested changes

2020-12-30 08:57 UTC, adaugochi commented on submissions/maryOkosun/dommanipulation/product.js
> +    }
This check `(quantity.value   < 1)` should be on the `else if` statement. There is no need written a function( i.e `checkInteger()` ) for this

2020-12-30 16:49 UTC, adaugochi requested changes

2020-12-30 16:49 UTC, adaugochi commented on submissions/maryOkosun/dommanipulation/product.js
> +    if(!(quantity.value.match(quantityRegex))){
There is no need for this check because the input field can only accept numbers

2020-12-30 16:49 UTC, adaugochi commented on submissions/maryOkosun/dommanipulation/product.js
> +    checkInteger();
Remove this function

2021-01-04 22:18 UTC, Marienoir commented
@adaugochi I have effected all the changes you pointed out. Please review my PR. Thanks

2021-01-05 09:01 UTC, adaugochi approved these changes

2021-01-05 09:01 UTC, merged