[181] How's the weather?
Dufuna-CodeCamp/Dufuna-CodeCamp20 pull request #1075
Opened 2021-01-06 18:25 UTC by kazeemerinfolami

## Task: `[181] How's the weather?`
- `Weather php`

2021-01-07 10:06 UTC, adaugochi requested changes
You have some node module file that is pushed along with this PR. kindly delete them. Click https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp20/pull/1075/files to see what I am talking about

2021-01-07 10:36 UTC, kazeemerinfolami commented
Deleted 🚮 , thank you.

On Thu, 7 Jan 2021 at 11:06, Maryfaith Mgbede <notifications@github.com>
wrote:

> *@adaugochi* requested changes on this pull request.
>
> You have some node module file that is pushed along with this PR. kindly
> delete them. Click
> https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp20/pull/1075/files to
> see what I am talking about
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp20/pull/1075#pullrequestreview-563359825>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/APEJWD5DCKFFHKURNTYPMQDSYWBTTANCNFSM4VX4Z2NQ>
> .
>

2021-01-08 15:17 UTC, adaugochi requested changes

2021-01-08 15:17 UTC, adaugochi commented on submissions/kazeemErinfolami/PHP/weather.php
> +function temperature ($celsius){
Kindly format this block of code to make it lool readable

2021-01-08 17:46 UTC, kazeemerinfolami commented
Corrected 👍🏿

On Fri, 8 Jan 2021, 16:17 Maryfaith Mgbede, <notifications@github.com>
wrote:

> *@adaugochi* requested changes on this pull request.
> ------------------------------
>
> In submissions/kazeemErinfolami/PHP/weather.php
> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp20/pull/1075#discussion_r554003647>
> :
>
> > @@ -0,0 +1,16 @@
> +<?php
> +function temperature ($celsius){
>
> Kindly format this block of code to make it lool readable
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp20/pull/1075#pullrequestreview-564338405>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/APEJWDYHSHKCSKM2MECV6I3SY4OYFANCNFSM4VX4Z2NQ>
> .
>

2021-01-10 14:51 UTC, adaugochi approved these changes

2021-01-10 14:51 UTC, merged