[217] Develop a Customer details list view page and Save Session in a Cookie
Dufuna-CodeCamp/Dufuna-CodeCamp20 pull request #1094
Opened 2021-01-12 12:16 UTC by ainobs

![Screenshot (95)](https://user-images.githubusercontent.com/64330690/104313503-67701580-54d8-11eb-8bc4-ad9c57e6e01d.png)
## Task: `Name of given task`
- `Changes you made to given task`

2021-01-13 11:30 UTC, adaugochi requested changes

2021-01-13 11:30 UTC, adaugochi commented on submissions/victorAienobe/phpDatabase/saveCookie.php
> +        if($result-> rowCount() > 0)  {
Your implementation still doesn't satisfy this `Ensure that you are not hitting the database each time there is a page reload as long as the cookie is still set or hasn't expired yet` criteria. What is having currently, if I reload the page, the `$result` is still coming from the SQL query

2021-01-13 11:32 UTC, adaugochi requested changes

2021-01-13 11:32 UTC, adaugochi commented on submissions/victorAienobe/phpDatabase/accessCookie.php
> +    if(isset($_COOKIE["customer"])) {
This file is unnecessary

2021-01-22 11:00 UTC, ainobs commented
Corrections have been made. Kindly review

On Wed, Jan 13, 2021, 12:32 PM Maryfaith Mgbede <notifications@github.com>
wrote:

> *@adaugochi* requested changes on this pull request.
> ------------------------------
>
> In submissions/victorAienobe/phpDatabase/accessCookie.php
> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp20/pull/1094#discussion_r556453893>
> :
>
> > @@ -0,0 +1,9 @@
> +<?php
> +
> +    if(isset($_COOKIE["customer"])) {
>
> This file is unnecessary
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp20/pull/1094#pullrequestreview-567133671>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/APKZXQQ6NT53FSCZPPMKO6LSZWAEHANCNFSM4V7DYJWQ>
> .
>

2021-01-25 13:16 UTC, adaugochi commented
Kindly update your PR title to the new task title that is on the app. Going forward, I will have to close this PR so you can then create a new one

2021-01-25 13:16 UTC, closed without merging