[218] Develop a List View for Customer Orders And Store The Data in A Cookie
Dufuna-CodeCamp/Dufuna-CodeCamp20 pull request #1099
Opened 2021-01-14 09:00 UTC by Jeffbuchi

![Order Listing](https://user-images.githubusercontent.com/32654841/104567563-8d023980-5614-11eb-96d2-c57558138cc6.PNG)

2021-01-14 15:24 UTC, Ireti203 approved these changes

2021-01-14 15:25 UTC, Ireti203 approved these changes

2021-01-14 15:26 UTC, Ireti203 approved these changes

2021-01-15 09:04 UTC, adaugochi requested changes
And I think you misinterpret this task. So this is what you are asked to do.

Remember in your previous task you wrote a query that returns all customers in a table. Each of the customers has a `view` button. So, anytime I click on each `view` button under a particular customer, I want it to go to a new page where I will see all the `orders` that the customer has made. I hope this is clear

2021-01-18 15:28 UTC, closed without merging