[DJFS-27] Develop an E-commerce store Database
Dufuna-CodeCamp/Dufuna-CodeCamp20 pull request #1100
Opened 2021-01-14 14:18 UTC by ChabuChabu

## Task: `Develop an E-commerce Store Database
- `I created 7 seven tables namely
    
     **administrators**
     **customers**
     **products**
     **orders**
     **order items**
     **categories**
     **addresses**

2021-01-14 15:16 UTC, Ireti203 approved these changes

2021-01-15 09:07 UTC, adaugochi requested changes

2021-01-15 09:07 UTC, adaugochi commented on submissions/chabuChabu/database/init.sql
> +order_date datetime,
well done. Kindly make this column `not null`

2021-01-15 13:32 UTC, adaugochi approved these changes

2021-01-15 13:32 UTC, merged