[DJFS-111] Develop a Customer details list view page
Dufuna-CodeCamp/Dufuna-CodeCamp20 pull request #1146
Opened 2021-01-28 17:39 UTC by MYKEL7

## Task: `Develop a Customer details list view page`
- ` Develop a Customer details list view page using PHP with MySQL Database 
- 
![successful](https://user-images.githubusercontent.com/52843057/106176785-9a5b1000-614c-11eb-8878-9ce21973956f.png)
`

2021-01-29 09:08 UTC, adaugochi requested changes

2021-01-29 09:08 UTC, adaugochi commented on submissions/onyemeMichael/php-db/customerDb.sql
> +USE mix_store;
Kindly use the e-commerce data query you have done before.

2021-01-29 10:47 UTC, MYKEL7 commented
Done.

On Fri, Jan 29, 2021, 10:08 AM Maryfaith Mgbede <notifications@github.com>
wrote:

> *@adaugochi* requested changes on this pull request.
> ------------------------------
>
> In submissions/onyemeMichael/php-db/customerDb.sql
> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp20/pull/1146#discussion_r566675789>
> :
>
> > @@ -0,0 +1,14 @@
> +
> +USE mix_store;
>
> Kindly use the e-commerce data query you have done before.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp20/pull/1146#pullrequestreview-579062067>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AMTFEMNZDW7KRMUTQGMBEMDS4J3JBANCNFSM4WXOO53Q>
> .
>

2021-01-29 11:10 UTC, adaugochi requested changes

2021-01-29 11:10 UTC, adaugochi commented on submissions/onyemeMichael/php-db/customerDb.sql
> +
Why is this file still here? Kindly use the `customers` table you created in the previous task

2021-01-29 11:15 UTC, MYKEL7 commented
That means this file is not needed, I used it, to show you how I used the
database mix_stores for my e-commerce store

On Fri, Jan 29, 2021, 12:11 PM Maryfaith Mgbede <notifications@github.com>
wrote:

> *@adaugochi* requested changes on this pull request.
> ------------------------------
>
> In submissions/onyemeMichael/php-db/customerDb.sql
> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp20/pull/1146#discussion_r566747668>
> :
>
> > @@ -0,0 +1,14 @@
> +
>
> Why is this file still here? Kindly use the customers table you created
> in the previous task
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp20/pull/1146#pullrequestreview-579157950>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AMTFEMPEYTX6CHCQDOFB7JDS4KJULANCNFSM4WXOO53Q>
> .
>

2021-01-29 11:41 UTC, MYKEL7 commented
File removed.

2021-01-29 12:34 UTC, adaugochi requested changes
I have said it before. You are to make use of the previous database task not a new one

2021-01-29 12:34 UTC, adaugochi commented on submissions/onyemeMichael/php-db/cookies.php
> +                    echo "<td>" . $row['full_name'] . "</td>";
There is no column called `full_name` on the customers table
![image](https://user-images.githubusercontent.com/43061141/106275573-59d7c100-6236-11eb-8905-0b3afd3207b2.png)

2021-01-29 12:34 UTC, adaugochi commented on submissions/onyemeMichael/php-db/cookies.php
> +            $sql= "SELECT * FROM customer_details";
And there is no `customer_details` table on your previous task

2021-01-29 12:39 UTC, MYKEL7 commented
I created one, of it so I don't have to drop the customer table, that does
not correspond with the column given to us to do.

On Fri, Jan 29, 2021 at 1:34 PM Maryfaith Mgbede <notifications@github.com>
wrote:

> *@adaugochi* requested changes on this pull request.
>
> I have said it before. You are to make use of the previous database task
> not a new one
> ------------------------------
>
> In submissions/onyemeMichael/php-db/cookies.php
> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp20/pull/1146#discussion_r566789701>
> :
>
> > +$user = new QueryDb();
> +$result = isset($_COOKIE['customer']) ? unserialize($_COOKIE['customer']) : $user->customer();
> +
> +    if(count($result) > 0)  {
> +        echo "<table>";
> +            echo "<tr>";
> +                echo "<th> S/N </th>";
> +                echo "<th> Full Name </th>";
> +                echo "<th> Email Address </th>";
> +                echo "<th> Created At</th>";
> +                echo "<th> Actions </th>";
> +            echo "</tr>";
> +            foreach($result as $row) {
> +                echo "<tr>";
> +                    echo "<td>" . $row['id'] . "</td>";
> +                    echo "<td>" . $row['full_name'] . "</td>";
>
> There is no column called full_name on the customers table
> [image: image]
> <https://user-images.githubusercontent.com/43061141/106275573-59d7c100-6236-11eb-8905-0b3afd3207b2.png>
> ------------------------------
>
> In submissions/onyemeMichael/php-db/cookies.php
> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp20/pull/1146#discussion_r566790182>
> :
>
> > @@ -0,0 +1,50 @@
> +<?php
> +
> +require_once("connection.php");
> +
> +echo "<h3> Customer Details </h3>";
> +
> +//Querying the database to select all information available in the table
> +class QueryDb extends Connect {
> +    public function customer() {
> +        try {
> +            $sql= "SELECT * FROM customer_details";
>
> And there is no customer_details table on your previous task
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp20/pull/1146#pullrequestreview-579213200>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AMTFEMPJQEMKMFHU7GUW2MDS4KTPBANCNFSM4WXOO53Q>
> .
>

2021-01-29 14:05 UTC, adaugochi requested changes

2021-01-29 14:05 UTC, adaugochi commented on submissions/onyemeMichael/database/init.sql
> +        full_name VARCHAR(30) NOT NULL,
Don't change the task. The task says `first_name` and `last_name`.  Don't change it to suit what you need

2021-01-29 16:18 UTC, MYKEL7 commented
Pls check it, the task stipulate  full_name, email_adress, created_at and
id.

On Fri, Jan 29, 2021, 3:05 PM Maryfaith Mgbede <notifications@github.com>
wrote:

> *@adaugochi* requested changes on this pull request.
> ------------------------------
>
> In submissions/onyemeMichael/database/init.sql
> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp20/pull/1146#discussion_r566843762>
> :
>
> > @@ -73,6 +73,21 @@ INSERT INTO customers (firstname, lastname, email, customer_password)
>  VALUES ('Paul', 'Onyeme', 'paulonyeme@email.com', 'paul'),
>  	   ('Mayowa', 'Ojo', 'mayawaojo@email.com', 'mayowa');
>
> +-- customers_datails table
> +CREATE TABLE customer_details(
> +        id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
> +        full_name VARCHAR(30) NOT NULL,
>
> Don't change the task. The task says first_name and last_name. Don't
> change it to suit what you need
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp20/pull/1146#pullrequestreview-579284784>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AMTFEMKCGUJVCZQVSH34MATS4K6ENANCNFSM4WXOO53Q>
> .
>

2021-02-01 09:26 UTC, adaugochi requested changes

2021-02-01 09:26 UTC, adaugochi commented on submissions/onyemeMichael/php-db/cookies.php
> +    public function customer() {
I think `customers` is fine. Because you are not a returning a single customer but many

2021-02-01 09:26 UTC, adaugochi commented on submissions/onyemeMichael/php-db/cookies.php
> +$user = new QueryDb();
user `$query` instead of `$user`

2021-02-01 10:18 UTC, MYKEL7 commented
I have fixed it.

On Mon, Feb 1, 2021, 10:27 AM Maryfaith Mgbede <notifications@github.com>
wrote:

> *@adaugochi* requested changes on this pull request.
> ------------------------------
>
> In submissions/onyemeMichael/php-db/cookies.php
> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp20/pull/1146#discussion_r567673106>
> :
>
> > @@ -0,0 +1,50 @@
> +<?php
> +
> +require_once("connection.php");
> +
> +echo "<h3> Customer Details </h3>";
> +
> +//Querying the database to select all information available in the table
> +class QueryDb extends Connect {
> +    public function customer() {
>
> I think customers is fine. Because you are not a returning a single
> customer but many
> ------------------------------
>
> In submissions/onyemeMichael/php-db/cookies.php
> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp20/pull/1146#discussion_r567673456>
> :
>
> > +    public function customer() {
> +        try {
> +            $sql= "SELECT * FROM customers";
> +            $stmt = $this->conn()->query($sql);
> +            $result = $stmt->fetchAll();
> +
> +        // setting up the cookie to save the result in the databsae
> +        setcookie("customer", serialize($result), time()+7200, "/");
> +        return $result;
> +        } catch (PDOException $e) {
> +            die ('could not execute ' . $sql . $e->getMessage());
> +        }
> +    }
> +}
> +//To call the customer function
> +$user = new QueryDb();
>
> user $query instead of $user
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp20/pull/1146#pullrequestreview-580154659>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AMTFEMK2J24SI6EHCW5YZ4TS4ZXWTANCNFSM4WXOO53Q>
> .
>

2021-02-01 14:25 UTC, adaugochi approved these changes

2021-02-01 14:26 UTC, merged