[DJFS-112] Develop a List View for Customer Orders
Dufuna-CodeCamp/Dufuna-CodeCamp20 pull request #1148
Opened 2021-01-29 13:20 UTC by ainobs

![Screenshot (117)](https://user-images.githubusercontent.com/64330690/106279676-116fd180-623d-11eb-9f3d-0370816f139d.png)
## Task: `Name of given task`
- `Changes you made to given task`

2021-01-30 09:48 UTC, adaugochi requested changes

2021-01-30 11:37 UTC, ainobs commented on submissions/victorAienobe/phpDatabase/listView.php
> +               $sql= "SELECT orders.product_name, orders.order_unit_price,orders.order_quantity,
I made use of the JOIN clause, the first line is commented out. That wasn't the query I used.

2021-01-30 11:39 UTC, ainobs commented on submissions/victorAienobe/phpDatabase/customerDatabase.sql
> +CREATE TABLE orders(
I have just two tables..
One for the previous task, and another for this task to accommodate the customer orders. I don't understand what you mean by changing DB structure

2021-02-01 09:24 UTC, adaugochi requested changes

2021-02-01 09:24 UTC, adaugochi commented on submissions/victorAienobe/phpDatabase/customerDatabase.sql
> +CREATE TABLE orders(
@ainobs You are not expected to create a new table. Kindly work with the existing tables you have on e-commerce database.

2021-02-01 09:24 UTC, adaugochi commented on submissions/victorAienobe/phpDatabase/listView.php
> +               $sql= "SELECT orders.product_name, orders.order_unit_price,orders.order_quantity,
Hint:

The query you are to write here will touch about 4 tables. `orders`, `order_items`, `customer_addresses` and `customers` table. These table already have relationship existing in them

2021-02-01 11:35 UTC, ainobs commented on submissions/victorAienobe/phpDatabase/customerDatabase.sql
> +CREATE TABLE orders(
okay i understand you now...
i thought we were meant to create a new  database for the task, which i did...

2021-02-01 11:37 UTC, ainobs commented on submissions/victorAienobe/phpDatabase/listView.php
> +               $sql= "SELECT orders.product_name, orders.order_unit_price,orders.order_quantity,
thanks, i've made the correction
kindly review

2021-02-02 11:21 UTC, adaugochi approved these changes

2021-02-02 11:21 UTC, merged