[CSFE-17] Calculate Product Shipping Cost
Dufuna-CodeCamp/Dufuna-CodeCamp20 pull request #1151
Opened 2021-01-29 20:48 UTC by cherishebojudah

…out of each page

## Task: `[CSFE-17] Calculate Product Shipping Cost`
- `Made adjustments to styling to fix the navbar and footer`

2021-01-30 09:51 UTC, adaugochi requested changes
I can't find the `js` file for shipping cost calculation

2021-01-30 10:15 UTC, cherishebojudah commented
> I can't find the `js` file for shipping cost calculation

Yes. That's because there were no changes to it in this commit. You've actually merged it prior to now but it didn't reflect on my app due to a naming error on my part, this commit is just to make it reflect on my app so it opens up the next module for me. Thank you.

2021-02-01 09:11 UTC, adaugochi commented
> > I can't find the `js` file for shipping cost calculation
> 
> Yes. That's because there were no changes to it in this commit. You've actually merged it prior to now but it didn't reflect on my app due to a naming error on my part, this commit is just to make it reflect on my app so it opens up the next module for me. Thank you.

ok

2021-02-01 09:11 UTC, adaugochi approved these changes

2021-02-01 09:11 UTC, merged