[CSFS-37] Database Design For A transportation Company
Dufuna-CodeCamp/Dufuna-CodeCamp20 pull request #1154
Opened 2021-01-30 22:04 UTC by Tocyn

![Screenshot 2021-01-30 at 22 58 36](https://user-images.githubusercontent.com/70757475/106369155-5552fb80-634f-11eb-8d10-1edf6fe46c23.png)
![Screenshot 2021-01-30 at 22 58 58](https://user-images.githubusercontent.com/70757475/106369158-57b55580-634f-11eb-8a0c-34658f98f531.png)
![Screenshot 2021-01-30 at 22 58 27](https://user-images.githubusercontent.com/70757475/106369159-5ab04600-634f-11eb-81ca-5cac99129ee9.png)

2021-02-01 09:06 UTC, adaugochi requested changes

2021-02-01 09:06 UTC, adaugochi commented on submissions/oluwatosinOke/database/transportation.sql
> +survived VARCHAR (50) NOT NULL,
`survived` should be either `TINYINT` or `BOOLEAN` not `VARCHAR`

2021-02-01 14:07 UTC, Tocyn commented
@adaugochi 
I have changed the survived column data type.
Kindly Review.

2021-02-02 11:17 UTC, adaugochi requested changes
I hope you rerun this query when you made your changes. If no, kindly drop the database and rerun this query again. If yes, let me know so I approve

2021-02-02 11:52 UTC, Tocyn commented
@adaugochi 
i did rerun the query.
kindly review

2021-02-02 11:56 UTC, Tocyn commented
@adaugochi 
i did rerun the query.
kindly review

2021-02-02 15:29 UTC, adaugochi approved these changes

2021-02-02 15:29 UTC, merged