[CSFS-37] Database Design for a Transportation Company
Dufuna-CodeCamp/Dufuna-CodeCamp20 pull request #1158
Opened 2021-02-01 14:52 UTC by ToluEnny24

i have created a database for a transportation company.
![passengers](https://user-images.githubusercontent.com/70230223/106474671-7168b100-64a5-11eb-82f4-ee1c95f33134.PNG)
![survival](https://user-images.githubusercontent.com/70230223/106474678-7299de00-64a5-11eb-96ba-acafc770db05.PNG)
![travel-details](https://user-images.githubusercontent.com/70230223/106474683-73cb0b00-64a5-11eb-99fd-0298183cf668.PNG)

2021-02-02 11:15 UTC, adaugochi requested changes

2021-02-02 11:15 UTC, adaugochi commented on submissions/fabunmiTolulope/database/LYCAirline.sql
> +age INT NULL,
On line 16, kindly make use of VARCHAR instead of INT

2021-02-02 11:15 UTC, adaugochi commented on submissions/fabunmiTolulope/database/LYCAirline.sql
> +SELECT * FROM travel_details;
Remove all these `SELECT` query

2021-02-02 11:15 UTC, adaugochi commented on submissions/fabunmiTolulope/database/LYCAirline.sql
> +survival_status VARCHAR(20),
On line 43, kindly use TINYINT or BOOLEAN

2021-02-03 03:08 UTC, ToluEnny24 commented
@adaugochi i have effected the requested changes, Thanks.

2021-02-03 09:17 UTC, adaugochi approved these changes

2021-02-03 09:17 UTC, merged