[DJFS-112] Develop a List View for Customer Orders
Dufuna-CodeCamp/Dufuna-CodeCamp20 pull request #1167
Opened 2021-02-03 10:56 UTC by MYKEL7

## Task: `Develop a List View for Customer Orders`
- `Develop a Customer details list view page and Save Session in a Cookie`

![myz](https://user-images.githubusercontent.com/52843057/106737295-5beda700-65cb-11eb-8eaf-acb082219565.png)

2021-02-03 15:26 UTC, adaugochi requested changes

2021-02-03 15:26 UTC, adaugochi commented on submissions/onyemeMichael/database/init.sql
> +INSERT INTO orders (order_amount, ordered_at, customer_orders)
I think `customer_id` was way better

2021-02-03 21:57 UTC, MYKEL7 commented on submissions/onyemeMichael/database/init.sql
> +INSERT INTO orders (order_amount, ordered_at, customer_orders)
Ok, thanks.

2021-02-04 11:24 UTC, adaugochi approved these changes

2021-02-04 11:25 UTC, merged