[CSFS -95] Loops and Numbers
Dufuna-CodeCamp/Dufuna-CodeCamp20 pull request #1179
Opened 2021-02-05 14:45 UTC by kojusola

## Task: `loops and numbers`
- `Added task loops and numbers file`

2021-02-06 10:17 UTC, adaugochi requested changes

2021-02-06 10:17 UTC, adaugochi commented on submissions/adeolaFafemi/php/loopsAndNumbers.php
> +     if($i>100){
I think there is a way to avoid this check. You don't have to do this `if` statement

2021-02-06 10:17 UTC, adaugochi commented on submissions/adeolaFafemi/php/loopsAndNumbers.php
> +    if($i>0 && $i%2 === 0){
You don't need to check if `$i` is greater than `0`

2021-02-06 10:17 UTC, adaugochi commented on submissions/adeolaFafemi/php/loopsAndNumbers.php
> +for($i=0; $i<50; $i++){
Start from `$i = 2` instead

2021-02-06 16:23 UTC, kojusola commented on submissions/adeolaFafemi/php/loopsAndNumbers.php
> +for($i=0; $i<50; $i++){
Done
Thank you

2021-02-08 09:18 UTC, adaugochi approved these changes

2021-02-08 09:18 UTC, merged