[CSFS-94] Hobby Arrays
Dufuna-CodeCamp/Dufuna-CodeCamp20 pull request #1180
Opened 2021-02-05 16:44 UTC by Tocyn

![Screenshot 2021-02-05 at 17 42 42](https://user-images.githubusercontent.com/70757475/107062490-a5abdc80-67d9-11eb-8a60-6b14e3c063cb.png)

2021-02-05 18:56 UTC, BenjaminKamena approved these changes

2021-02-06 10:14 UTC, adaugochi requested changes

2021-02-06 10:14 UTC, adaugochi commented on submissions/oluwatosinOke/php/hobby.php
> +echo "My Name is " .$names[$index]. ", I Love " .$hobby{$index}. ". <br />";
Add indentation on line 8

2021-02-06 17:24 UTC, Tocyn commented
@adaugochi 
I have added indentation to line 8 as requested.

2021-02-08 09:18 UTC, adaugochi approved these changes

2021-02-08 09:18 UTC, merged