[CSFS-111] Develop a Customer details list view page
Dufuna-CodeCamp/Dufuna-CodeCamp20 pull request #1224
Opened 2021-02-14 20:23 UTC by Tocyn

![Screenshot 2021-02-14 at 21 17 47](https://user-images.githubusercontent.com/70757475/107888033-85cb9580-6f0a-11eb-9be9-7dd34bdecf35.png)
![Screenshot 2021-02-14 at 21 17 19](https://user-images.githubusercontent.com/70757475/107888036-882def80-6f0a-11eb-9b76-e95ee8272a03.png)

2021-02-15 10:10 UTC, adaugochi requested changes
You are not supposed to create a new customer table, kindly work with the table you created for the e-commerce task

2021-02-15 10:12 UTC, ToluAkin requested changes

2021-02-15 10:12 UTC, ToluAkin commented on submissions/oluwatosinOke/phpDatabases/customerList.php
> +  $sql = "CREATE TABLE customer (
table names are plural. @Tocyn

2021-02-15 10:12 UTC, ToluAkin commented on submissions/oluwatosinOke/phpDatabases/customerList.php
> +  $conn = new PDO("mysql:host=$servername;dbname=$dbname", $username, $password);
@Tocyn You can have a seperate file for connection. You won't have to repeat this every time but just import where needed.

2021-02-16 12:35 UTC, ToluAkin approved these changes

2021-02-16 12:35 UTC, merged