[CSFS-37] Database Design For a Transportation Company
Dufuna-CodeCamp/Dufuna-CodeCamp20 pull request #1232
Opened 2021-02-16 10:54 UTC by bilkisutace

## Task: `[CSFS-37] Database Design For a Transportation Company`
- `Database Design For a Transportation Company`

2021-02-16 12:12 UTC, BenjaminKamena approved these changes

2021-02-16 15:49 UTC, adaugochi requested changes

2021-02-16 15:49 UTC, adaugochi commented on submissions/bilkisuTace/database/tranportation.sql
> +  `age` int(10) DEFAULT NULL,
Kindly use `VARCHAR` instead of `INT` for `age`. Also, remove the `DEFAULT` there

2021-02-16 15:49 UTC, adaugochi commented on submissions/bilkisuTace/database/tranportation.sql
> +  `status` enum(Did not Survive,Survived) NOT NULL,
`status` will be a `tinyint(1)`

2021-02-16 15:49 UTC, adaugochi commented on submissions/bilkisuTace/database/tranportation.sql
> +
Remove spaces below this file

2021-02-17 08:56 UTC, adaugochi approved these changes

2021-02-17 08:56 UTC, merged