[CSFS-111] Develop a Customer Details view page
Dufuna-CodeCamp/Dufuna-CodeCamp20 pull request #1261
Opened 2021-02-21 11:11 UTC by Tocyn

![Screenshot 2021-02-21 at 12 12 40](https://user-images.githubusercontent.com/70757475/108623181-ddec2580-743d-11eb-8b95-3b284af1c989.png)

2021-02-22 08:53 UTC, Tocyn commented
@tunderabiu2@gmail.com <tunderabiu2@gmail.com> do you want me to change the
error message

On Mon, 22 Feb 2021, 9:42 am Oladejo Babatunde, <notifications@github.com>
wrote:

> *@TundeOladejo* commented on this pull request.
> ------------------------------
>
> In submissions/oluwatosinOke/phpAndDatabases/cookie.php
> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp20/pull/1261#discussion_r579859116>
> :
>
> > @@ -0,0 +1,15 @@
>
> +<?php
>
> +require_once("connection.php");
>
> +try {
>
> +    $sql = "SELECT * FROM customers";
>
> +    $result= $pdo->query($sql);
>
> +    // setting up the cookie to save the result gotten from the databse
>
> +    setcookie("customers", "view", time()+7200, "/");
>
> +    return $result;
>
> +} catch (PDOException $e) {
>
> +die ('haaa...could not execute ' . $sql . $e->getMessage());
>
>
> 🤣 This error message!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp20/pull/1261#pullrequestreview-594876250>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQ32YYYUE3WPB2IXSLDTCRDTAIKH3ANCNFSM4X64BKUQ>
> .
>

2021-02-22 09:07 UTC, adaugochi requested changes

2021-02-22 09:07 UTC, adaugochi commented on submissions/oluwatosinOke/phpAndDatabases/customerlist.php
> +  	$sql = "SELECT * FROM customers";
What is on your `cookie.php` is the same thing you are doing here.

That aside, the idea of this task is to store the result returned from this SQL query in a cookie, Each time I reload this page, I don't want to always run this SQL query but instead, I want to get it from the data stored in the cookie as long as the cookie has not expired. If the cookie is has expired then run the SQL query

With your current implementation, each time I reload this page, I am always executing this SQL query.

2021-02-22 09:18 UTC, Tocyn commented
@adaa@cottacush.com <adaa@cottacush.com>
How can I sort it out

On Mon, 22 Feb 2021, 10:07 am Maryfaith Mgbede, <notifications@github.com>
wrote:

> *@adaugochi* requested changes on this pull request.
> ------------------------------
>
> In submissions/oluwatosinOke/phpAndDatabases/customerlist.php
> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp20/pull/1261#discussion_r580083517>
> :
>
> > @@ -0,0 +1,35 @@
> +<?php
> +require_once("cookie.php");
> +try {
> +  	$sql = "SELECT * FROM customers";
>
> What is on your cookie.php is the same thing you are doing here.
>
> That aside, the idea of this task is to store the result returned from
> this SQL query in a cookie, Each time I reload this page, I don't want to
> always run this SQL query but instead, I want to get it from the data
> stored in the cookie as long as the cookie has not expired. If the cookie
> is has expired then run the SQL query
>
> With your current implementation, each time I reload this page, I am
> always executing this SQL query.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp20/pull/1261#pullrequestreview-595134152>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQ32YY22FT7MSVZU7BOSQSDTAINFVANCNFSM4X64BKUQ>
> .
>

2021-02-23 09:30 UTC, adaugochi requested changes

2021-02-23 09:30 UTC, adaugochi commented on submissions/oluwatosinOke/phpAndDatabases/cookie.php
> +$result = isset($_COOKIE['view']) ? unserialize($_COOKIE['view']) : $view->list($id);
Where is `$view->list($id)` coming from?

2021-02-23 10:23 UTC, Tocyn commented
@adaugochi 
Kindly Review.
Thanks.

2021-02-24 10:35 UTC, adaugochi requested changes

2021-02-24 10:35 UTC, adaugochi commented on submissions/oluwatosinOke/phpAndDatabases/customerlist.php
> +    if ($result->rowCount()>0){
This `$result` is what is always `return` each time you run the `$sql` query in the `cookie.php`. 

What we want is that the `$result` used here to either come from the `$sql`query (if cookie is not set) or from cookie (if cookie is set). You are already storing the data in a cookie called `view` ( see line 8 of cookie,php file) but that's all you are doing. You are not getting it or using it

2021-02-24 11:44 UTC, Tocyn commented
@adaugochi 
Kindly Review.

2021-02-25 09:35 UTC, adaugochi requested changes

2021-02-25 09:35 UTC, adaugochi commented on submissions/oluwatosinOke/phpAndDatabases/customerlist.php
> +$results = isset($_COOKIE['view'])? unserialize($_COOKIE['view']) : $queryDb->getAllCustomers();
Where is this `$queryDb->getAllCustomers()` coming from?

2021-02-25 20:31 UTC, Tocyn commented
@adaugochi 
Kindly Review.

2021-02-26 11:42 UTC, adaugochi requested changes

2021-02-26 11:42 UTC, adaugochi commented on submissions/oluwatosinOke/phpAndDatabases/connection.php
> +  $pdo = new PDO("mysql: host=localhost; dbname=e_store", "root", "tocyn");
In your eCommerce task, this is not what you called your database name

2021-02-26 12:06 UTC, Tocyn commented
Changes have been effected.
Kindly review.

2021-03-01 10:03 UTC, adaugochi approved these changes

2021-03-01 10:03 UTC, merged