[CSFS-112] Develop a List View for Customer Orders
Dufuna-CodeCamp/Dufuna-CodeCamp20 pull request #1288
Opened 2021-03-01 21:28 UTC by Tocyn

![Screenshot 2021-03-01 at 20 44 32](https://user-images.githubusercontent.com/70757475/109561338-52c5fc00-7add-11eb-86ec-a1e029e7e82a.png)

2021-03-02 08:51 UTC, adaugochi requested changes

2021-03-02 08:51 UTC, adaugochi commented on submissions/oluwatosinOke/phpAndDatabases/customerOrder.php
> +    if ($result->rowCount()>0){
the idea of this task is to store the result returned from this SQL query in a cookie, Each time I reload this page, I don't want to always run this SQL query but instead, I want to get it from the data stored in the cookie as long as the cookie has not expired. If the cookie is has expired then run the SQL query
With your current implementation, each time I reload this page, I am always executing this SQL query.

2021-03-03 12:46 UTC, Tocyn commented
Changes have been effected.
Kindly review

2021-03-04 08:52 UTC, adaugochi approved these changes

2021-03-04 08:53 UTC, merged