[CSFS-153] Article Publishing Endpoints
Dufuna-CodeCamp/Dufuna-CodeCamp20 pull request #1302
Opened 2021-03-07 21:07 UTC by kojusola

## Task: `Created Endpoints for Article Publishing`
- `In addition to creating endpoints, I created documentation for the endpoints, the link can be found in the ApiDocumentation.txt file`

2021-03-08 10:12 UTC, adaugochi requested changes
I checked your API documentation, I didn't see your  Example response. it means you didn't save your response you got. Kindly follow the article and give a thumbs up if you find it helpful

2021-03-08 10:12 UTC, adaugochi commented on submissions/adeolaFafemi/phpSlim/app/constants/constants.php
> +}
Remove spaces below

2021-03-08 10:12 UTC, adaugochi commented on submissions/adeolaFafemi/phpSlim/app/controllers/ArticlesController.php
> +            return $response -> withHeader('Content-Type', 'application/json')->withStatus(404);
Use the constant here

2021-03-08 10:12 UTC, adaugochi commented on submissions/adeolaFafemi/phpSlim/app/controllers/ArticlesController.php
> +            return $response -> withHeader('Content-Type', 'application/json')->withStatus(404);
same here

2021-03-08 10:12 UTC, adaugochi commented on submissions/adeolaFafemi/phpSlim/app/controllers/ArticlesController.php
> +            return $response -> withHeader('Content-Type', 'application/json')->withStatus(404);
same here

2021-03-08 15:04 UTC, kojusola commented on submissions/adeolaFafemi/phpSlim/app/controllers/ArticlesController.php
> +            return $response -> withHeader('Content-Type', 'application/json')->withStatus(404);
Corrected.
Thank you.

2021-03-09 08:48 UTC, adaugochi requested changes
Remove `composer.lock` file, it shouldn't be part of your PR

2021-03-09 08:48 UTC, adaugochi commented on submissions/adeolaFafemi/phpSlim/app/constants/constants.php
> +}
Remove spaces below

2021-03-09 14:28 UTC, adaugochi requested changes
Remove composer.lock file
![image](https://user-images.githubusercontent.com/43061141/110485585-1a7d7980-80ec-11eb-9cdb-688087265e5b.png)

2021-03-09 15:07 UTC, kojusola commented
It should be out now. 
Thank you.

2021-03-10 08:59 UTC, adaugochi approved these changes

2021-03-10 08:59 UTC, merged