[DCFS-13] Newsletter Form Validation
Dufuna-CodeCamp/Dufuna-CodeCamp20 pull request #1322
Opened 2021-03-15 11:06 UTC by kemysola

## Task: `Form Validation`
- `Changes you made to given task`
- @adaugochi Good morning ma, Kindly review.Thank you.

2021-03-16 09:10 UTC, kemysola commented
@adaugochi Good morning ma,Kindly review.

2021-03-16 09:38 UTC, adaugochi requested changes

2021-03-16 09:38 UTC, adaugochi commented on submissions/adekemiAwomolo/dom/newsletter.js
> +function validate_data(field,event){
No need to pass `field` as a parameter. It is only `newsemail` that is using this function

2021-03-16 09:38 UTC, adaugochi commented on submissions/adekemiAwomolo/dom/newsletter.js
> +function newsValidation(event){
No need for this function as well

2021-03-17 08:25 UTC, adaugochi requested changes

2021-03-17 08:25 UTC, adaugochi commented on submissions/adekemiAwomolo/htmlForm/signup.html
> +						</form>
Kindly format this block of code properly. check from line 82 - 86

2021-03-17 08:25 UTC, adaugochi commented on submissions/adekemiAwomolo/htmlForm/signup.html
> +	<br>
Use css to style instead of adding `br`

2021-03-17 08:51 UTC, closed without merging