[DCFS-5] Create & Style the Customer Signup Page
Dufuna-CodeCamp/Dufuna-CodeCamp20 pull request #1340
Opened 2021-03-22 09:37 UTC by Keicee32

## Task: `Create & Style the Customer Signup Page`
- `Created the signup page and styled it using the sample format given`

2021-03-23 09:25 UTC, adaugochi requested changes
Well done 

- All images should be inside the `images` folder that is in your `html` folder
- `signup.html` should be inside `html-forms` folder.
- Also, kindly attach a screenshot of your work on the description part of your PR.
- Kindly fix codefactor issues on your PR

2021-03-23 12:05 UTC, Keicee32 commented
![Screenshot (33)](https://user-images.githubusercontent.com/59087407/112143567-59292e80-8bd8-11eb-9053-9a3237d57068.png)
ScreenShot

2021-03-31 08:42 UTC, adaugochi requested changes

2021-03-31 08:42 UTC, adaugochi commented on submissions/egekenzeKelechi/style.css
> +@import url('https://fonts.googleapis.com/css2?family=Roboto&display=swap');
your `style.css` file should be inside `css` folder

2021-03-31 08:42 UTC, adaugochi commented on submissions/egekenzeKelechi/style.css
> +.container{
kindly fix codefactor issue on your PR

2021-03-31 08:46 UTC, adaugochi requested changes

2021-03-31 08:46 UTC, adaugochi commented on submissions/egekenzeKelechi/style.css
> +    display: flex;
Why are you commenting out this CSS code?

2021-04-01 13:47 UTC, Keicee32 commented
![Screenshot (39)](https://user-images.githubusercontent.com/59087407/113303644-32b27400-92f9-11eb-8710-6c57e90581d3.png)

Browser view of my work as requested

2021-04-01 14:09 UTC, ToluAkin commented
@Keicee32 This is not the design for this task. I see you have designed the signup for zeplin. You need a zeplin account to see the design for the task.

2021-04-11 14:24 UTC, closed without merging