[CSFS-153] Article Publishing Endpoints
Dufuna-CodeCamp/Dufuna-CodeCamp20 pull request #1347
Opened 2021-03-28 14:29 UTC by Tocyn

2021-03-29 09:03 UTC, Ireti203 approved these changes

2021-03-29 09:06 UTC, adaugochi requested changes
Well done

2021-03-29 09:06 UTC, adaugochi commented on submissions/oluwatosinOke/slimPhp/app/controllers/ArticlesController.php
> +    public function index(Request $request, Response $response)
You were not asked to get all articles. This endpoint wasn't part of the task

2021-03-29 09:06 UTC, adaugochi commented on submissions/oluwatosinOke/slimPhp/app/controllers/ArticlesController.php
> +    public function publish(Request $request, Response $response, $args)
I am very impressed with the way you handled this endpoint.

2021-03-29 09:07 UTC, adaugochi commented on submissions/oluwatosinOke/slimPhp/app/controllers/ArticlesController.php
> +    public function publish(Request $request, Response $response, $args)
I can't find the link to your documentation. KIndly place the link on your Readme file

2021-04-18 15:54 UTC, Tocyn commented
Comments resolved.
Kindly review.

2021-04-18 19:24 UTC, adaugochi reviewed
I can't find the link to your documentation. Kindly place the link on your Readme file

2021-05-05 07:28 UTC, Ireti203 approved these changes

2021-05-05 07:29 UTC, merged