[DCFS-40] Querying the Transportation Database
Dufuna-CodeCamp/Dufuna-CodeCamp20 pull request #1350
Opened 2021-03-29 12:23 UTC by kemysola

## Task: `DATABASES`
- `Changes you made to given task`

2021-03-29 12:24 UTC, kemysola commented
Good afternoon @adaugochi @Ireti203 .Kindly review my pull request.Thank you

2021-03-30 09:03 UTC, adaugochi requested changes

2021-03-30 09:03 UTC, adaugochi commented on submissions/adekemiAwomolo/database/query.sql
> +SELECT passengers.full_name, passengers.sex FROM passengers LEFT JOIN passengers_details ON passengers.id = passengers_details.passengers_id
there is no column called `full_name` from your database task. Kindly check properly

2021-03-30 09:03 UTC, adaugochi commented on submissions/adekemiAwomolo/database/query.sql
> +SELECT passengers.id,passengers.full_name FROM passengers LEFT JOIN passengers_details ON passengers.id
same here too

2021-03-30 10:54 UTC, adaugochi approved these changes

2021-03-30 10:54 UTC, merged