[DjFS-11] Sign-Up Form Validation
Dufuna-CodeCamp/Dufuna-CodeCamp20 pull request #1351
Opened 2021-03-29 16:07 UTC by MayowaShoyinka

## Task: `[DJFS-11] Sign-Up Form Validation`
- `Created a domManipulation folder`

2021-03-30 08:59 UTC, adaugochi requested changes
Also, you forget to handle the check for password and confirm password if they match

2021-03-30 08:59 UTC, adaugochi commented on submissions/mayowaShoyinka/domManipulation/signupValidation.js
> +
remove the spaces above

2021-03-30 08:59 UTC, adaugochi commented on submissions/mayowaShoyinka/domManipulation/signupValidation.js
> +;
this semicolon should be on line 12 after the closing `)`

2021-03-30 08:59 UTC, adaugochi commented on submissions/mayowaShoyinka/domManipulation/signupValidation.js
> +  function validateSignup(field,regdex,errorOne,errorTwo, event) {
kindly format this block of code properly

2021-03-30 08:59 UTC, adaugochi commented on submissions/mayowaShoyinka/domManipulation/signupValidation.js
> +    let nameRegex =  /^[A-Za-z]+$/,
declare all these variables outside the function for better performance

2021-04-01 18:27 UTC, MayowaShoyinka commented
Changes Made, Thanks...Kindly Review.

2021-04-02 17:15 UTC, adaugochi commented
The `J` in [DJFS-11]` should be in capital letter.  Kindly create a new PR. I will have to close this one

2021-04-02 17:15 UTC, closed without merging