[CSFS-156] Build a To-Do App with REACT
Dufuna-CodeCamp/Dufuna-CodeCamp20 pull request #1376
Opened 2021-04-13 15:16 UTC by Marienoir

## Task: `Build a To-Do App with REACT`
- `I Built a To-Do App with REACT`

2021-04-14 09:29 UTC, Ireti203 commented
Attach the screenshot of your work.

2021-04-14 14:01 UTC, Marienoir commented
Screeenshots of the todo app

![todo1](https://user-images.githubusercontent.com/40265625/114722914-0e8a6600-9cef-11eb-8f6e-b99876b73b46.PNG)
![todo3](https://user-images.githubusercontent.com/40265625/114722922-10542980-9cef-11eb-8019-34675c24d9b5.PNG)
![todo2](https://user-images.githubusercontent.com/40265625/114722927-11855680-9cef-11eb-82e0-a93743db4733.PNG)

2021-04-14 14:11 UTC, Marienoir commented
I have added screenshots of the app and also fixed codefactor issue.
@Ireti203 Please review. Thanks

2021-04-14 14:58 UTC, Ireti203 requested changes

2021-04-14 14:58 UTC, Ireti203 commented on submissions/maryOkosun/react/public/index.html
> +      To begin the development, run `npm start` or `yarn start`.
Remove commented out code

2021-04-15 10:19 UTC, Marienoir commented
Added screenshots of the "xxx entries left"
![1 1](https://user-images.githubusercontent.com/40265625/114853951-399eb380-9ddc-11eb-94ff-cb2b15a8e4b3.PNG)
![2 1](https://user-images.githubusercontent.com/40265625/114853997-458a7580-9ddc-11eb-9465-2113c2994224.PNG)

2021-04-15 10:19 UTC, Marienoir commented
@Ireti203  Please review my PR. Thanks

2021-04-15 10:25 UTC, Ireti203 approved these changes

2021-04-15 10:26 UTC, merged