[CSFS-156] Build a To-Do App with REACT
Dufuna-CodeCamp/Dufuna-CodeCamp20 pull request #1397
Opened 2021-05-09 22:05 UTC by Tocyn

![Screenshot 2021-05-09 at 22 35 37](https://user-images.githubusercontent.com/70757475/117588394-fb668c80-b11a-11eb-820d-5b53ed150b58.png)
![Screenshot 2021-05-09 at 22 34 56](https://user-images.githubusercontent.com/70757475/117588386-f275bb00-b11a-11eb-899d-2c20ae6aa5ac.png)

2021-05-11 10:21 UTC, ToluAkin requested changes
Well done @Tocyn

2021-05-11 10:21 UTC, ToluAkin commented on submissions/oluwatosinOke/react/src/App.js
> +  const [todos, setTodos] = React.useState([
@Tocyn You are not expect to have the list in state. You are meant to create the list in the browser and push the values in to the array here.

2021-05-12 09:15 UTC, Tocyn commented
@ToluAkin Kindly Review

2021-05-12 09:15 UTC, Tocyn commented
@ToluAkin Kindly Review

2021-05-13 14:31 UTC, Tocyn commented
@ToluAkin 
Changes have been effected.
Kindly Review

2021-05-14 11:58 UTC, ToluAkin requested changes

2021-05-14 11:58 UTC, ToluAkin commented on submissions/oluwatosinOke/react/src/App.js
> +import 'bootstrap/dist/css/bootstrap.min.css';
You are  not meant to use any css library for this project. Kindly remove and all instances of the its implementation in classes and js @Tocyn

2021-05-14 11:58 UTC, ToluAkin commented on submissions/oluwatosinOke/react/src/index.js
> +  <React.StrictMode>
Remove this `<React.StrictMode>`

2021-05-14 12:12 UTC, Tocyn commented
@ToluAkin 
Requested changes have been effected.
Kindly Review.

2021-05-14 12:15 UTC, Tocyn commented
@ToluAkin 
I have effected the requested changes.
Kindly review

2021-05-14 12:19 UTC, ToluAkin requested changes

2021-05-14 12:19 UTC, ToluAkin commented on submissions/oluwatosinOke/react/src/index.js
> +import reportWebVitals from './reportWebVitals';
REmove this in package.json and here

2021-05-14 12:20 UTC, ToluAkin commented on submissions/oluwatosinOke/react/src/index.js
> +import reportWebVitals from './reportWebVitals';
Make sure to run `npm install` again after updating the package.json

2021-05-14 12:23 UTC, ToluAkin commented
@Tocyn I noticed that after unchecking an item, the color change is still there and the cross line. Also, your page is not mobile responsive which should not be.

2021-05-14 13:10 UTC, Tocyn commented
@ToluAkin 
Requested changes have been effected
Kindly review.
![Screenshot 2021-05-14 at 14 11 31](https://user-images.githubusercontent.com/70757475/118274946-ada4a800-b4bd-11eb-8277-cfc5e411d6c6.png)

2021-05-14 14:05 UTC, ToluAkin requested changes
@Tocyn I mentioned that when I unclick a list on the todo, it is still crossed out and color unchanged. Also your work is not mobile responsive.

2021-05-14 14:06 UTC, ToluAkin commented
Click on this [link](![image](https://user-images.githubusercontent.com/38213766/118282209-f5c7c880-b4c5-11eb-9083-21b3eef07097.png)) to see the responsiveness I am having on my end

2021-05-14 16:13 UTC, Tocyn commented
@ToluAkin 
The image you sent is not what i have.
what do I do?

2021-05-14 16:18 UTC, ToluAkin commented
> @ToluAkin 
> The image you sent is not what i have.
> what do I do?

Could attach images in mobile and tablet screen from your end here? Also, as the checked and unchecked issue been fixed?

2021-05-14 18:38 UTC, Tocyn commented
@ToluAkin 
Requested changes have been effected
Kindly Review
![Screenshot 2021-05-14 at 19 41 43](https://user-images.githubusercontent.com/70757475/118314322-e5c2df80-b4eb-11eb-8b41-9f10c2cf0233.png)
![Screenshot 2021-05-14 at 19 40 17](https://user-images.githubusercontent.com/70757475/118314329-e8253980-b4eb-11eb-9cfe-43b821470267.png)

2021-05-18 14:40 UTC, Tocyn commented
@ToluAkin
Kindly review

2021-05-21 11:27 UTC, Tocyn commented
@ToluAkin 
kindly review

2021-05-21 17:47 UTC, ToluAkin approved these changes
Well done @Tocyn. Good Job

2021-05-21 17:48 UTC, merged