[8] Add Page Navigation to your Pages
Dufuna-CodeCamp/Dufuna-CodeCamp20 pull request #353
Opened 2020-08-20 11:44 UTC by Lolatech07

## Task: `Add Page Navigation to your pages`
- `Task submission
![Screenshot Page](https://user-images.githubusercontent.com/67680490/90766024-d14a1180-e2e2-11ea-8e91-729ef60cea7a.png)
`

2020-08-20 12:22 UTC, adaugochi requested changes
This is not what you are ask to do

2020-08-20 12:23 UTC, adaugochi commented
You ask to create navigation links on your product page and contact form page

2020-08-20 12:27 UTC, Lolatech07 commented
I see. My oversight. I didn't understand the task as you explained.

So navigation link for Product page to be on the contact page and vice
versa?

On Thu, Aug 20, 2020, 1:23 PM Maryfaith Mgbede <notifications@github.com>
wrote:

> You ask to create navigation links on your product page and contact form
> page
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp20/pull/353#issuecomment-677631778>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQELR2UYAY7DDQE664VELNDSBUIT7ANCNFSM4QF6UJPA>
> .
>

2020-08-20 13:27 UTC, Lolatech07 commented
Hello. Could you kindly respond?

Thanks.

On Thu, 20 Aug 2020 at 13:27, Ola Oluwa <olaoluw07@gmail.com> wrote:

> I see. My oversight. I didn't understand the task as you explained.
>
> So navigation link for Product page to be on the contact page and vice
> versa?
>
> On Thu, Aug 20, 2020, 1:23 PM Maryfaith Mgbede <notifications@github.com>
> wrote:
>
>> You ask to create navigation links on your product page and contact form
>> page
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp20/pull/353#issuecomment-677631778>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/AQELR2UYAY7DDQE664VELNDSBUIT7ANCNFSM4QF6UJPA>
>> .
>>
>

2020-08-20 14:35 UTC, Lolatech07 commented
> You ask to create navigation links on your product page and contact form page



> You ask to create navigation links on your product page and contact form page

Hi. Please review updates to my PR. Thanks.

2020-08-20 14:37 UTC, Lolatech07 commented
Hi. Please review changes to my PR. Thanks.

On Thu, Aug 20, 2020, 1:23 PM Maryfaith Mgbede <notifications@github.com>
wrote:

> You ask to create navigation links on your product page and contact form
> page
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp20/pull/353#issuecomment-677631778>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQELR2UYAY7DDQE664VELNDSBUIT7ANCNFSM4QF6UJPA>
> .
>

2020-08-20 14:48 UTC, ToluAkin requested changes
@Lolatech07 You need to link your ecommerce page with contact form.

2020-08-20 14:48 UTC, ToluAkin commented on submissions/lolaOluwadahunsi/htmlForms/ecommerce_website.html
> +<!DOCTYPE html>
This file already exist in your html folder. You should remove it from here. @Lolatech07

2020-08-20 14:48 UTC, ToluAkin commented on submissions/lolaOluwadahunsi/htmlForms/contact_form_page.html
> +        <li><a href="ecommerce_website.html">Products</a></li>
Link to the page in your html folder

2020-08-20 17:45 UTC, Lolatech07 commented
Hi Tolu.

I thought I already linked the ecommerce and contact pages.

If you please clarify what I need to do here.

I've gone through additional resources as well and I'm not sure what else
needs to be done.

Thanks.

On Thu, 20 Aug 2020 at 15:48, ToluAkin <notifications@github.com> wrote:

> *@ToluAkin* requested changes on this pull request.
>
> @Lolatech07 <https://github.com/Lolatech07> You need to link your
> ecommerce page with contact form.
> ------------------------------
>
> In submissions/lolaOluwadahunsi/htmlForms/ecommerce_website.html
> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp20/pull/353#discussion_r474038916>
> :
>
> > @@ -0,0 +1,97 @@
> +<!DOCTYPE html>
>
> This file already exist in your html folder. You should remove it from
> here. @Lolatech07 <https://github.com/Lolatech07>
> ------------------------------
>
> In submissions/lolaOluwadahunsi/htmlForms/contact_form_page.html
> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp20/pull/353#discussion_r474039348>
> :
>
> > @@ -5,6 +5,12 @@
>      <title>Contact Form</title>
>  </head>
>  <body>
> +<nav>
> +    <ul>
> +        <li><a href="ecommerce_website.html">Products</a></li>
>
> Link to the page in your html folder
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp20/pull/353#pullrequestreview-471688425>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQELR2Q7R5XTQEJKNJSEWFDSBUZVTANCNFSM4QF6UJPA>
> .
>

2020-08-24 08:50 UTC, ToluAkin commented
@Lolatech07 This should help []( https://www.w3schools.com/Html/html_filepaths.asp)

2020-08-31 14:42 UTC, closed without merging