[15] Research Programming Languages
Dufuna-CodeCamp/Dufuna-CodeCamp20 pull request #366
Opened 2020-08-23 12:22 UTC by kamena1994

## Task: `Research programming languages`
- `added programming language folder and 
text file`

2020-08-24 08:39 UTC, adaugochi requested changes
Also, remove the space in programming language.txt

2020-08-24 09:02 UTC, ToluAkin requested changes

2020-08-24 09:02 UTC, ToluAkin commented on submissions/benjaminKamena/aboutMe/aboutMe.txt.txt
> +Am benjamin kamena,
@kamena1994 This file exist already. Remove it from your pull request. To do that, make sure you are on this branch, delete this file, do `git add .`, commit the changes, then push.

2020-08-25 09:47 UTC, adaugochi commented
Why are you deleting all your files

2020-08-26 08:23 UTC, adaugochi requested changes
Remove the spaces in `Programing Languages 1`. you can replace it with `_` or `-`

2020-08-26 08:50 UTC, ToluAkin approved these changes

2020-08-26 08:50 UTC, merged