[13]styled productpage
Dufuna-CodeCamp/Dufuna-CodeCamp20 pull request #406
Opened 2020-08-31 10:05 UTC by Iyiola-stack

## Task: `Styled the product page using css
![desk1](https://user-images.githubusercontent.com/61589702/91708846-d0826c80-eb79-11ea-94d3-2db3260fb810.PNG)
![mo1](https://user-images.githubusercontent.com/61589702/91708869-d710e400-eb79-11ea-9463-e490670232c6.PNG)
![mo2](https://user-images.githubusercontent.com/61589702/91708891-e001b580-eb79-11ea-9234-e82e8250b9e2.PNG)

- `Changes you made to given task`

2020-08-31 10:17 UTC, adaugochi commented
Well done. Please add space between each product related items on the mobile screen size. They are too close

2020-08-31 10:26 UTC, ToluAkin requested changes

2020-08-31 10:26 UTC, ToluAkin commented on submissions/peterIyiola/css/productpage.css
> +.productpagelink {
@Iyiola-stack You can group 14-16. They have the same style.

2020-08-31 10:26 UTC, ToluAkin commented on submissions/peterIyiola/css/productpage.css
> +    margin-left: 10%;
Use `px` instead of `%` @Iyiola-stack

2020-08-31 10:26 UTC, ToluAkin commented on submissions/peterIyiola/css/productpage.css
> +    margin-left: 13%;
Use `px` instead of `%` @Iyiola-stack

2020-08-31 10:26 UTC, ToluAkin commented on submissions/peterIyiola/css/productpage.css
> +    margin-left: 14%;
Use `px` instead of `%` @Iyiola-stack

2020-08-31 18:02 UTC, closed without merging

2020-09-01 09:53 UTC, Iyiola-stack commented
Goodmorning,
Kindly help with my PR
https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp20/pull/414/commits

On Mon, Aug 31, 2020 at 11:26 AM ToluAkin <notifications@github.com> wrote:

> *@ToluAkin* requested changes on this pull request.
> ------------------------------
>
> In submissions/peterIyiola/css/productpage.css
> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp20/pull/406#discussion_r480034465>
> :
>
> > @@ -0,0 +1,182 @@
> +.flex-container   {
> +    display: flex;
> +    flex-direction: row;
> +    flex-wrap: wrap;
> +    background-color: greenyellow;
> +    padding: 5px;
> +    justify-content: space-around;
> +}
> +.logo   {
> +    height: 30px;
> +    width: 40px;
> +}
> +
> +.productpagelink {
>
> @Iyiola-stack <https://github.com/Iyiola-stack> You can group 14-16. They
> have the same style.
> ------------------------------
>
> In submissions/peterIyiola/css/productpage.css
> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp20/pull/406#discussion_r480034993>
> :
>
> > +}
> +@media screen and (max-width:480px) {
> +
> +.flex-container {
> +    display:flex;
> +    flex-direction: column;
> +    flex-wrap: wrap;
> +}
> +.grid-similaritems   {
> +    display:block;
> +    justify-items: center;
> +    align-items: center;
> +
> +}
> +.similaritem1   {
> +    margin-left: 10%;
>
> Use px instead of % @Iyiola-stack <https://github.com/Iyiola-stack>
> ------------------------------
>
> In submissions/peterIyiola/css/productpage.css
> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp20/pull/406#discussion_r480035024>
> :
>
> > +.flex-container {
> +    display:flex;
> +    flex-direction: column;
> +    flex-wrap: wrap;
> +}
> +.grid-similaritems   {
> +    display:block;
> +    justify-items: center;
> +    align-items: center;
> +
> +}
> +.similaritem1   {
> +    margin-left: 10%;
> +}
> +.similaritem2   {
> +    margin-left: 13%;
>
> Use px instead of % @Iyiola-stack <https://github.com/Iyiola-stack>
> ------------------------------
>
> In submissions/peterIyiola/css/productpage.css
> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp20/pull/406#discussion_r480035068>
> :
>
> > +}
> +.grid-similaritems   {
> +    display:block;
> +    justify-items: center;
> +    align-items: center;
> +
> +}
> +.similaritem1   {
> +    margin-left: 10%;
> +}
> +.similaritem2   {
> +    margin-left: 13%;
> +}
> +.similaritem3   {
> +    margin-right:50px;
> +    margin-left: 14%;
>
> Use px instead of % @Iyiola-stack <https://github.com/Iyiola-stack>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp20/pull/406#pullrequestreview-478490266>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOV4RRTFKXQJ5VQG6BGE7BDSDN3GXANCNFSM4QQK3GDA>
> .
>