[10] Create & Style the Customer Signup Page  using CSS
Dufuna-CodeCamp/Dufuna-CodeCamp20 pull request #424
Opened 2020-09-01 13:31 UTC by MayowaShoyinka

## Task: `[10] Create & Style the Customer Signup Page  using CSS`
- `rearranged my files to the right folder and deleted the not needed files`
![signup-phone-view](https://user-images.githubusercontent.com/47593314/91856027-d7ad8700-ec1a-11ea-9484-809de1dc2636.PNG)
![signup-phone-view2](https://user-images.githubusercontent.com/47593314/91856041-dc723b00-ec1a-11ea-97c0-9a7d450ecd89.PNG)
![signup-tablet-view](https://user-images.githubusercontent.com/47593314/91856053-e005c200-ec1a-11ea-87e6-24f3a6d04889.PNG)
![signup-tablet-view2](https://user-images.githubusercontent.com/47593314/91856066-e431df80-ec1a-11ea-8ad9-18c2f6dcd60d.PNG)
![signup-web-view](https://user-images.githubusercontent.com/47593314/91856088-ed22b100-ec1a-11ea-83b1-666615b5234c.PNG)

`

2020-09-01 13:33 UTC, MayowaShoyinka commented
Changes Made @adaugochi

2020-09-01 15:58 UTC, adaugochi reviewed
Well done.

Please create an `images` folder inside your `html` folder and place all your images there

2020-09-01 15:58 UTC, adaugochi commented on submissions/mayowaShoyinka/css/signupstyle.css
> +
Remove spaces from line 211 - 214

2020-09-02 10:42 UTC, ToluAkin requested changes

2020-09-02 10:42 UTC, ToluAkin commented on submissions/mayowaShoyinka/css/signupstyle.css
> +.Navigation-header{
Update the class name to be in lowercase @MayowaShoyinka

2020-09-02 10:42 UTC, ToluAkin commented on submissions/mayowaShoyinka/css/signupstyle.css
> +  padding:25px 4em 0 20px;
Update the unit from `em` to `px`

2020-09-02 10:42 UTC, ToluAkin commented on submissions/mayowaShoyinka/css/signupstyle.css
> +.Navigation-header a{
Update the class name to be in lowercase @MayowaShoyinka

2020-09-02 10:42 UTC, ToluAkin commented on submissions/mayowaShoyinka/css/signupstyle.css
> +.Navigation-header a.logo{
Update the class name to be in lowercase @MayowaShoyinka

2020-09-02 10:42 UTC, ToluAkin commented on submissions/mayowaShoyinka/css/signupstyle.css
> +.Navigation-header-link{
Update the class name to be in lowercase @MayowaShoyinka

2020-09-02 10:42 UTC, ToluAkin commented on submissions/mayowaShoyinka/css/signupstyle.css
> +.Navigation-header a{
Update the class name to be in lowercase @MayowaShoyinka

2020-09-02 10:42 UTC, ToluAkin commented on submissions/mayowaShoyinka/css/signupstyle.css
> +  .Navigation-header-link{
Update the class name to be in lowercase @MayowaShoyinka

2020-09-02 16:57 UTC, MayowaShoyinka commented
changes made @ToluAkin

2020-09-02 21:02 UTC, closed without merging