[16] Render the related product list on the HTML page with JavaScript
Dufuna-CodeCamp/Dufuna-CodeCamp20 pull request #462
Opened 2020-09-07 15:09 UTC by tomike19

## Task: `Name of given task`
- `Changes you made to given task`

2020-09-07 15:19 UTC, ToluAkin requested changes
@tomike19 Javascript can not interpret `&#163;` update to use `NGN` or `N`

2020-09-07 15:54 UTC, ToluAkin requested changes
@tomike19 use camelCase as have done for other to name the ImageUrl

2020-09-08 08:33 UTC, ToluAkin requested changes

2020-09-08 08:33 UTC, ToluAkin commented on submissions/kolajoTomike/Javascript/app.js
> +  ImageUrl:"../html/img/hand.png",
@tomike19 I think you should change this key name to be in `camelCase` just like the others.

2020-09-08 09:06 UTC, adaugochi commented on submissions/kolajoTomike/Javascript/app.js
> +
Remove spaces from line 25 - 28

2020-09-08 10:04 UTC, ToluAkin approved these changes

2020-09-08 10:04 UTC, merged