[18] The Software Developer conditionals
Dufuna-CodeCamp/Dufuna-CodeCamp20 pull request #488
Opened 2020-09-10 19:51 UTC by Oyeteju

## Task: `Name of given task`
- `Changes you made to given task`

2020-09-11 09:02 UTC, ToluAkin requested changes

2020-09-11 09:02 UTC, ToluAkin commented on submissions/oyetejuOloyede/javaScript/conditionals.js
> +    output = i;
you are suppose to log `software development`  in this case @Oyeteju

2020-09-11 09:23 UTC, adaugochi requested changes
Make use of `else if` statement as well. The `else` block should output `i` instead

2020-09-16 08:41 UTC, ToluAkin requested changes

2020-09-16 08:41 UTC, ToluAkin commented on submissions/oyetejuOloyede/javaScript/conditionals.js
> +for(var i = 1; i < x; i++){
@Oyeteju `i <= x`

2020-09-17 09:08 UTC, ToluAkin approved these changes

2020-09-17 09:08 UTC, merged