[21] Contact Form Validation
Dufuna-CodeCamp/Dufuna-CodeCamp20 pull request #504
Opened 2020-09-13 20:04 UTC by kamena1994

## Task: `created the contact validation`
![contactValidation](https://user-images.githubusercontent.com/37587336/93027397-cd24c180-f60c-11ea-97bc-fad14498d012.PNG)

- `created contact.js and modified contact.html and contact.css`

2020-09-14 08:49 UTC, ToluAkin requested changes
I think you should close the PR till the other one is merged. There are files in this pull request, same as the other one with changes which will cause a merge conflict. @kamena1994

2020-09-17 09:09 UTC, ToluAkin requested changes
@kamena1994 This is PR is for contact form validation not signup

2020-09-17 14:50 UTC, ToluAkin requested changes

2020-09-17 14:50 UTC, ToluAkin commented on submissions/benjaminKamena/Dom/signUp.js
> +// sign-up form validation
@kamena1994 This file is not suppose to be in this PR

2020-09-17 14:55 UTC, ToluAkin requested changes
Merge required, email and full name validation into one then  merge subject and message in to one just like  you did for signup.js @kamena1994

2020-09-17 14:59 UTC, adaugochi requested changes
Almost all your functions do the same thing, which is checking if a field is empty. You didn't make a function to do what it is supposed to (which is to ensure code reusability). I will advise that you write a single function(maybe call it required) that handles that. the only difference is the field and the error message you intend to display. In that case, pass them as a parameter on the function.

2020-09-17 14:59 UTC, closed without merging