[18]Software Developer Conditionals
Dufuna-CodeCamp/Dufuna-CodeCamp20 pull request #505
Opened 2020-09-14 09:10 UTC by Iyiola-stack

## Task: `Created a conditional statement
- `Changes you made to given task`

2020-09-14 10:06 UTC, adaugochi requested changes

2020-09-14 10:06 UTC, adaugochi commented on submissions/peterIyiola/JS/index2.js
> +if (i % 3 ==0 && i % 5 ==0)
This should be executed first. Also, make use of `if else if and else` statement

2020-09-14 13:44 UTC, adaugochi requested changes

2020-09-14 13:44 UTC, adaugochi commented on submissions/peterIyiola/JS/index2.js
> +    console.log("Software" + " " + "Developer");
No need to do a concatenation here simply do `("Software Developer")`

2020-09-14 13:44 UTC, adaugochi commented on submissions/peterIyiola/JS/index2.js
> +else  (i % 5 ==0)
Also, console.log(i) in your else block instead

2020-09-14 14:53 UTC, Iyiola-stack commented
Done

On Mon, Sep 14, 2020 at 2:45 PM Maryfaith Mgbede <notifications@github.com>
wrote:

> *@adaugochi* requested changes on this pull request.
> ------------------------------
>
> In submissions/peterIyiola/JS/index2.js
> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp20/pull/505#discussion_r487927863>
> :
>
> > @@ -0,0 +1,12 @@
> +for (let i = 1; i <= 116; i++)
> +{
> +
> +if (i % 3 ==0 && i % 5 ==0)
> +    console.log("Software" + " " + "Developer");
>
> No need to do a concatenation here simply do ("Software Developer")
> ------------------------------
>
> In submissions/peterIyiola/JS/index2.js
> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp20/pull/505#discussion_r487928559>
> :
>
> > @@ -0,0 +1,12 @@
> +for (let i = 1; i <= 116; i++)
> +{
> +
> +if (i % 3 ==0 && i % 5 ==0)
> +    console.log("Software" + " " + "Developer");
> +
> +else if( i % 3 ==0)
> +    console.log("software");
> +
> +else  (i % 5 ==0)
>
> Also, console.log(i) in your else block instead
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp20/pull/505#pullrequestreview-487782636>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOV4RRWB5APOIBDNSHRFBOLSFYM6NANCNFSM4RLLEHBA>
> .
>

2020-09-14 16:13 UTC, adaugochi requested changes

2020-09-14 16:13 UTC, adaugochi commented on submissions/peterIyiola/JS/index2.js
> +else  (i % 5 ==0)
Did you forget about this condition `(i % 5 ==0)`

2020-09-14 19:57 UTC, Iyiola-stack commented
What do you want me to do with this condition

On Mon, Sep 14, 2020 at 5:14 PM Maryfaith Mgbede <notifications@github.com>
wrote:

> *@adaugochi* requested changes on this pull request.
> ------------------------------
>
> In submissions/peterIyiola/JS/index2.js
> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp20/pull/505#discussion_r488056096>
> :
>
> > @@ -0,0 +1,12 @@
> +for (let i = 1; i <= 116; i++)
> +{
> +
> +if (i % 3 ==0 && i % 5 ==0)
> +    console.log("Software" + " " + "Developer");
> +
> +else if( i % 3 ==0)
> +    console.log("software");
> +
> +else  (i % 5 ==0)
>
> Did you forget about this condition (i % 5 ==0)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp20/pull/505#pullrequestreview-487934163>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOV4RRWQLA6CZB36Q27MHJTSFY6NNANCNFSM4RLLEHBA>
> .
>

2020-09-15 08:51 UTC, ToluAkin commented
@Iyiola-stack Your output based on the logic of the task should be 4. Updated your logic to what @adaugochi mentioned.

2020-09-15 10:52 UTC, Iyiola-stack commented
done

On Tue, Sep 15, 2020 at 9:51 AM ToluAkin <notifications@github.com> wrote:

> @Iyiola-stack <https://github.com/Iyiola-stack> Your output based on the
> logic of the task should be 4. Updated your logic to what @adaugochi
> <https://github.com/adaugochi> mentioned.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp20/pull/505#issuecomment-692569429>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOV4RRVXPL4VJY6JZ7VWKMTSF4TJHANCNFSM4RLLEHBA>
> .
>

2020-09-15 11:34 UTC, ToluAkin requested changes
@Iyiola-stack You are still not doing what is required of the task.

2020-09-15 12:00 UTC, Iyiola-stack commented
Please,I need clarification on what is expected of me at this point.
I'm confused really

On Tue, Sep 15, 2020 at 12:35 PM ToluAkin <notifications@github.com> wrote:

> *@ToluAkin* requested changes on this pull request.
>
> @Iyiola-stack <https://github.com/Iyiola-stack> You are still not doing
> what is required of the task.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp20/pull/505#pullrequestreview-488589641>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOV4RRSNJQPSDJEZLG54SQDSF5GOJANCNFSM4RLLEHBA>
> .
>

2020-09-15 15:22 UTC, ToluAkin requested changes
@Iyiola-stack Please go through the comments by @adaugochi again

2020-09-16 08:28 UTC, ToluAkin commented
@Iyiola-stack you still need the output the number if it does not match any of those criteria.

2020-09-16 11:15 UTC, ToluAkin requested changes
@Iyiola-stack You are meant to only out the strings when the conditions are met not the number and string

2020-09-16 11:58 UTC, ToluAkin approved these changes

2020-09-16 11:58 UTC, merged