[21] Contact Form Validation
Dufuna-CodeCamp/Dufuna-CodeCamp20 pull request #542
Opened 2020-09-17 18:24 UTC by kamena1994

## Task: `Dom task`
- `added contact.js file`
![contactValidation](https://user-images.githubusercontent.com/37587336/93511901-cc996d00-f923-11ea-80fa-1c10b54162c5.PNG)

2020-09-18 08:53 UTC, ToluAkin requested changes

2020-09-18 08:53 UTC, ToluAkin commented on submissions/benjaminKamena/Dom/signUp.js
> +
This file exist already. Remove it from this pull request. I think you should sync your branch so you can get the file from the previous pull request @BenjaminKamena

2020-09-18 08:53 UTC, ToluAkin commented on submissions/benjaminKamena/JavaScript/index.js
> +
Same comment as above

2020-09-18 08:53 UTC, ToluAkin commented on submissions/benjaminKamena/JavaScript/index.html
> +<head>
Same comment as above

2020-09-18 15:15 UTC, BenjaminKamena commented on submissions/benjaminKamena/JavaScript/index.html
> +<head>
I have removed the files as requested

2020-09-18 16:39 UTC, adaugochi approved these changes
Some of the files you pushed already existed. Ensure you sync your branch

2020-09-19 11:51 UTC, adaugochi commented on submissions/benjaminKamena/Dom/contact.js
> +        return false;
This should return true

2020-09-21 08:31 UTC, adaugochi approved these changes

2020-09-21 08:31 UTC, merged