[20] Sign-Up Form Validation
Dufuna-CodeCamp/Dufuna-CodeCamp20 pull request #564
Opened 2020-09-21 15:40 UTC by emmanuelidiaghe

## Task: [20] Sign-Up Form Validation
- Validated signup Form

2020-09-22 09:03 UTC, adaugochi requested changes

2020-09-22 09:03 UTC, adaugochi commented on submissions/EmmanuelIdiaghe/domManipulation/sign-up.js
> +    if (!(name.value == "") && (!(name.value.match(RegexMatch)))) {
I don't think there is need to check if a value is empty here again. just check for the regexMatch. Cos in the validateForm function. The required function is executed first, which already checks for empty state

2020-09-23 10:33 UTC, emmanuelidiaghe commented
I’ve made changes

2020-09-23 10:45 UTC, adaugochi approved these changes

2020-09-23 10:46 UTC, merged