[45] Product Page Using HTML
Dufuna-CodeCamp/Dufuna-CodeCamp20 pull request #606
Opened 2020-09-24 18:00 UTC by ayotola-t

## Task: `Product Page for a e-commerce store using HTML only`
<img width="570" alt="Screenshot 2020-09-24 at 6 58 11 PM" src="https://user-images.githubusercontent.com/71293113/94181988-31127a00-fe98-11ea-9129-a6c3bfb3c05b.png">
<img width="636" alt="Screenshot 2020-09-24 at 6 58 24 PM" src="https://user-images.githubusercontent.com/71293113/94182006-366fc480-fe98-11ea-9c8b-918a0d1ee922.png">

2020-09-24 19:20 UTC, adaugochi requested changes
I think you are required to just use two images for this task

Also, you are meant to show the view on your browser, not your git commands

2020-09-24 19:42 UTC, ayotola-t commented
> I think you are required to just use two images for this task
> 
> Also, you are meant to show the view on your browser, not your git commands

There was no specification as to the number of images in the task. I'm adding a screenshot of the instructions. 
![IMG_7306](https://user-images.githubusercontent.com/71293113/94191949-2d85ef80-fea6-11ea-87db-fb93234813ae.PNG)

Here are screenshots of the browser view:

<img width="1278" alt="Screenshot 2020-09-24 at 8 41 21 PM" src="https://user-images.githubusercontent.com/71293113/94192156-75a51200-fea6-11ea-8fb9-99e0d3fa57a0.png">
<img width="1256" alt="Screenshot 2020-09-24 at 8 41 34 PM" src="https://user-images.githubusercontent.com/71293113/94192171-7a69c600-fea6-11ea-98ab-6fecc4b46425.png">
![Uploading Screenshot 2020-09-24 at 8.41.27 PM.png…]()

2020-09-24 19:43 UTC, ayotola-t commented
<img width="1271" alt="Screenshot 2020-09-24 at 8 41 57 PM" src="https://user-images.githubusercontent.com/71293113/94192194-835a9780-fea6-11ea-8184-e48395fc9ba3.png">

2020-09-26 17:03 UTC, adaugochi reviewed
Well done

But, you are expected to use just two images for this task, Do ensure to follow the instructions given

2020-09-26 17:03 UTC, adaugochi commented
This information should guide you

> Say for instance a Mentor comment of your PR, how do I go about it? How will the update be reflected on the Pull Request I already created? Below is a step to follow:

- Still, on that same branch, update your changes.

- Add your changes (git add .).

- Commit your changes (git commit  -m  "commit message").

- Finally, Push your change (git push origin branch_name)

2020-09-26 19:14 UTC, ayotola-t commented
> Well done
> 
> But, you are expected to use just two images for this task, Do ensure to follow the instructions given

Hello, 

I have updated to two images. 

But I'm honestly still a bit confused. Please where were we asked to use just two images for the task (I attached a screenshot previously)? I have re-read again and again.  I feel like there is something I'm missing or I'm not interpreting tasks correctly.

2020-09-28 08:52 UTC, ToluAkin requested changes
@ayotola-t Apologies for the confusion on the number of images to use, it was suppose to be added to the success criteria but it was omitted. You are meant to use 2 product images.
Feedback on Pull request
- I think your image names should be in lowercase with no spaces in between.
- You should remove the images you are not using.
- Always create a new branch for every new task

2020-09-28 08:52 UTC, ToluAkin commented on submissions/ayotolaTehingbola/html/product.html
> +    <footer>
The footer should be in the body tag @ayotola-t

2020-09-28 16:17 UTC, closed without merging