[40] Calculate Product Shipping Cost
Dufuna-CodeCamp/Dufuna-CodeCamp20 pull request #617
Opened 2020-09-25 16:51 UTC by Jeffbuchi

Calculating shipping cost on products.

2020-09-28 09:26 UTC, ToluAkin requested changes
@Jeffbuchi You have index.html as your product page and you have product.cs already in your css folder. You need to remove the files from the pull request because they are not needed and not part of the success criteria for this task.

2020-09-29 15:30 UTC, adaugochi requested changes

2020-09-29 15:30 UTC, adaugochi commented on submissions/jeffersonMormah/domManipulation/prod.js
> +const calcShipping = (e) => {
This function doesn't calculate shipping, the function name is confusing

2020-10-01 11:00 UTC, adaugochi approved these changes

2020-10-01 11:00 UTC, merged