[45] Product Page using HTML
Dufuna-CodeCamp/Dufuna-CodeCamp20 pull request #624
Opened 2020-09-26 21:57 UTC by Tocyn

html
- `Changes you made to given task`
![Screen Shot 2020-09-26 at 10 55 53 PM](https://user-images.githubusercontent.com/70757475/94350936-880c8080-004b-11eb-9755-ad73e03b44ea.png)

2020-09-28 09:00 UTC, ToluAkin requested changes

2020-09-28 09:00 UTC, ToluAkin commented on submissions/oluwatosinOke/html/tosin.html
> +</body>
You need to close `html` after the body tag @Tocyn

2020-09-28 09:06 UTC, ToluAkin requested changes

2020-09-28 09:06 UTC, ToluAkin commented on submissions/oluwatosinOke/html/tosin.html
> +<ol>
You did not close this tag @Tocyn

2020-09-28 09:06 UTC, ToluAkin commented on submissions/oluwatosinOke/html/tosin.html
> +    </Ol>
This tag should be in lowercase @Tocyn

2020-09-28 09:24 UTC, Tocyn commented
Hi,
Am I supposed to re submit


On Mon, 28 Sep 2020, 10:06 am ToluAkin, <notifications@github.com> wrote:

> *@ToluAkin* requested changes on this pull request.
> ------------------------------
>
> In submissions/oluwatosinOke/html/tosin.html
> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp20/pull/624#discussion_r495793028>
> :
>
> > +        <ul>
> +            <li> Samsung A20 </li>
> +        </ul>
> +    </div>
> +</nav>
> +
> +<body>
> +    <img src ="./images/ssa201.jpeg"> </img>
> +</body>
> +
> +<p>
> +    &#x20A6;75,000
> +</p>
> +<p> <strong> Product Description:</strong> </p>
> +<p>
> +<ol>
>
> You did not close this tag @Tocyn <https://github.com/Tocyn>
> ------------------------------
>
> In submissions/oluwatosinOke/html/tosin.html
> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp20/pull/624#discussion_r495793395>
> :
>
> > +</p>
> +<p> <strong> Product Description:</strong> </p>
> +<p>
> +<ol>
> +    <li> Display:6.4-inch display </li>
> +    <li> Storage:32GB </li>
> +    <li> RAM:4GB </li>
> +    <li> Camera: Front and Rear </li>
> +    </p>
> +    <p> <strong> Similar Product from seller: </strong> </p>
> +    <p>
> +    <ol>
> +        <li> Samsung A21 </li>
> +        <li> Samsung A10s </li>
> +        <li> Samsung A51 </li>
> +    </Ol>
>
> This tag should be in lowercase @Tocyn <https://github.com/Tocyn>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp20/pull/624#pullrequestreview-497320735>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQ32YY5QDMGMWGVHGHOQRMLSIBGZ3ANCNFSM4R3ESONA>
> .
>

2020-09-28 09:45 UTC, ToluAkin commented
@Tocyn you will make the necessary changes on the same branch. Commit the changes and push your changes.

2020-09-29 09:29 UTC, adaugochi reviewed
You are meant to use 2 images for this task as part of the success criteria

2020-09-29 09:58 UTC, Tocyn commented
Done.

On Tue, 29 Sep 2020, 10:29 am Maryfaith Mgbede, <notifications@github.com>
wrote:

> *@adaugochi* commented on this pull request.
>
> You are meant to use 2 images for this task as part of the success criteria
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp20/pull/624#pullrequestreview-498281863>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQ32YY34I5SSPHFH3QUD7LLSIGSG7ANCNFSM4R3ESONA>
> .
>

2020-09-29 10:12 UTC, adaugochi reviewed
Give a more descriptive and short name for these images

2020-09-29 10:13 UTC, adaugochi commented
ssa201 doesn't mean anything to me

2020-09-29 10:32 UTC, Tocyn commented
Do you mean I should rename the images??

On Tue, 29 Sep 2020, 11:13 am Maryfaith Mgbede, <notifications@github.com>
wrote:

> ssa201 doesn't mean anything to me
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp20/pull/624#issuecomment-700607186>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQ32YY4YYLTWUTJYGXNF3RTSIGXNFANCNFSM4R3ESONA>
> .
>

2020-09-29 10:38 UTC, Tocyn commented
I have renamed the images.
Thanks

On Tue, 29 Sep 2020, 11:32 am OKE OLUWATOSIN, <okegtosin@gmail.com> wrote:

> Do you mean I should rename the images??
>
> On Tue, 29 Sep 2020, 11:13 am Maryfaith Mgbede, <notifications@github.com>
> wrote:
>
>> ssa201 doesn't mean anything to me
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp20/pull/624#issuecomment-700607186>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/AQ32YY4YYLTWUTJYGXNF3RTSIGXNFANCNFSM4R3ESONA>
>> .
>>
>

2020-10-01 10:32 UTC, Tocyn commented
Kindly review my PR

On Tue, 29 Sep 2020, 11:37 am OKE OLUWATOSIN, <okegtosin@gmail.com> wrote:

> I have renamed the images.
> Thanks
>
> On Tue, 29 Sep 2020, 11:32 am OKE OLUWATOSIN, <okegtosin@gmail.com> wrote:
>
>> Do you mean I should rename the images??
>>
>> On Tue, 29 Sep 2020, 11:13 am Maryfaith Mgbede, <notifications@github.com>
>> wrote:
>>
>>> ssa201 doesn't mean anything to me
>>>
>>> —
>>> You are receiving this because you were mentioned.
>>> Reply to this email directly, view it on GitHub
>>> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp20/pull/624#issuecomment-700607186>,
>>> or unsubscribe
>>> <https://github.com/notifications/unsubscribe-auth/AQ32YY4YYLTWUTJYGXNF3RTSIGXNFANCNFSM4R3ESONA>
>>> .
>>>
>>

2020-10-02 08:36 UTC, adaugochi requested changes
You still have a comment on your PR

2020-10-02 09:01 UTC, Tocyn commented
Please can you tell me which of the comment, because I have attended to all
comments to the best of my understanding.

Thanks

On Fri, 2 Oct 2020, 9:37 am Maryfaith Mgbede, <notifications@github.com>
wrote:

> *@adaugochi* requested changes on this pull request.
>
> You still have a comment on your PR
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp20/pull/624#pullrequestreview-500954248>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQ32YY3HHEVZNLBMZDLDMB3SIWGLJANCNFSM4R3ESONA>
> .
>

2020-10-02 09:33 UTC, adaugochi commented
Can you check the `File changes` tab

2020-10-02 09:44 UTC, Tocyn commented
Thanks Maryfaith.
I don't know the file changes you are referring to.
Do you want me to remove all spaces from the code?
Thanks again

On Fri, 2 Oct 2020, 10:33 am Maryfaith Mgbede, <notifications@github.com>
wrote:

> Can you check the File changes tab
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp20/pull/624#issuecomment-702627356>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQ32YY5MIH2ZW2K4BFRWEJTSIWM7VANCNFSM4R3ESONA>
> .
>

2020-10-02 10:15 UTC, ToluAkin requested changes

2020-10-02 10:15 UTC, ToluAkin commented on submissions/oluwatosinOke/html/tosin.html
> +        <li>6.4" LCD display</li>
There is no parent `<ul>` for this `<li>` @Tocyn

2020-10-02 10:15 UTC, ToluAkin commented on submissions/oluwatosinOke/html/tosin.html
> +        <img src ="./images/samsungA20frontview.jpeg"> </img>
@Tocyn `img` tag is self-closing. There is no need for `</img>`

2020-10-02 10:15 UTC, ToluAkin commented on submissions/oluwatosinOke/html/tosin.html
> +     <ul>
You are not using this `<ul>` @Tocyn . You should remove it.

2020-10-02 10:33 UTC, Tocyn commented
Thanks @ToluAkin.
I have effected the changes.

On Fri, 2 Oct 2020, 11:15 am ToluAkin, <notifications@github.com> wrote:

> *@ToluAkin* requested changes on this pull request.
> ------------------------------
>
> In submissions/oluwatosinOke/html/tosin.html
> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp20/pull/624#discussion_r498734873>
> :
>
> > +    <meta charset="UTF-8">
> +    <title> E COMMERCE </title>
> +</head>
> +<header>
> +    <h1> MY FAVOURITE ONLINE STORE </h1>
> +</header>
> +<nav>
> +     <ul>
> +          Samsung A20
> +         <strong> &#x20A6;75,000</strong>
> +    </ul>
> +</nav>
> +<body>
> +    <p>
> +        <img src ="./images/samsungA20frontview.jpeg"> </img>
> +        <li>6.4" LCD display</li>
>
> There is no parent <ul> for this <li> @Tocyn <https://github.com/Tocyn>
> ------------------------------
>
> In submissions/oluwatosinOke/html/tosin.html
> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp20/pull/624#discussion_r498735529>
> :
>
> > +<head>
> +    <meta charset="UTF-8">
> +    <title> E COMMERCE </title>
> +</head>
> +<header>
> +    <h1> MY FAVOURITE ONLINE STORE </h1>
> +</header>
> +<nav>
> +     <ul>
> +          Samsung A20
> +         <strong> &#x20A6;75,000</strong>
> +    </ul>
> +</nav>
> +<body>
> +    <p>
> +        <img src ="./images/samsungA20frontview.jpeg"> </img>
>
> @Tocyn <https://github.com/Tocyn> img tag is self-closing. There is no
> need for </img>
> ------------------------------
>
> In submissions/oluwatosinOke/html/tosin.html
> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp20/pull/624#discussion_r498735899>
> :
>
> > @@ -0,0 +1,43 @@
> +<!DOCTYPE html>
> +<html>
> +<head>
> +    <meta charset="UTF-8">
> +    <title> E COMMERCE </title>
> +</head>
> +<header>
> +    <h1> MY FAVOURITE ONLINE STORE </h1>
> +</header>
> +<nav>
> +     <ul>
>
> You are not using this <ul> @Tocyn <https://github.com/Tocyn> . You
> should remove it.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp20/pull/624#pullrequestreview-501015680>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQ32YY26H6QC3SY6OPRSPHDSIWR5BANCNFSM4R3ESONA>
> .
>

2020-10-02 10:36 UTC, ToluAkin requested changes

2020-10-02 10:36 UTC, ToluAkin commented on submissions/oluwatosinOke/html/tosin.html
> +<header>
@Tocyn header and nav tag should be inside the body tag

2020-10-02 10:36 UTC, ToluAkin commented on submissions/oluwatosinOke/html/tosin.html
> +<ol>
@Tocyn This has not been fixed

2020-10-02 10:52 UTC, Tocyn commented
Thanks ToluAkin, I don't understand what you mean by parent <ul>.

On Fri, 2 Oct 2020, 11:37 am ToluAkin, <notifications@github.com> wrote:

> *@ToluAkin* requested changes on this pull request.
> ------------------------------
>
> In submissions/oluwatosinOke/html/tosin.html
> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp20/pull/624#discussion_r498745027>
> :
>
> > @@ -0,0 +1,43 @@
> +<!DOCTYPE html>
> +<html>
> +<head>
> +    <meta charset="UTF-8">
> +    <title> E COMMERCE </title>
> +</head>
> +<header>
>
> @Tocyn <https://github.com/Tocyn> header and nav tag should be inside the
> body tag
> ------------------------------
>
> In submissions/oluwatosinOke/html/tosin.html
> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp20/pull/624#discussion_r498745123>
> :
>
> > +        <ul>
> +            <li> Samsung A20 </li>
> +        </ul>
> +    </div>
> +</nav>
> +
> +<body>
> +    <img src ="./images/ssa201.jpeg"> </img>
> +</body>
> +
> +<p>
> +    &#x20A6;75,000
> +</p>
> +<p> <strong> Product Description:</strong> </p>
> +<p>
> +<ol>
>
> @Tocyn <https://github.com/Tocyn> This has not been fixed
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp20/pull/624#pullrequestreview-501028771>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQ32YY5DBIIHUZJXELXND3TSIWUM5ANCNFSM4R3ESONA>
> .
>

2020-10-02 10:57 UTC, ToluAkin commented on submissions/oluwatosinOke/html/tosin.html
> +        <li>6.4" LCD display</li>
@Tocyn there should be a `ul` or `ol` tag as parent before using a `li`

2020-10-02 11:06 UTC, Tocyn commented
Thank you ToluAkin, I have effected the said changes.


On Fri, 2 Oct 2020, 11:57 am ToluAkin, <notifications@github.com> wrote:

> *@ToluAkin* commented on this pull request.
> ------------------------------
>
> In submissions/oluwatosinOke/html/tosin.html
> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp20/pull/624#discussion_r498753562>
> :
>
> > +    <meta charset="UTF-8">
> +    <title> E COMMERCE </title>
> +</head>
> +<header>
> +    <h1> MY FAVOURITE ONLINE STORE </h1>
> +</header>
> +<nav>
> +     <ul>
> +          Samsung A20
> +         <strong> &#x20A6;75,000</strong>
> +    </ul>
> +</nav>
> +<body>
> +    <p>
> +        <img src ="./images/samsungA20frontview.jpeg"> </img>
> +        <li>6.4" LCD display</li>
>
> @Tocyn <https://github.com/Tocyn> there should be a ul or ol tag as
> parent before using a li
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp20/pull/624#discussion_r498753562>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQ32YY6PIT42L2G6CRA7NUTSIWWZ7ANCNFSM4R3ESONA>
> .
>

2020-10-02 11:14 UTC, ToluAkin requested changes

2020-10-02 11:14 UTC, ToluAkin commented on submissions/oluwatosinOke/html/tosin.html
> +<p>
@Tocyn Remove this paragraph tag it is not needed

2020-10-02 11:14 UTC, ToluAkin commented on submissions/oluwatosinOke/html/tosin.html
> +<p>
@Tocyn Remove this paragraph tag it is not needed

2020-10-02 11:14 UTC, ToluAkin commented on submissions/oluwatosinOke/html/tosin.html
> +   <p>
@Tocyn Remove this paragraph tag it is not needed

2020-10-02 11:14 UTC, ToluAkin commented on submissions/oluwatosinOke/html/tosin.html
> +    <p>
@Tocyn Remove this paragraph tag it is not needed

2020-10-02 11:44 UTC, Tocyn commented
Thank you @ToluAkin. I have removed the said tags.

On Fri, 2 Oct 2020, 12:14 pm ToluAkin, <notifications@github.com> wrote:

> *@ToluAkin* requested changes on this pull request.
> ------------------------------
>
> In submissions/oluwatosinOke/html/tosin.html
> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp20/pull/624#discussion_r498759607>
> :
>
> > +    <img src ="./images/samsungA20backview.jpeg">
> +        <ul>
> +            <li>Backview with dual 13mp Camera and fingerprint scanner</li>
> +        </ul>
> +   </p>
> +<p> <strong> Product Description:</strong> </p>
> +<p>
> +    <ol>
> +        <li> Display:6.4-inch display </li>
> +        <li> Storage:32GB </li>
> +        <li> RAM:4GB </li>
> +        <li> Camera: Front and Rear </li>
> +    </ol>
> +</p>
> +    <p> <strong> Similar Product from seller: </strong> </p>
> +<p>
>
> @Tocyn <https://github.com/Tocyn> Remove this paragraph tag it is not
> needed
> ------------------------------
>
> In submissions/oluwatosinOke/html/tosin.html
> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp20/pull/624#discussion_r498759689>
> :
>
> > +         <strong> &#x20A6;75,000</strong>
> +</nav>
> +    <p>
> +        <img src ="./images/samsungA20frontview.jpeg">
> +        <ul>
> +            <li>6.4" LCD display</li>
> +        </ul>
> +    </p>
> +   <p>
> +    <img src ="./images/samsungA20backview.jpeg">
> +        <ul>
> +            <li>Backview with dual 13mp Camera and fingerprint scanner</li>
> +        </ul>
> +   </p>
> +<p> <strong> Product Description:</strong> </p>
> +<p>
>
> @Tocyn <https://github.com/Tocyn> Remove this paragraph tag it is not
> needed
> ------------------------------
>
> In submissions/oluwatosinOke/html/tosin.html
> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp20/pull/624#discussion_r498759748>
> :
>
> > +</head>
> +<body>
> +<header>
> +    <h1> MY FAVOURITE ONLINE STORE </h1>
> +</header>
> +<nav>
> +          Samsung A20
> +         <strong> &#x20A6;75,000</strong>
> +</nav>
> +    <p>
> +        <img src ="./images/samsungA20frontview.jpeg">
> +        <ul>
> +            <li>6.4" LCD display</li>
> +        </ul>
> +    </p>
> +   <p>
>
> @Tocyn <https://github.com/Tocyn> Remove this paragraph tag it is not
> needed
> ------------------------------
>
> In submissions/oluwatosinOke/html/tosin.html
> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp20/pull/624#discussion_r498759777>
> :
>
> > @@ -0,0 +1,46 @@
> +<!DOCTYPE html>
> +<html>
> +<head>
> +    <meta charset="UTF-8">
> +    <title> E COMMERCE </title>
> +</head>
> +<body>
> +<header>
> +    <h1> MY FAVOURITE ONLINE STORE </h1>
> +</header>
> +<nav>
> +          Samsung A20
> +         <strong> &#x20A6;75,000</strong>
> +</nav>
> +    <p>
>
> @Tocyn <https://github.com/Tocyn> Remove this paragraph tag it is not
> needed
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp20/pull/624#pullrequestreview-501048937>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQ32YY2ZMPHIWKKHNMTZRITSIWYYRANCNFSM4R3ESONA>
> .
>

2020-10-02 11:45 UTC, ToluAkin approved these changes

2020-10-02 11:46 UTC, merged

2020-10-02 12:01 UTC, Tocyn commented
Thank you for your tima and patience.

Warm Regards.

On Fri, 2 Oct 2020, 12:46 pm ToluAkin, <notifications@github.com> wrote:

> Merged #624
> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp20/pull/624> into
> master.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp20/pull/624#event-3833611633>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQ32YY3F6XMXNBZMFAEWZZLSIW4QPANCNFSM4R3ESONA>
> .
>