[45] product Page Using HTML
Dufuna-CodeCamp/Dufuna-CodeCamp20 pull request #629
Opened 2020-09-28 08:07 UTC by Moronke02

## Task: `Develop  a product page for your e-commerce store using HTML only`
- `Added HTML folder`
-Link to implementation screenshots:
 https://drive.google.com/drive/folders/1P7JaWxvvj2fW4ymBTuyMSqs3ufECf8rv?usp=sharing

2020-09-28 09:17 UTC, ToluAkin requested changes
@Moronke02 Your index.html should also be the product page. You need to remove the index file. 
You are meant to only write html no styling, you need to remove all styling in the product page alongside the sizing of the images. 
You also need to remove all images that you are not using from the asset folder.

2020-09-28 13:13 UTC, Moronke02 commented
> @Moronke02 Your index.html should also be the product page. You need to remove the index file.
> You are meant to only write html no styling, you need to remove all styling in the product page alongside the sizing of the images.
> You also need to remove all images that you are not using from the asset folder.

@ToluAkin Thanks for the feedback. Changes effected.

2020-09-28 14:04 UTC, ToluAkin commented
@Moronke02 you are meant to upload the screenshot of the webpage on the pull request.

2020-09-28 14:09 UTC, ToluAkin commented
@Moronke02 You should have your image names in lowercase with no spaces between them. You are also meant to work with two product images

2020-09-28 14:17 UTC, Moronke02 commented
> @Moronke02 you are meant to upload the screenshot of the webpage on the pull request.

@ToluAkin It was stated that we can add the link to the screenshot although if that is most expected I think I will just do that

2020-09-28 14:19 UTC, Moronke02 commented
> @Moronke02 You should have your image names in lowercase with no spaces between them. You are also meant to work with two product images

@ToluAkin Thanks for the feedback, I will correct them as you said . But for the product images, it was not stated although I will also eliminate the redundant ones.Thanks

2020-09-28 14:51 UTC, Moronke02 commented
Implementation Screenshots
![Screenshot (315)](https://user-images.githubusercontent.com/45916239/94448116-75588f80-01a2-11eb-957c-ea9812d2521a.png)
![Screenshot (316)](https://user-images.githubusercontent.com/45916239/94448122-77225300-01a2-11eb-95c3-2b4a56742150.png)

2020-09-28 16:19 UTC, adaugochi requested changes

2020-09-28 16:19 UTC, adaugochi commented on submissions/moronkeAliu/HTML/index.html
> +    <footer>
Footer tag should be inside your <body> tag

2020-09-29 09:27 UTC, adaugochi approved these changes

2020-09-29 09:27 UTC, merged