[45] Product Page using HTML
Dufuna-CodeCamp/Dufuna-CodeCamp20 pull request #648
Opened 2020-09-30 03:00 UTC by bilkisutace

## Task: `[45] Product Page using HTML`
- `Created a Product Page
![screenshot1](https://user-images.githubusercontent.com/69322971/94638212-67555c80-02d1-11eb-8ee0-ba61d9fefd3e.JPG)
![screenshot2](https://user-images.githubusercontent.com/69322971/94638222-6b817a00-02d1-11eb-98f7-03f36b2cdff4.JPG)
![screenshot3](https://user-images.githubusercontent.com/69322971/94638226-6d4b3d80-02d1-11eb-870a-8d09b992c2bf.JPG)
![screenshot4](https://user-images.githubusercontent.com/69322971/94638227-6f150100-02d1-11eb-9310-f9d429fa6b8a.JPG)

`

2020-09-30 09:02 UTC, ToluAkin requested changes
@bilkisutace You are required to use 2 product images for this task.
You need to delete the images that you are not using.
Your image names should be in lowercase, no spaces in between.
You need to link your images using relative path. Check [here](https://www.w3schools.com/Html/html_filepaths.asp) for how to do that.
Remove all height and width from the images. You will get to style your page when your course study gets to CSS.

2020-09-30 09:02 UTC, ToluAkin commented on submissions/bilkisuTace/HTML/product.html
> +	<table width=50%>
Remove the width here @bilkisutace

2020-09-30 14:46 UTC, adaugochi requested changes

2020-09-30 14:46 UTC, adaugochi commented on submissions/bilkisuTace/HTML/product.html
> +	<header>
<header> tag is meant to be inside the <body> tag. Because it is called header doesn't mean it should be in the <head> tag

2020-10-01 10:58 UTC, adaugochi approved these changes

2020-10-01 10:59 UTC, merged