[54] Add Page Navigation to your Pages
Dufuna-CodeCamp/Dufuna-CodeCamp20 pull request #651
Opened 2020-09-30 10:50 UTC by kojusola

## Task: `Uploaded signup page and included page navigation to all pages`
- ` created a signup page using only html and included page navigation to all pages, the screenshots of implementation can be found below:`
![ContactUsNavigation0](https://user-images.githubusercontent.com/66546900/94676213-e28b3280-0312-11eb-9bc8-75a7bffec790.jpg)
![Productpagenavigation0](https://user-images.githubusercontent.com/66546900/94676232-e9b24080-0312-11eb-8bc9-a5077ba808bd.jpg)
![productpagenavigation1](https://user-images.githubusercontent.com/66546900/94676246-f0d94e80-0312-11eb-98e6-2a0e2e26f42f.jpg)
![Signuppagenavigation0](https://user-images.githubusercontent.com/66546900/94676272-fb93e380-0312-11eb-99bb-7299a8abaa6d.jpg)
![signuppagenavigation1](https://user-images.githubusercontent.com/66546900/94676297-051d4b80-0313-11eb-8529-e25e1edeabb9.jpg)

2020-09-30 10:59 UTC, kojusola commented
Removed the signup form page from the html forms folder.
Sorry for any inconveniences.

2020-10-02 08:35 UTC, adaugochi requested changes
You don't have signup.html file, Why are you linking it here? Please remove it

2020-10-02 14:50 UTC, kojusola commented
Removed the sign-up page links.
Thanks.

2020-10-03 17:18 UTC, adaugochi requested changes

2020-10-03 17:18 UTC, adaugochi commented on submissions/adeolaFafemi/html-forms/contactUs.html
> +                    <li><a href="../html-forms/contactUs.html">Contact Us</a></li>
I think just `contactUs.html` should work here

2020-10-03 17:18 UTC, adaugochi commented on submissions/adeolaFafemi/HTML/index.html
> +                    <li><a href="../HTML/index.html">Product Page</a></li>
just `index.html` should work here

2020-10-03 18:18 UTC, kojusola commented
changed the navigation link.
thank you

2020-10-04 19:48 UTC, adaugochi approved these changes

2020-10-04 19:49 UTC, merged