[51] Develop a Contact Form using HTML
Dufuna-CodeCamp/Dufuna-CodeCamp20 pull request #703
Opened 2020-10-06 17:14 UTC by bilkisutace

## Task: `[51] Develop a Contact Form using HTML`
- `Created a contact form page
![contactformpage](https://user-images.githubusercontent.com/69322971/95236958-82f3c200-07ff-11eb-9e64-b07193215192.jpg)
`

2020-10-06 17:28 UTC, emmanuelidiaghe requested changes
Hello @bilkisuTace,

You didn’t properly attach the screenshot.
Ensure the attachment begins on a new line

2020-10-06 21:50 UTC, emmanuelidiaghe approved these changes

2020-10-07 08:34 UTC, ToluAkin requested changes

2020-10-07 08:34 UTC, ToluAkin commented on submissions/bilkisuTace/HTML/product.html
> +			<li><a href="../html-forms/contact.html"><h3>Contact Page</h3></a></li>
There is an oncoming task to link your pages. You should remove this for now @bilkisutace

2020-10-07 08:34 UTC, ToluAkin commented on submissions/bilkisuTace/html-forms/contact.html
> +
There are too many extra spaces in this file. I think you should remove them for readability @bilkisutace

2020-10-07 09:21 UTC, ToluAkin approved these changes

2020-10-07 09:22 UTC, merged