[51] Develop a Contact Form Page using HTML
Dufuna-CodeCamp/Dufuna-CodeCamp20 pull request #709
Opened 2020-10-07 09:46 UTC by EseAlli

Develop a Contact Form Page using HTML
Created a contact form page

2020-10-07 11:20 UTC, emmanuelidiaghe requested changes
Hello @Ese,

Good job on your PR!
Please attach a screenshot of the implementation.

2020-10-07 11:29 UTC, emmanuelidiaghe requested changes

2020-10-07 11:29 UTC, emmanuelidiaghe commented on submissions/alliEse/html-forms/contact.html
> +                <li><a href="#"> Home</a></li>
Please remove the href attribute and its value from all a-tags in the nav. The linking will be done in subsequent tasks.

2020-10-07 13:08 UTC, adaugochi requested changes

2020-10-07 13:08 UTC, adaugochi commented on submissions/alliEse/HTML/index.html
> +				<li><a href="../html-forms/contact.html">Contact Us</a> </li>
Well done @EseAlli 

Linking of pages will be done in your next task. You can remove them for now

2020-10-07 13:08 UTC, adaugochi commented on submissions/alliEse/html-forms/contact.html
> +                <li><a href="../HTML/index.html">Product</a> </li>
Same here too

2020-10-07 13:58 UTC, ToluAkin requested changes

2020-10-07 13:58 UTC, ToluAkin commented on submissions/alliEse/html-forms/contact.html
> +	<p> Find us here:
The p tag should close on this line as well @EseAlli

2020-10-09 10:34 UTC, EseAlli commented
![image](https://user-images.githubusercontent.com/29662060/95573410-4f917d00-0a23-11eb-8618-9b49c8d718f1.png)

2020-10-09 15:41 UTC, merged