[51] Develop a Contact Form Page using HTML
Dufuna-CodeCamp/Dufuna-CodeCamp20 pull request #714
Opened 2020-10-07 19:21 UTC by Tocyn

Task: `HTML FORMS`

![Screen Shot 2020-10-07 at 8 17 58 PM](https://user-images.githubusercontent.com/70757475/95377352-59f42f80-08da-11eb-82d1-8a05627c67a6.png)

2020-10-08 09:18 UTC, adaugochi requested changes

2020-10-08 09:18 UTC, adaugochi commented on submissions/oluwatosinOke/html-forms/contactform.html
> +<html>
No `<head>` and `<body>` tags

2020-10-08 17:30 UTC, Tocyn commented
Thank you @adaugochi.
I have added the tags.

On Thu, 8 Oct 2020, 10:18 am Maryfaith Mgbede, <notifications@github.com>
wrote:

> *@adaugochi* requested changes on this pull request.
> ------------------------------
>
> In submissions/oluwatosinOke/html-forms/contactform.html
> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp20/pull/714#discussion_r501570428>
> :
>
> > @@ -0,0 +1,24 @@
> +<!DOCTYPE html>
> +<html>
>
> No <head> and <body> tags
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp20/pull/714#pullrequestreview-504585921>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQ32YY7LXNMPHGDHWTMQHLDSJV7V3ANCNFSM4SHZXTMQ>
> .
>

2020-10-09 10:00 UTC, adaugochi requested changes

2020-10-09 10:00 UTC, adaugochi commented on submissions/oluwatosinOke/html-forms/contactform.html
> +     <h1> Contact Form </h1>
`<h1>` and `<form>` tags are not tags that can be found on the `<head>` section. Tags placed inside the `<head>` tag are `<meta>, <link>, <title>, <script>`. So, kindly correct yourself

2020-10-09 19:45 UTC, Tocyn commented
Thank you @adaugochi, I have made the required changes.

Warm Regards.

On Fri, 9 Oct 2020, 11:00 am Maryfaith Mgbede, <notifications@github.com>
wrote:

> *@adaugochi* requested changes on this pull request.
> ------------------------------
>
> In submissions/oluwatosinOke/html-forms/contactform.html
> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp20/pull/714#discussion_r502321900>
> :
>
> > @@ -0,0 +1,28 @@
> +<!DOCTYPE html>
> +<html>
> +    <head>
> +     <h1> Contact Form </h1>
>
> <h1> and <form> tags are not tags that can be found on the <head>
> section. Tags placed inside the <head> tag are <meta>, <link>, <title>,
> <script>. So, kindly correct yourself
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp20/pull/714#pullrequestreview-505532457>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQ32YY3XZOLWLWOOGHLXW5TSJ3NNBANCNFSM4SHZXTMQ>
> .
>

2020-10-11 14:28 UTC, adaugochi requested changes
I am still not seeing `<head>` and `<body>` tags

2020-10-11 14:43 UTC, Tocyn commented
@adaugochi, I followed the slide example so I am confused on the head and
body tags you are referring to.

On Sun, 11 Oct 2020, 3:29 pm Maryfaith Mgbede, <notifications@github.com>
wrote:

> *@adaugochi* requested changes on this pull request.
>
> I am still not seeing <head> and <body> tags
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp20/pull/714#pullrequestreview-506184761>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQ32YYYQI32V3RUPQTL6CLDSKG6LNANCNFSM4SHZXTMQ>
> .
>

2020-10-11 15:09 UTC, Tocyn commented
@adaugochi, I have effected some changes. Kindly review.

On Sun, 11 Oct 2020, 3:43 pm OKE OLUWATOSIN, <okegtosin@gmail.com> wrote:

> @adaugochi, I followed the slide example so I am confused on the head and
> body tags you are referring to.
>
> On Sun, 11 Oct 2020, 3:29 pm Maryfaith Mgbede, <notifications@github.com>
> wrote:
>
>> *@adaugochi* requested changes on this pull request.
>>
>> I am still not seeing <head> and <body> tags
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp20/pull/714#pullrequestreview-506184761>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/AQ32YYYQI32V3RUPQTL6CLDSKG6LNANCNFSM4SHZXTMQ>
>> .
>>
>

2020-10-12 15:05 UTC, Tocyn commented
@ adaugochi, kindly review my PR. Thank you.

On Sun, 11 Oct 2020, 4:09 pm OKE OLUWATOSIN, <okegtosin@gmail.com> wrote:

> @adaugochi, I have effected some changes. Kindly review.
>
> On Sun, 11 Oct 2020, 3:43 pm OKE OLUWATOSIN, <okegtosin@gmail.com> wrote:
>
>> @adaugochi, I followed the slide example so I am confused on the head and
>> body tags you are referring to.
>>
>> On Sun, 11 Oct 2020, 3:29 pm Maryfaith Mgbede, <notifications@github.com>
>> wrote:
>>
>>> *@adaugochi* requested changes on this pull request.
>>>
>>> I am still not seeing <head> and <body> tags
>>>
>>> —
>>> You are receiving this because you authored the thread.
>>> Reply to this email directly, view it on GitHub
>>> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp20/pull/714#pullrequestreview-506184761>,
>>> or unsubscribe
>>> <https://github.com/notifications/unsubscribe-auth/AQ32YYYQI32V3RUPQTL6CLDSKG6LNANCNFSM4SHZXTMQ>
>>> .
>>>
>>

2020-10-12 15:59 UTC, adaugochi requested changes

2020-10-12 15:59 UTC, adaugochi commented on submissions/oluwatosinOke/html-forms/contactform.html
> +    <Form action = "#" method =post>
Your `<form>` tag should be after closing `<head>` tag. Also, it should be all in lowercases

2020-10-12 15:59 UTC, adaugochi commented on submissions/oluwatosinOke/html-forms/contactform.html
> +      <Button type="submit">submit</Button>
tags should be all in lowercases

2020-10-12 18:21 UTC, Tocyn commented
Thanks @adaugochi. I have effected required changes.
Kindly review.

On Mon, 12 Oct 2020, 4:59 pm Maryfaith Mgbede, <notifications@github.com>
wrote:

> *@adaugochi* requested changes on this pull request.
> ------------------------------
>
> In submissions/oluwatosinOke/html-forms/contactform.html
> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp20/pull/714#discussion_r503390261>
> :
>
> > @@ -0,0 +1,27 @@
> +<!DOCTYPE html>
> +<html>
> +    <Form action = "#" method =post>
>
> Your <form> tag should be after closing <head> tag. Also, it should be
> all in lowercases
> ------------------------------
>
> In submissions/oluwatosinOke/html-forms/contactform.html
> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp20/pull/714#discussion_r503390479>
> :
>
> > +      <input type="text" name= "firstname" id = "firstname"> <br>
> +
> +      <label for= "last name">Last name</Label><br>
> +      <input type="text" name= "lastname" id = "lastname"> <br>
> +
> +      <label for="email">Email</label><br>
> +      <input type="email" name="email" id="email" placeholder="enter your email address"><br>
> +
> +      <label for= "subject">Subject</Label><br>
> +      <input type="text" name= "subject" id = "subject"> <br>
> +
> +      <label for="comment">Message Input</label><br/>
> +      <textarea name="comments" id="comments"rows ="10" cols="30">
> +      </textarea><br>
> +
> +      <Button type="submit">submit</Button>
>
> tags should be all in lowercases
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp20/pull/714#pullrequestreview-506742279>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQ32YY4MV7OTB2FOK5YMDDDSKMRVLANCNFSM4SHZXTMQ>
> .
>

2020-10-13 09:08 UTC, adaugochi requested changes

2020-10-13 09:08 UTC, adaugochi commented on submissions/oluwatosinOke/html-forms/contactform.html
> +    <form action = "#" method =post></form>
This should be inside the `<body>` tag. And there is nothing within your `<form>` tag also, why?

2020-10-14 10:21 UTC, adaugochi requested changes

2020-10-14 10:21 UTC, adaugochi commented on submissions/oluwatosinOke/html-forms/contactform.html
> +      <form action = "#" method =post entype="application/x-www-form-urlencoded"></form>
Your `<form>` tag can not be empty. It should have some nested element within it

2020-10-14 19:09 UTC, Tocyn commented
I have effected the requested changes, kindly review my PR.

On Wed, 14 Oct 2020, 11:21 am Maryfaith Mgbede, <notifications@github.com>
wrote:

> *@adaugochi* requested changes on this pull request.
> ------------------------------
>
> In submissions/oluwatosinOke/html-forms/contactform.html
> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp20/pull/714#discussion_r504565497>
> :
>
> > @@ -0,0 +1,27 @@
> +<!DOCTYPE html>
> +<html>
> +    <head>
> +      <meta> CONTACT FORM <br>
> +    </head>
> +    <body>
> +      <form action = "#" method =post entype="application/x-www-form-urlencoded"></form>
>
> Your <form> tag can not be empty. It should have some nested element
> within it
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp20/pull/714#pullrequestreview-508201639>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQ32YY6T5GT7WFBWFR4U4BLSKV3TNANCNFSM4SHZXTMQ>
> .
>

2020-10-16 06:51 UTC, adaugochi requested changes
You haven't effect the changes yet.

Kindly remove the `contactformdata.html` file

2020-10-16 10:26 UTC, Tocyn commented
I will remove the file link.
 I don't understand the other  changes you want me to effect, I have edited
to the best of my understanding.kindly explain further.

On Fri, 16 Oct 2020, 7:52 am Maryfaith Mgbede, <notifications@github.com>
wrote:

> *@adaugochi* requested changes on this pull request.
>
> You haven't effect the changes yet.
>
> Kindly remove the contactformdata.html file
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp20/pull/714#pullrequestreview-510196883>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQ32YY5CEOES73LNWRKXDNDSK7URJANCNFSM4SHZXTMQ>
> .
>

2020-10-17 05:21 UTC, Tocyn commented
Good morning, kindly review my PR

On Fri, 16 Oct 2020, 11:26 am OKE OLUWATOSIN, <okegtosin@gmail.com> wrote:

> I will remove the file link.
>  I don't understand the other  changes you want me to effect, I have
> edited to the best of my understanding.kindly explain further.
>
> On Fri, 16 Oct 2020, 7:52 am Maryfaith Mgbede, <notifications@github.com>
> wrote:
>
>> *@adaugochi* requested changes on this pull request.
>>
>> You haven't effect the changes yet.
>>
>> Kindly remove the contactformdata.html file
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp20/pull/714#pullrequestreview-510196883>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/AQ32YY5CEOES73LNWRKXDNDSK7URJANCNFSM4SHZXTMQ>
>> .
>>
>

2020-10-17 06:54 UTC, adaugochi requested changes

2020-10-17 06:54 UTC, adaugochi commented on submissions/oluwatosinOke/html-forms/contactform.html
> +      <form action = "#" method =post entype="application/x-www-form-urlencoded">
remove the attributes on this `<form>` tag. There are not necessary yet

2020-10-17 16:42 UTC, Tocyn commented
Attribute removed. Kindly review.

On Sat, 17 Oct 2020, 7:54 am Maryfaith Mgbede, <notifications@github.com>
wrote:

> *@adaugochi* requested changes on this pull request.
> ------------------------------
>
> In submissions/oluwatosinOke/html-forms/contactform.html
> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp20/pull/714#discussion_r506839441>
> :
>
> > @@ -0,0 +1,28 @@
> +<!DOCTYPE html>
> +<html>
> +    <head>
> +      <meta> CONTACT FORM <br>
> +    </head>
> +    <body>
> +      <form action = "#" method =post entype="application/x-www-form-urlencoded">
>
> remove the attributes on this <form> tag. There are not necessary yet
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp20/pull/714#pullrequestreview-510956573>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQ32YY4OQWU3UUKSQ3WBJL3SLE5SVANCNFSM4SHZXTMQ>
> .
>

2020-10-18 07:05 UTC, adaugochi approved these changes

2020-10-18 07:05 UTC, merged