[52] Develop a Contact Form Page using HTML
Dufuna-CodeCamp/Dufuna-CodeCamp20 pull request #723
Opened 2020-10-08 17:03 UTC by gracioust

## Task: `Develop a Contact Form Page using HTML`
- `Developed
![Capturec](https://user-images.githubusercontent.com/18602498/95490765-97b38f80-0990-11eb-97cc-4ff5cc8fd3a0.PNG)
 a Contact Form Page using HTML'

2020-10-08 19:41 UTC, ainobs requested changes

2020-10-08 19:41 UTC, ainobs commented on submissions/tosinIshola/html-forms/contact_form.html
> +<html lang="en"><head>
hello tosin, nice job so far. Please move this head tag down into the next line.

2020-10-09 10:05 UTC, TundeOladejo requested changes

2020-10-09 10:05 UTC, TundeOladejo commented on submissions/tosinIshola/HTML/Ecommerce.html
> +
Remove this extra line

2020-10-10 09:31 UTC, gracioust commented on submissions/tosinIshola/HTML/Ecommerce.html
> +
What extra line?

2020-10-10 15:15 UTC, adaugochi requested changes

2020-10-10 15:15 UTC, adaugochi commented on submissions/tosinIshola/html-forms/contact_form.html
> +<form action="#" method="post" enctype="multipart/form-data">
All this `action="#" method="post" enctype="multipart/form-data"` aren't needed. Can you remove them?

2020-10-11 14:27 UTC, adaugochi approved these changes

2020-10-11 14:27 UTC, merged