[46] Product page using Html
Dufuna-CodeCamp/Dufuna-CodeCamp20 pull request #741
Opened 2020-10-13 22:45 UTC by queensaldam

## Task: `Product page using html`
- `Created a Buy me home page`

2020-10-14 10:10 UTC, adaugochi requested changes
Well done  @queensaldam 

Kindly remove the spaces on your images name. Replace with either `-` or `_`. Also, for this task you are expected to use two images for this task

2020-10-15 20:24 UTC, emmanuelidiaghe commented
Great job!
Your images should be within the “images” folder

2020-10-16 06:50 UTC, adaugochi approved these changes

2020-10-16 06:50 UTC, merged

2020-10-16 06:51 UTC, emmanuelidiaghe requested changes

2020-10-16 06:51 UTC, emmanuelidiaghe commented on submissions/damilolaSalami/html/productpage.html
> +            <img src="images/4face_sandwich_toaster.jpg alt="4face_toaster">
You omitted the closing quotes for the src attribute