[58] Develop an E-commerce Store Database
Dufuna-CodeCamp/Dufuna-CodeCamp20 pull request #749
Opened 2020-10-18 17:22 UTC by faithakinbobola

## Task: Develop an E-commerce Store Database`
- `Developed the database for my E-commerce store`

2020-10-19 12:36 UTC, adaugochi requested changes

2020-10-19 12:36 UTC, adaugochi commented on submissions/akinbobolaFaith/database/init.sql
> +	products_id INT NOT NULL,
kindly read the instructions again thoroughly. you were told `each product belongs to a category` and not `each category belongs to a product`

2020-10-20 10:48 UTC, adaugochi requested changes

2020-10-20 10:48 UTC, adaugochi commented on submissions/akinbobolaFaith/database/init.sql
> +	created_by DATETIME,
I think this should be `created_at`

2020-10-20 10:48 UTC, adaugochi commented on submissions/akinbobolaFaith/database/init.sql
> +INSERT INTO customers (firstname, lastname, email_address, password, created_by)
same here

2020-10-20 10:48 UTC, adaugochi commented on submissions/akinbobolaFaith/database/init.sql
> +	date VARCHAR(50) NOT NULL,
`order_date` is better than just `date`

2020-10-20 11:33 UTC, adaugochi requested changes

2020-10-20 11:33 UTC, adaugochi commented on submissions/akinbobolaFaith/database/init.sql
> +("Skechers Men's Blaine Orsen Ankle Boot", 'Approx. 1'' heel height, Approx. 5'' boot shaft height, Cushioned footbed, Dual side goring Fabric lining', 'https://C:\Users\Dell\Desktop\Dufuna-CodeCamp2
kindly use online image URLs rather than this absolute path you are using

2020-10-22 09:35 UTC, adaugochi requested changes

2020-10-22 09:35 UTC, adaugochi commented on submissions/akinbobolaFaith/css/contactForm.css
> +nav a[href="#"] {
kindly give this a class name. Imagine you now add a link, this styling will be affected and thus you need to update it again. Same goes for others

2020-10-22 11:24 UTC, adaugochi requested changes

2020-10-22 11:24 UTC, adaugochi commented on submissions/akinbobolaFaith/database/init.sql
> +	created_by DATETIME,
You haven't fix this

2020-10-22 11:24 UTC, adaugochi requested changes

2020-10-22 11:24 UTC, adaugochi commented on submissions/akinbobolaFaith/database/init.sql
> +	date VARCHAR(50) NOT NULL,
and this too

2020-10-22 14:08 UTC, adaugochi requested changes
What is this file that is part of your PR 
![image](https://user-images.githubusercontent.com/43061141/96883555-76ff3580-1478-11eb-897c-095eef93ab39.png)

2020-10-22 16:09 UTC, faithakinbobola commented
I don't know. I didn't touch any shortcut file. I don't know how it came about

2020-10-25 00:27 UTC, adaugochi requested changes
We will look into the matter on Monday via call

2020-10-27 08:56 UTC, adaugochi approved these changes

2020-10-27 08:56 UTC, merged