[54] Add Page Navigation to your Pages
Dufuna-CodeCamp/Dufuna-CodeCamp20 pull request #750
Opened 2020-10-18 20:45 UTC by Tocyn

![Screen Shot 2020-10-18 at 9 37 58 PM](https://user-images.githubusercontent.com/70757475/96385292-db757880-118a-11eb-8b1e-04bf8ba35042.png)
![Screen Shot 2020-10-18 at 9 38 42 PM](https://user-images.githubusercontent.com/70757475/96385298-de706900-118a-11eb-80c5-57983fc8bb01.png)

2020-10-19 09:53 UTC, adaugochi requested changes

2020-10-19 09:53 UTC, adaugochi commented on submissions/oluwatosinOke/html-forms/contactform.html
> +              <li><a href="../html/tosin.html">Product Page</a></li>
kindly change this file name from `tosin.html` to something better.

2020-10-19 15:52 UTC, Tocyn commented
File name has been changed. Kindly review.

On Mon, 19 Oct 2020, 10:54 am Maryfaith Mgbede, <notifications@github.com>
wrote:

> *@adaugochi* requested changes on this pull request.
> ------------------------------
>
> In submissions/oluwatosinOke/html-forms/contactform.html
> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp20/pull/750#discussion_r507618389>
> :
>
> > @@ -5,6 +5,9 @@
>      </head>
>      <body>
>        <form>
> +          <ul>
> +              <li><a href="../html/tosin.html">Product Page</a></li>
>
> kindly change this file name from tosin.html to something better.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp20/pull/750#pullrequestreview-511594875>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQ32YY7ZTRQMTW46RWTB3B3SLQED3ANCNFSM4SVKQCSA>
> .
>

2020-10-20 09:43 UTC, adaugochi approved these changes

2020-10-20 09:43 UTC, merged