[65] Create &Style the Customer Signup Page using CSS- Frontend
Dufuna-CodeCamp/Dufuna-CodeCamp20 pull request #757
Opened 2020-10-20 15:57 UTC by gracioust

## Task: `Create &Style the Customer Signup Page using CSS- Frontend`
- `Create &Style the Customer Signup Page using CSS- Frontend`
![signup 1](https://user-images.githubusercontent.com/18602498/96612055-3aef9780-12f5-11eb-998e-8f546fd3b0a7.PNG)
![signup 2](https://user-images.githubusercontent.com/18602498/96612083-40e57880-12f5-11eb-8755-f33e6d80db87.PNG)
![signup 3](https://user-images.githubusercontent.com/18602498/96612112-4a6ee080-12f5-11eb-99d6-36a8651176cf.PNG)
![signup 4](https://user-images.githubusercontent.com/18602498/96612136-50fd5800-12f5-11eb-85c9-51d49f75c82a.PNG)

2020-10-22 09:09 UTC, adaugochi requested changes
Kindly give html elements `class` or `id` names and style them instead of styling their `tag` name. except for cases like `a` tag where you don't want all `a` tag to have `text-decoration`

2020-10-23 08:55 UTC, ToluAkin requested changes

2020-10-23 08:55 UTC, ToluAkin commented on submissions/tosinIshola/HTML/Ecommerce.html
> +    <img src="../HTML/Images/fashion.jpg" alt="logo" style="border: 1px solid #ddd;
@gracioust Move the style here to the external css file

2020-10-23 08:55 UTC, ToluAkin commented on submissions/tosinIshola/html-forms/contact_form.html
> +    <img src="../HTML/Images/fashion.jpg" alt="logo" style="border: 1px solid #ddd;
@gracioust Move the style here to the external css file

2020-10-23 08:55 UTC, ToluAkin commented on submissions/tosinIshola/html-forms/signup.html
> +    <img src="../HTML/Images/fashion.jpg" alt="logo" style="border: 1px solid #ddd;
@gracioust Move the style here to the external css file

2020-11-06 15:41 UTC, closed without merging