[55] Add Page Navigation to your pages
Dufuna-CodeCamp/Dufuna-CodeCamp20 pull request #770
Opened 2020-10-23 22:14 UTC by queensaldam

## Task: `Added navigation to the pages`
- `Navigation to product & contact page was added

2020-10-25 00:34 UTC, adaugochi requested changes

2020-10-25 00:34 UTC, adaugochi commented on submissions/damilolaSalami/html/productpage.html
> +                <li><a href="../html/productpage.html"></a>Product page</li>
simply do `href="productpage.html"`. Also, what about your contact form page? Are you not linking pages on that too?

2020-10-26 10:43 UTC, adaugochi requested changes

2020-10-26 10:43 UTC, adaugochi commented on submissions/damilolaSalami/html/contact.html
> +<!DOCTYPE html>
This should be inside `html-forms` and should have been done prior to now

2020-10-26 10:43 UTC, adaugochi commented on submissions/damilolaSalami/html/contact.html
> +                <li><a href="productpage.html">Product Page</a></li>
You are only expected to add navigation links to tat already created page

2020-10-27 09:03 UTC, adaugochi requested changes

2020-10-27 09:03 UTC, adaugochi commented on submissions/damilolaSalami/html/productpage.html
> +                <li><a href="contact.html">Contact us</a></li>
Does this link work?

2020-10-27 09:05 UTC, adaugochi commented
I checked your work and I noticed you haven't created contact form page before

You ought to do that before doing this task.

2020-10-27 09:44 UTC, queensaldam commented
> I checked your work and I noticed you haven't created contact form page before
> 
> You ought to do that before doing this task.

Thank you. I'm sorry for all the troubles.
Please am I to create a PR branch on html form containing contact page first? Then update html branch with the navigation page?

2020-10-27 16:07 UTC, ToluAkin commented
@queensaldam In this case, you can have **2 PRs that will not conflict.** You can create a new pull request with the task_id for the contact form only. If you have any issues, you can reach out. Remember, you create a new branch from the master branch.

2020-10-27 17:03 UTC, queensaldam commented
> > @queensaldam In this case, you can have **2 PRs that will not conflict.** You can create a new pull request with the task_id for the contact form only. If you have any issues, you can reach out. Remember, you create a new branch from the master branch.
> 
> Thank you

I've done it

2020-10-28 09:02 UTC, adaugochi commented
We have said it over time. "Don't have 2 PRs open at the same time". Some of these changes you have on this PR are still in the previous PR. Kindly ensure that one PR is merged first before creating another one to avoid confusion from your end. 

Going forward, you have to close this PR for now. Fix the comments on your previous PR, get it merged then proceed to create another one. Thanks. If you don't understand what I have said, kindly reach out

2020-10-31 21:43 UTC, closed without merging