[58] Develop an E-commerce Store Database
Dufuna-CodeCamp/Dufuna-CodeCamp20 pull request #774
Opened 2020-10-24 19:21 UTC by MYKEL7

## Task: `Develop an E-commerce Store Database `
- `Created an e-commerce database`

2020-10-25 00:49 UTC, adaugochi requested changes

2020-10-25 00:49 UTC, adaugochi commented on submissions/onyemeMichael/database/init.sql
> +    order_amount DECIMAL (20,4) NOT NULL,
Are you sure we have up to 20? same goes for others

2020-10-26 10:52 UTC, adaugochi requested changes

2020-10-26 10:52 UTC, adaugochi commented on submissions/onyemeMichael/database/init.sql
> +    product_image BLOB,
I think should be NOT NULL as well

2020-10-26 11:54 UTC, MYKEL7 commented
Done

On Mon, Oct 26, 2020, 11:52 AM Maryfaith Mgbede <notifications@github.com>
wrote:

> *@adaugochi* requested changes on this pull request.
> ------------------------------
>
> In submissions/onyemeMichael/database/init.sql
> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp20/pull/774#discussion_r511872012>
> :
>
> > +
> +-- Insert into admin_users
> +INSERT INTO admin_users (firstname, lastname, email, admin_password, phone_number)
> +VALUES ('Onyeme', 'Michael', 'onyememykel@gmail', 'iamblessed', '08182515388'),
> +	   ('Nifemi', 'Omotola', 'nifemi@email.com', 'omotola', '08012345678'),
> +       ('Olatokunbo', 'Fagbamigbe', 'tox@email.com', 'tox', '09012345678' ),
> +       ('Emmanuel', 'Ojo', 'emmaneul@email.com', 'emmanuel', '07031803086'),
> +       ('Ada', 'Mgbede', 'adaamgbede@email.com', 'adaa', '08109030672'),
> +       ('Toluwalase', 'Akintoye', 'toluakintoye@email.com', 'tolu', '08012785678');
> +
> +-- Products table
> +CREATE TABLE products (
> +	id INT NOT NULL AUTO_INCREMENT,
> +    product_name VARCHAR (50) NOT NULL,
> +    product_description VARCHAR (255) NOT NULL,
> +    product_image BLOB,
>
> I think should be NOT NULL as well
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp20/pull/774#pullrequestreview-516659933>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AMTFEMIBKBGUXYC5ZNA2L6DSMVIHRANCNFSM4S5ZEGLQ>
> .
>

2020-10-26 15:49 UTC, adaugochi requested changes

2020-10-26 15:49 UTC, adaugochi commented on submissions/onyemeMichael/database/init.sql
> +    zipcode INT NOT NULL,
Read the question again concerning `zipcode`

2020-10-27 09:29 UTC, adaugochi requested changes

2020-10-27 09:29 UTC, adaugochi commented on submissions/onyemeMichael/database/init.sql
> +VALUES ('Mykel str', 'Apapa', 'Lagos', 100335, 'Nigeria', 08182515388, 1 ),
phone_number should a string

2020-10-27 09:47 UTC, MYKEL7 commented
Done

On Tue, Oct 27, 2020, 10:29 AM Maryfaith Mgbede <notifications@github.com>
wrote:

> *@adaugochi* requested changes on this pull request.
> ------------------------------
>
> In submissions/onyemeMichael/database/init.sql
> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp20/pull/774#discussion_r512534846>
> :
>
> > +CREATE TABLE addresses (
> +	id INT NOT NULL AUTO_INCREMENT,
> +    street_adress VARCHAR (255) NOT NULL,
> +    city VARCHAR (50) NOT NULL,
> +    state_name VARCHAR (50) NOT NULL,
> +    zipcode INT,
> +    country VARCHAR (50) NOT NULL,
> +    phone_number VARCHAR (20) NOT NULL,
> +    customer_id INT NOT NULL,
> +    PRIMARY KEY (id),
> +    FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE CASCADE
> +);
> +
> +-- Insert into addresse table
> +INSERT INTO addresses (street_adress, city, state_name, zipcode, country, phone_number, customer_id)
> +VALUES ('Mykel str', 'Apapa', 'Lagos', 100335, 'Nigeria', 08182515388, 1 ),
>
> phone_number should a string
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp20/pull/774#pullrequestreview-517498676>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AMTFEMO64FGWDB677Y5MSSDSM2HH5ANCNFSM4S5ZEGLQ>
> .
>

2020-10-27 15:53 UTC, adaugochi requested changes
Kindly ensure you rerun your query when correction is made. Delete the DB and rerun the query again

2020-10-27 15:53 UTC, adaugochi commented on submissions/onyemeMichael/database/init.sql
> +VALUES ('Mykel str', 'Apapa', 'Lagos', '100335', 'Nigeria', '08182515388', '1' ),
customer_id is an `INT` and not a string

2020-10-27 15:53 UTC, adaugochi commented on submissions/onyemeMichael/database/init.sql
> +VALUES ('Mykel str', 'Apapa', 'Lagos', '100335', 'Nigeria', '08182515388', '1' ),
Same as zip code. Please note the differences

2020-10-28 08:55 UTC, adaugochi requested changes
Kindly note this differences

2020-10-28 08:55 UTC, adaugochi commented on submissions/onyemeMichael/database/init.sql
> +VALUES ('1', '138999', '138999', '1', '1');
unit_price and amount are DECIMAL, Why are you inserting a string

2020-10-28 08:55 UTC, adaugochi commented on submissions/onyemeMichael/database/init.sql
> +VALUES ('138999', now(), '1'),
`order_amount` is a DECIMAL, but you are inserting string

2020-10-28 11:18 UTC, adaugochi requested changes

2020-10-28 11:18 UTC, adaugochi commented on submissions/onyemeMichael/database/init.sql
> +VALUES (1, 138999, 138999, 1, 1);
amount and price are `decimal` not `int`

2020-10-28 11:18 UTC, adaugochi commented on submissions/onyemeMichael/database/init.sql
> +VALUES (1, 138999, 138999, 1, 1);
Same for others too

2020-10-31 18:00 UTC, adaugochi approved these changes

2020-10-31 18:01 UTC, merged