[65] Create & Style the Customer Signup Page using CSS- Frontend
Dufuna-CodeCamp/Dufuna-CodeCamp20 pull request #781
Opened 2020-10-26 14:47 UTC by Onyinye101

## Task: `[65] Create & Style the Customer Signup Page using CSS`
- `Created & Styled the Customer Signup Page using HTML and CSS`

<img width="1275" alt="Screenshot 2020-10-25 at 2 32 35 PM" src="https://user-images.githubusercontent.com/64909274/97186905-2fdbb200-17a2-11eb-9597-9c639a03a165.png">
<img width="293" alt="Screenshot 2020-10-26 at 3 45 59 PM" src="https://user-images.githubusercontent.com/64909274/97187178-7df0b580-17a2-11eb-9adc-7dedd5d3f9c0.png">
<img width="295" alt="Screenshot 2020-10-26 at 3 46 40 PM" src="https://user-images.githubusercontent.com/64909274/97187189-80eba600-17a2-11eb-83a1-99280942781e.png">

2020-10-26 15:29 UTC, adaugochi requested changes
I am still seeing product page task as part of this PR

2020-10-26 21:00 UTC, Onyinye101 commented
I don’t understand. How? 

Sent from my iPhone

> On 26 Oct 2020, at 16:29, Maryfaith Mgbede <notifications@github.com> wrote:
> 
> ﻿
> @adaugochi requested changes on this pull request.
> 
> I am still seeing product page task as part of this PR
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2020-10-27 09:02 UTC, adaugochi requested changes
Kindly click [here](https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp20/pull/781/files) to see the changes you made to your file

2020-10-27 10:37 UTC, ToluAkin requested changes

2020-10-27 10:37 UTC, ToluAkin commented on submissions/onyinyeChukwuka/css/sign-up.css
> +    font-family: Montserrat;
You don't need to specify font family again since you have specified in the body of the browser.

2020-10-27 10:37 UTC, ToluAkin commented on submissions/onyinyeChukwuka/HTML/index.html
> +    <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet">
You can use just one link instead of three. Try and figure out how to use multiple font family in one link @Onyinye101

2020-10-27 10:37 UTC, ToluAkin commented on submissions/onyinyeChukwuka/HTML-Forms/contactform.html
>  <!DOCTYPE html>
This should be in another pull request @Onyinye101

2020-10-27 13:13 UTC, closed without merging