[62] Create & Style the Customer Signup Page using CSS
Dufuna-CodeCamp/Dufuna-CodeCamp20 pull request #783
Opened 2020-10-26 22:28 UTC by Marienoir

## Task: ` Create & Style the Customer Signup Page using CSS`
- ` I created & Styled the Customer Signup Page using CSS`
![Capture](https://user-images.githubusercontent.com/40265625/97235312-e495c380-17e2-11eb-97b9-85314d07983c.PNG)
![Capture1](https://user-images.githubusercontent.com/40265625/97235319-e65f8700-17e2-11eb-8985-a6475680145a.PNG)
![Capture3](https://user-images.githubusercontent.com/40265625/97235324-e8294a80-17e2-11eb-85a1-79454c6a72ed.PNG)

2020-10-27 09:08 UTC, adaugochi commented
Well done @Marienoir 

But, I think there is more you can do. Spaces are not evenly distributed in the `body` section of your work, i.e `left and right`. Also the same goes for the form card. I can't see your footer section.

Kindly fix codefactor issue on your PR

2020-10-28 11:16 UTC, adaugochi requested changes
remove spaces on image names

Also, send a screenshot on your new implementation

2020-10-28 11:16 UTC, adaugochi commented on submissions/maryOkosun/html-forms/contact.html
> +
remove spaces

2020-10-28 22:00 UTC, Marienoir commented
![phone1](https://user-images.githubusercontent.com/40265625/97501287-4dab4180-1971-11eb-97ab-a5d05a52d837.PNG)
![phone2](https://user-images.githubusercontent.com/40265625/97501293-4f750500-1971-11eb-9d90-1d59d9a75e31.PNG)
![tablet1](https://user-images.githubusercontent.com/40265625/97501305-57cd4000-1971-11eb-804a-7cdcf160e3d3.PNG)
![tablet2](https://user-images.githubusercontent.com/40265625/97501314-5a2f9a00-1971-11eb-94f5-4ace201e9c98.PNG)
![web1](https://user-images.githubusercontent.com/40265625/97501316-5ac83080-1971-11eb-9bad-36d0d959e0a9.PNG)
![web2](https://user-images.githubusercontent.com/40265625/97501325-5dc32100-1971-11eb-8588-9298c5207bda.PNG)

2020-10-29 11:15 UTC, adaugochi commented
Well done @Marienoir 

We are making progress
Kindly let the text at the top to occupy available spaces (i.e left and right ) https://user-images.githubusercontent.com/40265625/97501287-4dab4180-1971-11eb-97ab-a5d05a52d837.PNG

2020-10-30 12:36 UTC, Marienoir commented
![phone3](https://user-images.githubusercontent.com/40265625/97705729-d67ec600-1ab4-11eb-82d2-22fff422d559.PNG)

2020-10-30 12:41 UTC, adaugochi requested changes
We want to try as much as possible to separate concerns. Kindly place all images inside the `images` folder that is in your `html` folder

2020-10-31 17:32 UTC, adaugochi requested changes
You have two `signup.html` file one inside the `css` folder and the other inside your `html-form`, Kindly remove the one in your `css` folder

2020-11-02 11:08 UTC, adaugochi approved these changes

2020-11-02 11:09 UTC, merged