[52] Develop a contact form page using HTML
Dufuna-CodeCamp/Dufuna-CodeCamp20 pull request #785
Opened 2020-10-27 16:56 UTC by queensaldam

## Task: `Develop a contact form page using html`
- `a contact from page was created`

2020-10-28 08:41 UTC, adaugochi requested changes

2020-10-28 08:41 UTC, adaugochi commented on submissions/damilolaSalami/html-form/contact.html
> +                <li><a href="productpage.html">Product Page</a></li>
Well done @queensaldam 

Kindly remove this linking between two pages and add them in your next task i.e Adding navigation links

2020-10-28 08:41 UTC, adaugochi commented on submissions/damilolaSalami/html/productpage.html
> +                <li><a href="../html/productpage.html"></a>Product page</li>
Same here too

2020-10-28 10:39 UTC, ToluAkin requested changes

2020-10-28 10:39 UTC, ToluAkin commented on submissions/damilolaSalami/html/productpage.html
>          <nav>
The changes made on this file revert it. It will conflict with the other pull request. You are only suppose to create the contact form. @queensaldam

2020-10-31 17:28 UTC, adaugochi approved these changes

2020-10-31 17:28 UTC, merged