[55] Add Page Navigation to your pages
Dufuna-CodeCamp/Dufuna-CodeCamp20 pull request #808
Opened 2020-10-31 22:07 UTC by queensaldam

## Task: `Added navigation page
- 'Navigation page to product page & contact page was added'

2020-11-01 07:47 UTC, TundeOladejo approved these changes

2020-11-02 08:22 UTC, adaugochi requested changes

2020-11-02 08:22 UTC, adaugochi commented on submissions/damilolaSalami/html-form/contact.html
> +                <li><a href="productpage.html">Product Page</a></li>
Are you sure this `href="productpage.html"` works? Try testing this link.

2020-11-03 09:19 UTC, adaugochi approved these changes

2020-11-03 09:19 UTC, merged