[63] Style the Contact Us Page using CSS
Dufuna-CodeCamp/Dufuna-CodeCamp20 pull request #817
Opened 2020-11-02 21:20 UTC by Marienoir

##Task: Style the Contact Us Page using CSS
- `I styled the contact page using CSS`
![phone1](https://user-images.githubusercontent.com/40265625/97920266-7ceaf580-1d59-11eb-8f16-2d00163afea7.PNG)
![phone2](https://user-images.githubusercontent.com/40265625/97920273-7eb4b900-1d59-11eb-880c-6a427416da00.PNG)
![phone3](https://user-images.githubusercontent.com/40265625/97920274-7f4d4f80-1d59-11eb-8a54-cac8bc04c182.PNG)
![tablet](https://user-images.githubusercontent.com/40265625/97920277-7fe5e600-1d59-11eb-8a66-080d86d4d39b.PNG)
![tablet2](https://user-images.githubusercontent.com/40265625/97920278-807e7c80-1d59-11eb-8d49-cf0cbbab6ff6.PNG)
![web](https://user-images.githubusercontent.com/40265625/97920281-81171300-1d59-11eb-98d1-488729c62c63.PNG)
![web1](https://user-images.githubusercontent.com/40265625/97920284-81afa980-1d59-11eb-8791-5078aa7d92e5.PNG)

2020-11-03 09:02 UTC, ToluAkin requested changes
@Marienoir You used a lot of width and height which will make your webpage pretty much static. If you want space around your elements use padding or margin. Try and take time to review page and use more of  padding or margin.

2020-11-04 20:48 UTC, Marienoir commented
![1](https://user-images.githubusercontent.com/40265625/98166228-65417780-1ee7-11eb-9e45-53de26504f0b.PNG)
![2](https://user-images.githubusercontent.com/40265625/98166231-6672a480-1ee7-11eb-822a-f6918ba7d642.PNG)
![3](https://user-images.githubusercontent.com/40265625/98166236-670b3b00-1ee7-11eb-82ce-e7c92178febb.PNG)
![4](https://user-images.githubusercontent.com/40265625/98166238-67a3d180-1ee7-11eb-96de-7cb8e0ed779f.PNG)
![5](https://user-images.githubusercontent.com/40265625/98166240-683c6800-1ee7-11eb-8900-828004ad697c.PNG)
![6](https://user-images.githubusercontent.com/40265625/98166241-68d4fe80-1ee7-11eb-8871-fced45cc34ac.PNG)
![7](https://user-images.githubusercontent.com/40265625/98166246-6a062b80-1ee7-11eb-81ea-1d80fc71ba31.PNG)

2020-11-04 20:49 UTC, Marienoir commented on submissions/maryOkosun/css/contact.css
> +	box-sizing: border-box;
I have corrected that. Thanks

2020-11-04 20:49 UTC, Marienoir commented on submissions/maryOkosun/css/contact.css
> +body{
Done also

2020-11-04 20:49 UTC, Marienoir commented on submissions/maryOkosun/css/contact.css
> +	height: 40%;
Thanks a lot. I have effected the change.

2020-11-04 20:50 UTC, Marienoir commented on submissions/maryOkosun/css/contact.css
> +	width: 130px;
Okay. I used just width now in my new PR. Kindly review, thanks.

2020-11-06 08:50 UTC, adaugochi approved these changes

2020-11-06 08:54 UTC, merged