[66] Style the Contact Us Page using CSS- Frontend
Dufuna-CodeCamp/Dufuna-CodeCamp20 pull request #822
Opened 2020-11-03 16:07 UTC by Onyinye101

## Task: `[66] Style the Contact Us Page using CSS`
- `Styled the Contact Us Page using CSS`

![Uploading Screenshot 2020-10-25 at 2.32.23 PM.png…]()
<img width="292" alt="Screenshot 2020-11-03 at 5 06 10 PM" src="https://user-images.githubusercontent.com/64909274/98010449-000e5900-1df7-11eb-99d2-eb3183427be4.png">
<img width="291" alt="Screenshot 2020-11-03 at 5 06 39 PM" src="https://user-images.githubusercontent.com/64909274/98010459-03094980-1df7-11eb-9115-e9953088ace2.png">

2020-11-03 16:16 UTC, adaugochi commented
Kindly send a screenshot of the desktop view. I can only see the mobile view

2020-11-03 16:18 UTC, Onyinye101 commented
@adaugochi I have done that now

2020-11-04 09:30 UTC, adaugochi requested changes
In your previous PR, I dropped a comment saying that any styling whose property value is set to `normal` shouldn't be used cos by default it is `normal`. There is no need for writing it out again.

I also dropped a comment concerning the font-family. Since you already declared it on the body tag there is no need using them on individual elements again.

Kindly take note of this corrections.

2020-11-06 08:33 UTC, adaugochi approved these changes

2020-11-06 08:33 UTC, merged