[77] Database Design For A Transportation Company
Dufuna-CodeCamp/Dufuna-CodeCamp20 pull request #829
Opened 2020-11-05 11:35 UTC by MYKEL7

## Task: `Database Design For A Transportation Company`
- `I created a database for a transportation company `

2020-11-05 14:13 UTC, adaugochi requested changes
Also, remove all insert queries from the tables

2020-11-05 14:13 UTC, adaugochi commented on submissions/onyemeMichael/database/transportation.sql
> +CREATE TABLE cabin_classes (
This table is not need

2020-11-05 14:13 UTC, adaugochi commented on submissions/onyemeMichael/database/transportation.sql
> +CREATE TABLE classes (
this table is not needed

2020-11-05 14:13 UTC, adaugochi commented on submissions/onyemeMichael/database/transportation.sql
> +CREATE TABLE accidents (
This table requires just 3 columns

2020-11-06 08:31 UTC, adaugochi requested changes
I ask you to remove those things I pointed, but you went ahead to comment them. Kindly remove them. They shouldn't be seen at all

2020-11-06 08:31 UTC, adaugochi commented on submissions/onyemeMichael/database/transportation.sql
> +CREATE TABLE accidents (
Kindly read thoroughly the task you are given. This is not correct

2020-11-07 10:00 UTC, adaugochi requested changes

2020-11-07 22:30 UTC, MYKEL7 commented
Done.

On Sat, Nov 7, 2020, 11:00 AM Maryfaith Mgbede <notifications@github.com>
wrote:

> *@adaugochi* requested changes on this pull request.
> ------------------------------
>
> In submissions/onyemeMichael/database/transportation.sql
> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp20/pull/829#discussion_r518676618>
> :
>
> > +CREATE TABLE passengers (
> +	id INT NOT NULL AUTO_INCREMENT,
> +    firstname VARCHAR(25) NOT NULL,
> +    lastname VARCHAR(25) NOT NULL,
> +    sex VARCHAR(7) NOT NULL,
> +    age INT NOT NULL,
> +    PRIMARY KEY(id)
> +);
> +
> +-- Trips Table
> +CREATE TABLE trips (
> +	id INT NOT NULL AUTO_INCREMENT,
> +    passenger_class INT NOT NULL,
> +    passenger_ticket VARCHAR(15) NOT NULL,
> +    trip_fare DECIMAL(16,4) NOT NULL,
> +    number_of_parents_children INT NOT NULL,
>
> There is a column missing on this table. Kindly read the instruction again
> on the task, you will figure it out
> ------------------------------
>
> In submissions/onyemeMichael/database/transportation.sql
> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp20/pull/829#discussion_r518677020>
> :
>
> > +    age INT NOT NULL,
> +    PRIMARY KEY(id)
> +);
> +
> +-- Trips Table
> +CREATE TABLE trips (
> +	id INT NOT NULL AUTO_INCREMENT,
> +    passenger_class INT NOT NULL,
> +    passenger_ticket VARCHAR(15) NOT NULL,
> +    trip_fare DECIMAL(16,4) NOT NULL,
> +    number_of_parents_children INT NOT NULL,
> +    number_of_siblings_spouses INT NOT NULL,
> +    passenger_id INT NULL,
> +    point_of_embarkation VARCHAR(150) NOT NULL,
> +    PRIMARY KEY(id),
> +    FOREIGN KEY(passenger_class) REFERENCES classes(id) ON DELETE CASCADE,
>
> This line of code is wrong. MySQL workbench would have thrown an error If
> you run the query you have currently on this file
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp20/pull/829#pullrequestreview-525051559>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AMTFEMLWMNKDFJFHHPME3QLSOULEZANCNFSM4TLH4TIQ>
> .
>

2020-11-09 09:14 UTC, adaugochi approved these changes

2020-11-09 09:15 UTC, merged