[65] Create & Style the customer signup page using CSS
Dufuna-CodeCamp/Dufuna-CodeCamp20 pull request #834
Opened 2020-11-05 22:29 UTC by cherishebojudah

## Task: `[65] Create & Style the customer signup page using CSS
![Sign-up page mobile 1](https://user-images.githubusercontent.com/71259714/98303537-89bc5300-1fbe-11eb-83fc-6b4a026b9aa2.png)
![Sign-up page mobile 2](https://user-images.githubusercontent.com/71259714/98303560-9345bb00-1fbe-11eb-8a65-6cda181053df.png)
![Sign-up page tablet 1](https://user-images.githubusercontent.com/71259714/98303568-96d94200-1fbe-11eb-953c-09a44b33e91c.png)
![Sign-up page tablet 2](https://user-images.githubusercontent.com/71259714/98303579-9c368c80-1fbe-11eb-8000-b7ae95511ba9.png)
![Sign-up page web 1](https://user-images.githubusercontent.com/71259714/98303589-9fca1380-1fbe-11eb-89ff-dd9260107173.png)
![Sign-up page web 2](https://user-images.githubusercontent.com/71259714/98303609-ab1d3f00-1fbe-11eb-9c1f-0f5a80fbefdd.png)

`
- `created and designed sign-up page for ecommerce website`

2020-11-06 08:22 UTC, adaugochi commented
Beautiful. well done @cherishebojudah Kindly fix cofactor issue

2020-11-07 09:58 UTC, adaugochi requested changes
Well done so far
Kindly place your signUp.html folder inside `html-forms` folder

2020-11-07 10:45 UTC, adaugochi requested changes

2020-11-07 10:45 UTC, adaugochi commented on submissions/ebojudahCherish/css/signUp.html
> +<!DOCTYPE html>
Kindly place this file inside `html-forms` folder. 
![image](https://user-images.githubusercontent.com/43061141/98438999-ba030f00-20ee-11eb-82b7-0de934857aae.png)

2020-11-07 20:32 UTC, adaugochi reviewed
You currently have two signup.html files. 1 in css folder and the other in html-forms folders. Kindly delete the one in css folder

2020-11-07 20:33 UTC, adaugochi requested changes
Rename your `styles.css` to `signup.css`

2020-11-10 21:44 UTC, cherishebojudah commented
> Rename your `styles.css` to `signup.css`

@adaugochi about this, this file holds all the styling for all my pages, so it might not be ideal for me to name it 'signup.css'. Thanks for all your feedback.

2020-11-11 09:35 UTC, adaugochi approved these changes

2020-11-11 09:35 UTC, merged