[63] Style the Contact Us Page using CSS
Dufuna-CodeCamp/Dufuna-CodeCamp20 pull request #854
Opened 2020-11-09 22:55 UTC by ayotola-t

**Mobile View:**
<img width="371" alt="Screenshot 2020-11-09 at 23 50 03" src="https://user-images.githubusercontent.com/71293113/98605828-efe4f680-229a-11eb-99c4-cc5f66a48e68.png">
<img width="359" alt="Screenshot 2020-11-09 at 23 50 23" src="https://user-images.githubusercontent.com/71293113/98605836-f3787d80-229a-11eb-87fd-c524ae5eac1e.png">
<img width="354" alt="Screenshot 2020-11-09 at 23 50 29" src="https://user-images.githubusercontent.com/71293113/98605838-f4111400-229a-11eb-8d65-195d56c12dbd.png">

**Web View:**
<img width="1440" alt="Screenshot 2020-11-09 at 23 51 24" src="https://user-images.githubusercontent.com/71293113/98605917-0ee38880-229b-11eb-937e-3c577b75e2f3.png">

2020-11-09 23:25 UTC, ayotola-t commented
**Tablet view:**
<img width="780" alt="Screenshot 2020-11-10 at 00 23 39" src="https://user-images.githubusercontent.com/71293113/98608334-caa6b700-229f-11eb-8ab0-9a17919bdb65.png">
<img width="775" alt="Screenshot 2020-11-10 at 00 23 47" src="https://user-images.githubusercontent.com/71293113/98608346-ce3a3e00-229f-11eb-80ac-a7ab626a7006.png">

2020-11-10 09:39 UTC, adaugochi requested changes

2020-11-10 09:39 UTC, adaugochi commented on submissions/ayotolaTehingbola/css/contact.css
> +    /* min-height: 100vh; */
Well done.
I think you forgot to remove this comment

2020-11-10 14:52 UTC, adaugochi approved these changes

2020-11-10 14:52 UTC, merged