{64} Style the Product Details Page using CSS
Dufuna-CodeCamp/Dufuna-CodeCamp20 pull request #856
Opened 2020-11-10 12:53 UTC by Tocyn

![Screen Shot 2020-11-10 at 12 36 03 PM](https://user-images.githubusercontent.com/70757475/98676239-9f819d80-235b-11eb-9273-da9f72be38ff.png)
![Screen Shot 2020-11-10 at 12 47 25 PM](https://user-images.githubusercontent.com/70757475/98676250-a1e3f780-235b-11eb-81f7-49dfa755b7b0.png)
![Screen Shot 2020-11-10 at 1 44 57 PM](https://user-images.githubusercontent.com/70757475/98676260-a6101500-235b-11eb-83b7-45d638e5b573.png)

2020-11-10 13:20 UTC, Tocyn commented
![Screen Shot 2020-11-10 at 2 12 17 PM](https://user-images.githubusercontent.com/70757475/98678881-7fec7400-235f-11eb-8cc0-8460c114f620.png)
![Screen Shot 2020-11-10 at 2 12 31 PM](https://user-images.githubusercontent.com/70757475/98678877-7ebb4700-235f-11eb-97c5-3a4731e0bee1.png)
![Screen Shot 2020-11-10 at 2 12 56 PM](https://user-images.githubusercontent.com/70757475/98678868-7bc05680-235f-11eb-8c89-2ac567765025.png)

2020-11-11 09:31 UTC, adaugochi commented
The content on the body section should take more place around it. It looks too tiny and compressed. Meanwhile there are spaces left and right

2020-11-11 10:02 UTC, Tocyn commented
![Screen Shot 2020-11-11 at 10 57 49 AM](https://user-images.githubusercontent.com/70757475/98797738-440fe800-240d-11eb-9689-840e27aa4be7.png)
![Screen Shot 2020-11-11 at 10 58 18 AM](https://user-images.githubusercontent.com/70757475/98797742-45d9ab80-240d-11eb-9504-485e763376ba.png)

2020-11-11 10:21 UTC, Tocyn commented
![Screen Shot 2020-11-11 at 11 16 45 AM](https://user-images.githubusercontent.com/70757475/98799844-ee890a80-240f-11eb-9055-3ada551ef827.png)

2020-11-12 09:02 UTC, Ireti203 commented
The input field for email address on the footer (mobile screen) seem invisible. Can you correct this please.

2020-11-13 10:20 UTC, Ireti203 requested changes
Kindly give this css file a better name. Dont forget to effect the change in your html file. 

Weldone @Tocyn

2020-11-15 19:53 UTC, Tocyn commented
![Screen Shot 2020-11-15 at 8 41 11 PM](https://user-images.githubusercontent.com/70757475/99195105-005a0d00-2784-11eb-8804-f030c8084cac.png)
![Screen Shot 2020-11-15 at 8 16 02 PM](https://user-images.githubusercontent.com/70757475/99195107-0354fd80-2784-11eb-8b8b-bf1814751217.png)

2020-11-16 10:44 UTC, Tocyn commented
> The input field for email address on the footer (mobile screen) seem invisible. Can you correct this please.

Done. kindly review

2020-11-17 08:48 UTC, adaugochi commented
Kindly style your input field and button

2020-11-17 11:27 UTC, Tocyn commented
![Screen Shot 2020-11-17 at 12 19 49 PM](https://user-images.githubusercontent.com/70757475/99384636-02c97d80-28d0-11eb-970d-55c1f41d0478.png)
![Screen Shot 2020-11-17 at 12 20 30 PM](https://user-images.githubusercontent.com/70757475/99384797-3dcbb100-28d0-11eb-88af-9ef6a028728d.png)
![Screen Shot 2020-11-17 at 12 23 02 PM](https://user-images.githubusercontent.com/70757475/99384642-052bd780-28d0-11eb-922e-62286d3c6f38.png)

2020-11-18 09:34 UTC, ToluAkin requested changes
Try as much as possible to avoid using `br` in your html. Well done!

2020-11-18 09:34 UTC, ToluAkin commented on submissions/oluwatosinOke/html/productPage.html
> +        <form>
@Tocyn Your product page should not be wrapped in a form tag. It isn't a form.

2020-11-18 09:34 UTC, ToluAkin commented on submissions/oluwatosinOke/html/productPage.html
> +                            <input min="1" type="number" id="quantity" name="quantity" value="0" /><br>
Remove the `<br>` here and style the input field with css @Tocyn

2020-11-18 09:34 UTC, ToluAkin commented on submissions/oluwatosinOke/html/productPage.html
> +                        <h3> Product Description: <br>
Remove the `<br>` here and style the input field with css @Tocyn

2020-11-18 09:34 UTC, ToluAkin commented on submissions/oluwatosinOke/html/productPage.html
> +                                    <figcaption>iphone-11 <br> price: &#x20A6;120,000</figcaption>
Put them in 2 separate paragraph tags instead. @Tocyn

2020-11-18 09:34 UTC, ToluAkin commented on submissions/oluwatosinOke/html/productPage.html
> +                        <p> Copyright &copy; 2020 myfavoriteonlinestore.com<br>
Put them in 2 separate paragraph tags instead. @Tocyn

2020-11-18 12:19 UTC, ToluAkin requested changes

2020-11-18 12:19 UTC, ToluAkin commented on submissions/oluwatosinOke/html/productPage.html
> +                        <h3> <p>Product Description:</p>
Either you use the p tag or the h3 tag. You can't have p nested on h3 @Tocyn

2020-11-19 09:38 UTC, adaugochi approved these changes

2020-11-19 09:39 UTC, merged

2020-11-19 09:39 UTC, adaugochi commented
Kindly use `[]` not `{}` @Tocyn  on your PR title.