[63] Style the Contact Us Page using CSS
Dufuna-CodeCamp/Dufuna-CodeCamp20 pull request #868
Opened 2020-11-13 04:45 UTC by bilkisutace

## Task: `[63] Style the Contact Us Page using CSS`
- `Styled the Contact Us Page using CSS`
![mobile-signup](https://user-images.githubusercontent.com/69322971/99029641-47bd7f00-2573-11eb-80b2-93d85866e975.JPG)
![mobile-signup2](https://user-images.githubusercontent.com/69322971/99029643-49874280-2573-11eb-87da-8a5aa1c74128.JPG)
![tablet-signup](https://user-images.githubusercontent.com/69322971/99029644-4a1fd900-2573-11eb-96ae-3eb44b00ab3a.JPG)
![tablet-signup2](https://user-images.githubusercontent.com/69322971/99029647-4ab86f80-2573-11eb-8bba-fc95d28c28da.JPG)
![web-signup](https://user-images.githubusercontent.com/69322971/99029648-4b510600-2573-11eb-8da0-af8d6a5c0f5a.JPG)
![web-signup2](https://user-images.githubusercontent.com/69322971/99029649-4be99c80-2573-11eb-8a07-13a4e922ea02.JPG)

2020-11-13 10:34 UTC, Ireti203 commented
Weldone @bilkisutace 

Your social media icons looks lumped together. Can you give it some sort of padding.

2020-11-13 10:42 UTC, Ireti203 requested changes

2020-11-13 10:42 UTC, Ireti203 commented on submissions/bilkisuTace/css/contactus.css
> +            BODY
Remove extra white space. You can put the comment on a single line

2020-11-13 10:42 UTC, Ireti203 commented on submissions/bilkisuTace/css/contactus.css
> +            FOOTER
Same here

2020-11-13 10:42 UTC, Ireti203 commented on submissions/bilkisuTace/html-forms/contactUs.html
> +
Remove whitespace.

2020-11-13 10:42 UTC, Ireti203 commented on submissions/bilkisuTace/html-forms/contactUs.html
> +
Remove whitespace

2020-11-13 10:42 UTC, Ireti203 commented on submissions/bilkisuTace/html-forms/contactUs.html
> +
Remove whitespace.

2020-11-13 10:42 UTC, Ireti203 commented on submissions/bilkisuTace/html-forms/contactUs.html
> +			<div class="div-form">
Kindly format properly.

2020-11-13 10:42 UTC, Ireti203 commented on submissions/bilkisuTace/html-forms/contactUs.html
> +                                <input type="email" name="email" id="email" placeholder="Enter your email address"/>
Kindly format this file properly.

2020-11-13 13:55 UTC, adaugochi commented
From the screenshot you sent, the form card isn't aligned properly. Kindly check the mockup again

2020-11-16 12:58 UTC, bilkisutace commented
![mobileview1](https://user-images.githubusercontent.com/69322971/99255083-a99c1400-2813-11eb-9f4f-160cf11d256f.JPG)
![mobileview2](https://user-images.githubusercontent.com/69322971/99255087-aacd4100-2813-11eb-96e3-dda7105a0d99.JPG)
![tabletview](https://user-images.githubusercontent.com/69322971/99255089-aacd4100-2813-11eb-8817-cf81d1c2ffba.JPG)
![webview](https://user-images.githubusercontent.com/69322971/99255091-ab65d780-2813-11eb-8714-30d3378e7b39.JPG)

2020-11-18 09:19 UTC, adaugochi requested changes

2020-11-18 09:19 UTC, adaugochi commented on submissions/bilkisuTace/css/contactus.css
> +    flex-direction: row;
by default, it has `row` as flex-direction. So there is no need to using it

2020-11-18 09:19 UTC, adaugochi commented on submissions/bilkisuTace/css/contactus.css
> +    flex-direction: row;
same here

2020-11-18 09:19 UTC, adaugochi commented on submissions/bilkisuTace/html-forms/contactUs.html
> +					<ul class="body-social">
kindly indent your code properly

2020-11-18 09:42 UTC, ToluAkin requested changes
@bilkisutace Remove all break elements in your html file

2020-11-18 09:42 UTC, ToluAkin commented on submissions/bilkisuTace/html-forms/contactUs.html
> +                                 <label id="email" for="email"><b id="news-sign">Sign up for our Newsletter</label></b><br/><br>
Remove the break on this label and style with css @bilkisutace

2020-11-18 09:42 UTC, ToluAkin commented on submissions/bilkisuTace/html-forms/contactUs.html
> +                                <button class="white-button" type="button">SUBMIT</button>
I think you should reduce the font-size of your button. The button seem to be bigger than the text input. @bilkisutace

2020-11-18 09:42 UTC, ToluAkin commented on submissions/bilkisuTace/html-forms/contactUs.html
> +						<a href="contact.html">Contact Us </a><br/><br/>
You should put the links in separate span elements or you use list to render them. @bilkisutace Also, remove the br around the links

2020-11-26 09:36 UTC, adaugochi approved these changes

2020-11-26 09:36 UTC, merged