[65] Create & Style the Customer SignUp Page Using CSS
Dufuna-CodeCamp/Dufuna-CodeCamp20 pull request #876
Opened 2020-11-13 20:05 UTC by queensaldam

## Task: `Create & Style customer sign up page`
- `Styled CSS page`

2020-11-14 10:54 UTC, ToluAkin requested changes

2020-11-14 10:54 UTC, ToluAkin commented on submissions/damilolaSalami/css/signUp.css
> +.body{
Use body as an element instead of as a class @queensaldam

2020-11-14 10:54 UTC, ToluAkin commented on submissions/damilolaSalami/css/signUp.css
> +    height: 75px;
Use padding or margin instead of setting the height @queensaldam

2020-11-14 10:54 UTC, ToluAkin commented on submissions/damilolaSalami/css/signUp.css
> +    height: 75px;
You should set only either of the height or width. That way, the image can resize based on screen size rather than having it static @queensaldam

2020-11-14 10:54 UTC, ToluAkin commented on submissions/damilolaSalami/css/signUp.css
> +    font-family: 'Arial';
No need to set this here, you have it in the body element already @queensaldam

2020-11-14 10:54 UTC, ToluAkin commented on submissions/damilolaSalami/css/signUp.css
> +    font-family: 'Arial';
No need to set this here, you have it in the body element already @queensaldam

2020-11-14 10:54 UTC, ToluAkin commented on submissions/damilolaSalami/css/signUp.css
> +    font-family: 'Arial Narrow';
No need to set this here, you have it in the body element already @queensaldam

2020-11-14 10:54 UTC, ToluAkin commented on submissions/damilolaSalami/css/signUp.css
> +    font-family: 'Arial';
No need to set this here, you have it in the body element already @queensaldam

2020-11-14 10:54 UTC, ToluAkin commented on submissions/damilolaSalami/css/signUp.css
> +    font-family: 'Arial';
No need to set this here, you have it in the body element already @queensaldam

2020-11-14 10:54 UTC, ToluAkin commented on submissions/damilolaSalami/css/signUp.css
> +    width: 150px;
Use padding instead of setting the height and width of a button @queensaldam

2020-11-14 10:54 UTC, ToluAkin commented on submissions/damilolaSalami/css/signUp.css
> +        font-family: 'Arial';
No need to set this here, you have it in the body element already @queensaldam

2020-11-14 10:54 UTC, ToluAkin commented on submissions/damilolaSalami/html-form/signUp.html
> +    <section>
Remove all `br` elements from this file and style the input field appropriately with css. @queensaldam

2020-11-14 10:54 UTC, ToluAkin commented on submissions/damilolaSalami/html-form/signUp.html
> +        <div class="one containertwo">
Using one, two or three as class names is not straightforward and explanatory to what it stands for. You need to update the names to be related to where is been used or what they are doing @queensaldam

2020-11-14 10:54 UTC, ToluAkin commented
@queensaldam add screenshot of your page in mobile and desktop view

2020-11-14 16:09 UTC, adaugochi requested changes
well done. Kindly make class name or id names to be more descriptive. Using things like `one, two, three` is not cool

2020-11-17 08:44 UTC, adaugochi requested changes
Kindly add a screenshot of what you did

2020-11-17 22:18 UTC, queensaldam commented
![mobile signup page 2](https://user-images.githubusercontent.com/58794483/99457356-21a92d80-292b-11eb-9dc4-2eccdcff1798.PNG)
![mobile signup page](https://user-images.githubusercontent.com/58794483/99457359-22da5a80-292b-11eb-9a8c-99d0ab75c2b4.PNG)
![sign up page tablet 2](https://user-images.githubusercontent.com/58794483/99457361-2372f100-292b-11eb-9217-7508e8a578ea.PNG)
![sign up page tablet](https://user-images.githubusercontent.com/58794483/99457362-240b8780-292b-11eb-9d02-2cf87be542f0.PNG)
![sign up page web](https://user-images.githubusercontent.com/58794483/99457365-240b8780-292b-11eb-8794-af3e2a1fbfb2.PNG)

2020-11-18 11:36 UTC, ToluAkin requested changes
@queensaldam Well done! You need to remove all the font-family that were set in element that are not the body element

2020-11-18 11:36 UTC, ToluAkin commented on submissions/damilolaSalami/css/signUp.css
> +    height: 75px;
You should set only either of the height or width. That way, the image can resize based on screen size rather than having it static @queensaldam

2020-11-18 11:36 UTC, ToluAkin commented on submissions/damilolaSalami/css/signUp.css
> +    font-family: 'Arial';
@queensaldam Don't set font-family again in the elements you have it in the body already. Having it in the body means, every single element that the body wraps will have that same font-family.

2020-11-18 11:36 UTC, ToluAkin commented on submissions/damilolaSalami/html-form/signUp.html
> +    <section>
Remove all br elements from this file and style the input field appropriately with css. @queensaldam

2020-11-27 09:12 UTC, adaugochi approved these changes

2020-11-27 09:13 UTC, merged