[109] The Software Developer Conditionals - Frontend
Dufuna-CodeCamp/Dufuna-CodeCamp20 pull request #879
Opened 2020-11-14 11:56 UTC by Onyinye101

## Task: `[109] The Software Developer Conditionals`
- `Created softwaredeveloper.js`

2020-11-14 15:07 UTC, BenjaminKamena requested changes
Convert positiveDifference to an absolute number, use Math.ab to do that

2020-11-14 15:18 UTC, Onyinye101 commented
Why? 

Sent from my iPhone

> On 14 Nov 2020, at 16:07, Benjamin Kamena <notifications@github.com> wrote:
> 
> ﻿
> @BenjaminKamena requested changes on this pull request.
> 
> Convert positiveDifference to an absolute number, use Math.ab to do that
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2020-11-14 15:21 UTC, BenjaminKamena commented
The criteria is saying absolute number right?

2020-11-14 15:25 UTC, BenjaminKamena commented
Ohh sorry its saying positive number, so need to change it to positive number by using Math.ab

2020-11-14 15:38 UTC, TundeOladejo requested changes

2020-11-14 15:38 UTC, TundeOladejo commented on submissions/onyinyeChukwuka/javascript/softwaredeveloper.js
> +const positiveDifference = 123 - 7;
Use `Math.abs` to return an absolute value

2020-11-14 15:40 UTC, TundeOladejo commented
> Ohh sorry its saying positive number, so need to change it to positive number by using Math.ab

Nice one @BenjaminKamena. It's `Math.abs` not `Math.ab`

2020-11-16 10:10 UTC, adaugochi requested changes
@Onyinye101 

You might be wondering why you are asked to use `Math.abs`. What that `Math` function or method does is to return the absolute value of a number. E.g if you do `2 - 5` and you make use of the `Math.abs` method you will get `3` instead of `-3`. 

So your task says `positive difference between 7 and 123`. Meaning when you so `7 - 123` even when you know it will give you a negative value, you still want to get a positive value. I don't know if you understand? 

Instead of you doing this `const positiveDifference = 123 - 7;` like what most of you did, the best would have been this `const positiveDifference = Math.abs(7 - 123)`;

2020-11-16 10:13 UTC, Onyinye101 commented
Thank you so much for this. It’s very insightful. Thank you again. 

Sent from my iPhone

> On 16 Nov 2020, at 11:10, Maryfaith Mgbede <notifications@github.com> wrote:
> 
> ﻿
> @adaugochi requested changes on this pull request.
> 
> @Onyinye101
> 
> You might be wondering why you are asked to use Math.abs. What that Math function or method does is to return the absolute value of a number. E.g if you do 2- 5 and you make use of the Math.abs method you will get 3 instead of -3.
> 
> So your task says positive difference between 7 and 123. Meaning when you so 7 - 123 even when you know it will give you a negative sign, you still want to get a positive value. I don't know if you understand?
> 
> Instead of you doing this const positiveDifference = 123 - 7; like what most of you did, the best would have been this const positiveDifference = Math.abs(7 - 123);
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2020-11-16 12:53 UTC, adaugochi approved these changes

2020-11-16 12:53 UTC, merged