[20] Sign-Up Form Validation
Dufuna-CodeCamp/Dufuna-CodeCamp20 pull request #880
Opened 2020-11-14 12:24 UTC by kazeemerinfolami

## Task: `[20] Sign-Up Form Validation`
- `SignUp Form Validation`

2020-11-14 16:02 UTC, ToluAkin requested changes

2020-11-14 16:02 UTC, ToluAkin commented on submissions/kazeemErinfolami/htmlForms/signUp.html
> +      <form id="formValidation" method="POST">
You can remove the `method` attribute. It is not needed. @kazeemerinfolami

2020-11-16 10:23 UTC, adaugochi requested changes

2020-11-16 10:23 UTC, adaugochi commented on submissions/kazeemErinfolami/javascript/Dom/signUp.js
> +  let name = "",
Kindly declare these variables outside the function

2020-11-16 19:15 UTC, kazeemerinfolami commented
Done

2020-11-17 08:43 UTC, adaugochi approved these changes

2020-11-17 08:43 UTC, merged