[21] Contact Form Validation
Dufuna-CodeCamp/Dufuna-CodeCamp20 pull request #890
Opened 2020-11-17 13:46 UTC by kazeemerinfolami

## Task: `[21] Contact Form Validation`
- `Contact Form Validation`

2020-11-18 10:29 UTC, kazeemerinfolami commented
Please check my PR

2020-11-18 11:38 UTC, ToluAkin requested changes

2020-11-18 11:38 UTC, ToluAkin commented on submissions/kazeemErinfolami/javascript/Dom/contact.js
> +  subjectReg = "",
I think you should use the empty quotes directly instead of creating a variable for it. @kazeemerinfolami

2020-11-18 11:38 UTC, ToluAkin commented on submissions/kazeemErinfolami/javascript/Dom/contact.js
> +  subjectError = "",
I think you should use the empty quotes directly instead of creating a variable for it. @kazeemerinfolami

2020-11-18 11:38 UTC, ToluAkin commented on submissions/kazeemErinfolami/javascript/Dom/contact.js
> +let fullNameError = "no special cha",
This error message is incomplete @kazeemerinfolami

2020-11-18 15:47 UTC, kazeemerinfolami commented
It's all fixed

2020-11-19 09:21 UTC, adaugochi approved these changes

2020-11-19 09:21 UTC, merged