[67] Style the Product Details Using CSS-Frontend
Dufuna-CodeCamp/Dufuna-CodeCamp20 pull request #914
Opened 2020-11-20 17:21 UTC by gracioust

## Task: `Style the Product Details Using CSS-Frontend`
- `Styled the Product Details Using CSS-Frontend`
![product1](https://user-images.githubusercontent.com/18602498/99829806-12112b00-2b5d-11eb-9c18-4e09e02c149f.PNG)
![product2](https://user-images.githubusercontent.com/18602498/99829842-1c332980-2b5d-11eb-940d-a517014a9431.PNG)
![product3](https://user-images.githubusercontent.com/18602498/99829850-20f7dd80-2b5d-11eb-8717-ef842d5229a9.PNG)
![product4](https://user-images.githubusercontent.com/18602498/99829859-2523fb00-2b5d-11eb-87e5-be23df11add6.PNG)
![product5](https://user-images.githubusercontent.com/18602498/99829872-2bb27280-2b5d-11eb-8a08-6141c8b336e4.PNG)
![product6](https://user-images.githubusercontent.com/18602498/99829880-2f45f980-2b5d-11eb-8bf2-f587e8cbea18.PNG)

2020-11-21 10:51 UTC, adaugochi commented
Well done @gracioust 

But, the last two screenshots don't look too ok. The cards look compressed. Kindly rework them

2020-11-26 12:48 UTC, gracioust commented
Reworked the screenshots
![product1](https://user-images.githubusercontent.com/18602498/100352859-e626f700-2fed-11eb-8ed4-f90396b05bb3.PNG)
![product2](https://user-images.githubusercontent.com/18602498/100352875-ec1cd800-2fed-11eb-90d5-dcc21c1b03c1.PNG)
![product3](https://user-images.githubusercontent.com/18602498/100352891-f048f580-2fed-11eb-91db-009d43f8a3aa.PNG)
![product4](https://user-images.githubusercontent.com/18602498/100352898-f4751300-2fed-11eb-83ad-74b0ba415349.PNG)
![product5](https://user-images.githubusercontent.com/18602498/100352914-f8a13080-2fed-11eb-8535-83896461e82c.PNG)
![product6](https://user-images.githubusercontent.com/18602498/100352919-fccd4e00-2fed-11eb-9521-7415e235b646.PNG)

2020-11-26 12:49 UTC, gracioust commented
> Well done @gracioust
> 
> But, the last two screenshots don't look too ok. The cards look compressed. Kindly rework them

Thanks, I have made the changes.

2020-11-28 10:06 UTC, adaugochi commented
well done @gracioust 
we are making progress
Kindly make more adjustment. there are spaces around it, let it fit properly

2020-11-28 10:07 UTC, adaugochi requested changes

2020-11-28 10:07 UTC, adaugochi commented on submissions/tosinIshola/HTML/Home.html
> +<html lang="en">
what is this home.html for?

2020-12-01 14:44 UTC, closed without merging

2020-12-01 14:44 UTC, gracioust commented
I will create another PR