[62] Create & Style the Customer Signup Page using CSS
Dufuna-CodeCamp/Dufuna-CodeCamp20 pull request #924
Opened 2020-11-22 21:02 UTC by bint-saad

[62] Create & Style the Customer Signup Page using CSS
[62] Create & Style the Customer Signup Page using CSS
![css4](https://user-images.githubusercontent.com/70863560/99917067-46781900-2d0e-11eb-9dcc-1c8b4443cbf3.JPG)
![css1](https://user-images.githubusercontent.com/70863560/99917068-4841dc80-2d0e-11eb-9446-ae5101a9a9a8.JPG)
![css2](https://user-images.githubusercontent.com/70863560/99917069-48da7300-2d0e-11eb-830f-1fa6024b0ef9.JPG)
![css3](https://user-images.githubusercontent.com/70863560/99917073-4a0ba000-2d0e-11eb-8b07-1173792580e3.JPG)

2020-11-23 08:16 UTC, adaugochi requested changes
Well done @bint-saad , the padding-left and right inside the card inside the same. There is more padding on the right than on the left. Make them be even

2020-11-23 08:16 UTC, adaugochi commented on submissions/hadizaSaadu/css/signup-page.html
> +<!DOCTYPE html>
KIndly place the file inside the `hmtl-forms` folder

2020-11-23 13:00 UTC, adaugochi commented
send a new screenshot of your work

2020-11-23 14:01 UTC, bint-saad commented
![css3](https://user-images.githubusercontent.com/70863560/99970859-b634e500-2d9c-11eb-986c-15fbe880670d.JPG)
![css4](https://user-images.githubusercontent.com/70863560/99970863-b7fea880-2d9c-11eb-8142-3bffc16a92c2.JPG)
![css1](https://user-images.githubusercontent.com/70863560/99970864-b8973f00-2d9c-11eb-94bf-c4aa2c949169.JPG)
![css2](https://user-images.githubusercontent.com/70863560/99970867-b8973f00-2d9c-11eb-84e2-027553a2cabd.JPG)

2020-11-23 14:02 UTC, bint-saad commented
screenshot attched!!! Thanks

2020-11-24 08:33 UTC, adaugochi commented
Well done @bint-saad , the padding-left and right inside the card inside the same. There is more padding on the right than on the left. Make them be even

2020-11-24 08:35 UTC, adaugochi commented
![image](https://user-images.githubusercontent.com/43061141/100068943-73c0e600-2e38-11eb-86b6-55dc1ea8014e.png)

2020-11-24 08:36 UTC, adaugochi commented
See that left and right marking that I did. that's where I am pointing at in my comment

2020-11-24 10:17 UTC, bint-saad commented
![cssn4](https://user-images.githubusercontent.com/70863560/100080859-9e19a000-2e46-11eb-81bd-126c8d9cbf49.JPG)
![cssn1](https://user-images.githubusercontent.com/70863560/100080864-9fe36380-2e46-11eb-9c74-21d00c85b4df.JPG)
![cssn2](https://user-images.githubusercontent.com/70863560/100080868-a07bfa00-2e46-11eb-9973-3b5123e97510.JPG)
![cssn3](https://user-images.githubusercontent.com/70863560/100080872-a1149080-2e46-11eb-9c0d-dc664492d1ce.JPG)

2020-11-24 10:17 UTC, bint-saad commented
comment fixed...thanks

2020-11-24 15:02 UTC, adaugochi requested changes
Styling like this `font-weight: normal;
  font-stretch: normal; letter-spacing: normal;
  font-style: normal;` are `normal` by default. There is no need for using them everywhere in your stylings. Kindly remove it.

Also, images should be placed in the `images` folder that is in your `html` folder.

Note that you have same files appearing multiple places. Kindly click [here](https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp20/pull/924/files) to look at what your push as PR

2020-11-24 15:02 UTC, adaugochi commented on submissions/hadizaSaadu/html-forms/css/signup-page.css
> +  font-family: "montserrat", sans-serif;
Declare font-family in your `body` tag and remove it where it is in use elsewhere

2020-11-24 20:16 UTC, bint-saad commented
![cssn4](https://user-images.githubusercontent.com/70863560/100146468-42790200-2e9a-11eb-8357-42f9d24f850d.JPG)
![cssn1](https://user-images.githubusercontent.com/70863560/100146474-44db5c00-2e9a-11eb-947c-2ffaa10ae01d.JPG)
![cssn2](https://user-images.githubusercontent.com/70863560/100146476-4573f280-2e9a-11eb-8839-a676e736c278.JPG)
![cssn3](https://user-images.githubusercontent.com/70863560/100146479-460c8900-2e9a-11eb-9596-79cb1af33be4.JPG)

2020-11-24 20:18 UTC, bint-saad commented
all existing comments fixed... kindly  review closely for any other error(s)

2020-11-25 09:30 UTC, adaugochi requested changes
These images are still inside `css` folder. kindly move them 
![image](https://user-images.githubusercontent.com/43061141/100208550-23fe1f80-2f09-11eb-82b7-68facf19cf86.png)

![image](https://user-images.githubusercontent.com/43061141/100208324-e39ea180-2f08-11eb-8bbf-28243821624c.png)

Also, you have to remove this file
![image](https://user-images.githubusercontent.com/43061141/100208446-06c95100-2f09-11eb-88d0-404fe4547d2f.png)

2020-11-25 09:30 UTC, adaugochi commented on submissions/hadizaSaadu/html-forms/css/signup-page.css
> +/* body {
You haven't fix this

2020-11-25 10:39 UTC, bint-saad commented
![cssn4](https://user-images.githubusercontent.com/70863560/100216534-adfeb600-2f12-11eb-8dfe-20634e2700f4.JPG)
![cssn1](https://user-images.githubusercontent.com/70863560/100216540-afc87980-2f12-11eb-8ddb-b83147921157.JPG)
![cssn2](https://user-images.githubusercontent.com/70863560/100216543-b0611000-2f12-11eb-955b-fb6509dd0aa2.JPG)
![cssn3](https://user-images.githubusercontent.com/70863560/100216545-b1923d00-2f12-11eb-913b-e944d0c1fd27.JPG)

2020-11-25 10:40 UTC, bint-saad commented
comments fixed

2020-11-25 11:22 UTC, adaugochi requested changes

2020-11-25 11:22 UTC, adaugochi commented on submissions/hadizaSaadu/html-forms/css/signup-page.css
> +/* body {
Kindly place this `signup-page.css` inside `css` folder and the `css` folder should not be inside `html-forms` folder. Check your slack message I already gave you guidelines on what you need to to

2020-11-25 14:19 UTC, adaugochi requested changes
Why did you remove your CSS file completely? I only said you should put it in the right folder

2020-11-25 16:57 UTC, bint-saad commented
![cssn4](https://user-images.githubusercontent.com/70863560/100226163-a1cd2580-2f1f-11eb-9441-b95d21665747.JPG)
![cssn1](https://user-images.githubusercontent.com/70863560/100226166-a396e900-2f1f-11eb-8933-e84059bbd890.JPG)
![cssn2](https://user-images.githubusercontent.com/70863560/100226167-a42f7f80-2f1f-11eb-9693-38c0cca527e7.JPG)
![cssn3](https://user-images.githubusercontent.com/70863560/100226169-a4c81600-2f1f-11eb-8955-b25864078c82.JPG)

2020-11-25 16:59 UTC, bint-saad commented
![cssn4](https://user-images.githubusercontent.com/70863560/100258822-c937e880-2f47-11eb-9619-79a8ae4d0805.JPG)
![cssn1](https://user-images.githubusercontent.com/70863560/100258830-cc32d900-2f47-11eb-9d0b-9e01c9f02cbd.JPG)
![cssn2](https://user-images.githubusercontent.com/70863560/100258834-cccb6f80-2f47-11eb-8b42-f8bc052f00f7.JPG)
![cssn3](https://user-images.githubusercontent.com/70863560/100258842-cfc66000-2f47-11eb-8cd3-1042e692986c.JPG)

2020-11-25 17:00 UTC, bint-saad commented
done

2020-11-26 09:21 UTC, adaugochi approved these changes

2020-11-26 10:38 UTC, adaugochi approved these changes

2020-11-26 10:38 UTC, merged