[63] Style the Contact Us Page using CSS
Dufuna-CodeCamp/Dufuna-CodeCamp20 pull request #944
Opened 2020-11-26 16:39 UTC by bint-saad

[63] Style the Contact Us Page using CSS
[63] Style the Contact Us Page using CSS
![con1](https://user-images.githubusercontent.com/70863560/100375592-547bb180-300e-11eb-810c-29aea0fdc7fd.JPG)
![con3](https://user-images.githubusercontent.com/70863560/100375598-55acde80-300e-11eb-9f6f-1a7c52b16f60.JPG)
![con2](https://user-images.githubusercontent.com/70863560/100375601-56457500-300e-11eb-80bc-8d3ae4e0d08b.JPG)

2020-11-27 09:49 UTC, adaugochi requested changes
Kindly fix codefactor issue

2020-11-27 11:45 UTC, bint-saad commented
![con1](https://user-images.githubusercontent.com/70863560/100446047-6a40b380-30ae-11eb-8e46-719eebe02107.JPG)
![con3](https://user-images.githubusercontent.com/70863560/100446053-6c0a7700-30ae-11eb-9b12-c5c296005f22.JPG)
![con2](https://user-images.githubusercontent.com/70863560/100446055-6ca30d80-30ae-11eb-9f90-e1a425d19a14.JPG)

2020-11-27 11:46 UTC, bint-saad commented
conflicts resolved..... kindly review

2020-11-28 10:03 UTC, adaugochi requested changes

2020-11-28 10:03 UTC, adaugochi commented on submissions/hadizaSaadu/css/contact-page.css
> +/* .images {
remove it if not in use

2020-11-28 12:43 UTC, bint-saad commented
![3](https://user-images.githubusercontent.com/70863560/100515878-b7408a80-317f-11eb-959d-74f5ebb42e5a.JPG)
![1](https://user-images.githubusercontent.com/70863560/100515881-b90a4e00-317f-11eb-8582-1bb0bfa4a761.JPG)
![2](https://user-images.githubusercontent.com/70863560/100515882-b9a2e480-317f-11eb-8efa-82497b3128ed.JPG)

2020-11-28 12:44 UTC, bint-saad commented
Removed

2020-11-28 23:06 UTC, adaugochi approved these changes

2020-11-28 23:07 UTC, merged