[66] Style the Contact Us Page using CSS
Dufuna-CodeCamp/Dufuna-CodeCamp20 pull request #952
Opened 2020-11-28 12:21 UTC by queensaldam

## Task: `Contact us page styling using CSS`
- `Style the contact us page`

2020-11-28 12:22 UTC, queensaldam commented
![contact us desktop page](https://user-images.githubusercontent.com/58794483/100515462-b9edb080-317c-11eb-8176-a62b1e07b4e3.png)
![contact us tablet](https://user-images.githubusercontent.com/58794483/100515464-bc500a80-317c-11eb-93e0-b0306dff94d6.png)
![contact us mobile](https://user-images.githubusercontent.com/58794483/100515466-bce8a100-317c-11eb-8767-b91f41768dbc.png)

2020-11-28 12:40 UTC, queensaldam commented
![contact us desktop page](https://user-images.githubusercontent.com/58794483/100515842-3f726000-317f-11eb-86fb-0665921c3c5f.png)
![contact us tablet](https://user-images.githubusercontent.com/58794483/100515843-41d4ba00-317f-11eb-8113-b23b92e06635.png)
![contact us mobile](https://user-images.githubusercontent.com/58794483/100515844-44371400-317f-11eb-8018-163f041c9b01.png)

2020-11-28 22:59 UTC, adaugochi requested changes

2020-11-28 22:59 UTC, adaugochi commented on submissions/damilolaSalami/html-form/contactUs.html
> +<!DOCTYPE html>
kindly work on your existing contact form page. Make changes there. do not create a new file

2020-11-30 09:24 UTC, adaugochi requested changes

2020-11-30 09:24 UTC, adaugochi commented on submissions/damilolaSalami/html-form/contactUs.html
> +<!DOCTYPE html>
kindly delete this file

2020-12-01 11:47 UTC, adaugochi requested changes
All images should be placed inside the `images` folder that is in your `html` folder

2020-12-04 14:01 UTC, queensaldam commented
> All images should be placed inside the `images` folder that is in your `html` folder

Please I don't understand what I am to do

2020-12-07 09:18 UTC, adaugochi approved these changes

2020-12-07 09:18 UTC, merged