[64] Style the Product Details Page using CSS
Dufuna-CodeCamp/Dufuna-CodeCamp20 pull request #959
Opened 2020-11-30 11:29 UTC by bint-saad

[64] Style the Product Details Page using CSS
[64] Style the Product Details Page using CSS
![3c](https://user-images.githubusercontent.com/70863560/100605045-a15dd180-3307-11eb-93b7-ec2bb09d7f2d.JPG)
![3a](https://user-images.githubusercontent.com/70863560/100605051-a3279500-3307-11eb-8aef-edec98a4554d.JPG)
![3b](https://user-images.githubusercontent.com/70863560/100605053-a3279500-3307-11eb-9115-4395bd32a14b.JPG)

2020-12-01 11:42 UTC, adaugochi commented
Kindly send screenshots for desktop and mobile phone view

2020-12-01 11:48 UTC, Ireti203 requested changes

2020-12-01 11:48 UTC, Ireti203 commented on submissions/hadizaSaadu/HTML/product-page.html
> +
Remove whitespace

2020-12-01 11:48 UTC, Ireti203 commented on submissions/hadizaSaadu/HTML/product-page.html
> +<table class="downtb" >
Use a descriptive name for classes. "downtb" is not descriptive

2020-12-01 11:48 UTC, Ireti203 commented on submissions/hadizaSaadu/HTML/product-page.html
> +
Remove whitespace

2020-12-15 16:06 UTC, bint-saad commented
![tab3](https://user-images.githubusercontent.com/70863560/102240155-d6694700-3ef7-11eb-9e62-df0cc673a302.JPG)
![desktop1](https://user-images.githubusercontent.com/70863560/102240163-d79a7400-3ef7-11eb-8d3d-0f8e06907f1e.JPG)
![desktop2](https://user-images.githubusercontent.com/70863560/102240167-d8330a80-3ef7-11eb-84eb-9e707e045f52.JPG)
![mobile1](https://user-images.githubusercontent.com/70863560/102240169-d9643780-3ef7-11eb-9b9c-de6009ac9b2a.JPG)
![mobile2](https://user-images.githubusercontent.com/70863560/102240177-d9fcce00-3ef7-11eb-812d-7cf51dd75cad.JPG)
![mobile3](https://user-images.githubusercontent.com/70863560/102240178-da956480-3ef7-11eb-852b-35fd46ca266d.JPG)
![tab1](https://user-images.githubusercontent.com/70863560/102240180-db2dfb00-3ef7-11eb-8b73-9cbf0c5596f5.JPG)
![tab2](https://user-images.githubusercontent.com/70863560/102240184-dbc69180-3ef7-11eb-9234-77ce6cf88e67.JPG)

2020-12-15 16:07 UTC, bint-saad commented
screenshot added........... thanks

2020-12-16 09:02 UTC, adaugochi approved these changes

2020-12-16 09:02 UTC, merged