[183] Loops and Numbers
Dufuna-CodeCamp/Dufuna-CodeCamp20 pull request #960
Opened 2020-11-30 13:21 UTC by Samju200

## Task: `looping between two number and print`
- `Changes you made to given task`

2020-12-01 11:47 UTC, adaugochi requested changes

2020-12-01 11:47 UTC, adaugochi commented on submissions/adeyemiJuwon/php/loop.php
> +echo "$i <br >";
format this line of code

2020-12-01 11:47 UTC, adaugochi commented on submissions/adeyemiJuwon/php/loop.php
> +while($x <150){
add single space after `<`

2020-12-01 12:09 UTC, Samju200 commented on submissions/adeyemiJuwon/php/loop.php
> +echo "$i <br >";
Okay Done

2020-12-01 12:09 UTC, Samju200 commented on submissions/adeyemiJuwon/php/loop.php
> +while($x <150){
Okay

2020-12-02 09:57 UTC, adaugochi requested changes

2020-12-02 09:57 UTC, adaugochi commented on submissions/adeyemiJuwon/php/loop.php
> +echo "$i <br>";
format this line of code

2020-12-02 10:50 UTC, Samju200 commented on submissions/adeyemiJuwon/php/loop.php
> +echo "$i <br>";
@adaugochi Done

2020-12-02 13:04 UTC, adaugochi commented
Kindly check line 14 of your code

2020-12-02 18:33 UTC, Samju200 commented
> Kindly check line 14 of your code

Yes Thank You
Done @adaugochi

2020-12-03 09:00 UTC, adaugochi approved these changes

2020-12-03 09:00 UTC, merged