[67]  Style the Product Details Page using CSS
Dufuna-CodeCamp/Dufuna-CodeCamp20 pull request #963
Opened 2020-12-01 15:04 UTC by gracioust

## Task: `Style the Product Details Page using CSS`
- `Styled the Product Details Page using CSS`
![product1](https://user-images.githubusercontent.com/18602498/100757515-c1b48b80-33ee-11eb-9f44-6ae8c35ee69c.PNG)
![product2](https://user-images.githubusercontent.com/18602498/100757545-c9743000-33ee-11eb-9968-b03087802ae6.PNG)
![product3](https://user-images.githubusercontent.com/18602498/100757549-ca0cc680-33ee-11eb-87c3-6003d3f01dcf.PNG)
![product4](https://user-images.githubusercontent.com/18602498/100757553-caa55d00-33ee-11eb-9e32-ea2789fbf5cd.PNG)
![product5](https://user-images.githubusercontent.com/18602498/100757554-caa55d00-33ee-11eb-8978-8a8d21d36c5e.PNG)
![product6](https://user-images.githubusercontent.com/18602498/100757556-cb3df380-33ee-11eb-96af-f38636c7f798.PNG)

2020-12-02 09:52 UTC, adaugochi commented
I expect the related product item to appear one on a mobile screen, not two

2020-12-04 14:27 UTC, gracioust commented
> I expected the related product item to appear one on a mobile screen, not two

Okay, done that

2020-12-04 14:29 UTC, gracioust commented
**THE RELATED IMAGES HAVE BEEN ADJUSTED TO DISPLAY ONE BY ONE IN MOBILE VIEW**
![product4](https://user-images.githubusercontent.com/18602498/101175326-5284a480-3645-11eb-9399-3cac71bb5f99.PNG)
![product5](https://user-images.githubusercontent.com/18602498/101175341-59131c00-3645-11eb-9d43-debbf1b10e78.PNG)
![product6](https://user-images.githubusercontent.com/18602498/101175343-59abb280-3645-11eb-974a-58f72fc85b2f.PNG)
![product7](https://user-images.githubusercontent.com/18602498/101175344-59abb280-3645-11eb-99ca-c4c790083b9f.PNG)

2020-12-05 16:24 UTC, adaugochi requested changes

2020-12-05 16:24 UTC, adaugochi commented on submissions/tosinIshola/HTML/Home.html
> +<html lang="en">
Which page is this? Where are ask to create a home page? If no, kindly remove it

2020-12-07 11:54 UTC, gracioust commented
Done please kindly help me review this PR and merge, i have been delayed enough on this task.

2020-12-08 09:49 UTC, adaugochi requested changes

2020-12-08 09:49 UTC, adaugochi commented on submissions/tosinIshola/html-forms/contact_form.html
> +               <li><a href="../HTML/Home.html">HOME</a></li>  <br>
You forgot to remove this

2020-12-08 09:49 UTC, adaugochi commented on submissions/tosinIshola/html-forms/signup.html
> +               <li><a href="../HTML/Home.html">HOME</a></li>  <br>
You forgot to remove this

2020-12-10 19:10 UTC, gracioust commented on submissions/tosinIshola/html-forms/signup.html
> +               <li><a href="../HTML/Home.html">HOME</a></li>  <br>
Done

2020-12-10 19:13 UTC, gracioust commented on submissions/tosinIshola/html-forms/contact_form.html
> +               <li><a href="../HTML/Home.html">HOME</a></li>  <br>
Done

2020-12-11 09:15 UTC, adaugochi approved these changes

2020-12-11 09:15 UTC, merged