[164] Sign-Up Form Validation - Fullstack
Dufuna-CodeCamp/Dufuna-CodeCamp20 pull request #964
Opened 2020-12-01 15:52 UTC by kojusola

## Task: `added signup form validation file`
- `validated the signup form using javascript`

2020-12-02 09:56 UTC, adaugochi requested changes
Well done @kojusola 

But you defile the reason for using functions. `functions` are used to ensure code reusability. You wrote separate functions for things that look to similar instead of writing just one function that can handle all of them.

I will like for you to do a rework

2020-12-02 11:12 UTC, kojusola commented
made changes to the function 
thank you

2020-12-02 13:02 UTC, adaugochi requested changes

2020-12-02 13:02 UTC, adaugochi commented on submissions/adeolaFafemi/dom/signUp.js
> +    else
Too many nested `if else` statement. There is no need to have an `if else` inside the `else` block, Simply do an `else if` for the regex check and `else` if it returns true. Same goes for other places too

2020-12-02 21:40 UTC, kojusola commented
corrected it 
thanks

2020-12-03 09:03 UTC, adaugochi approved these changes

2020-12-03 09:03 UTC, merged