[168] Contact Form Validation
Dufuna-CodeCamp/Dufuna-CodeCamp20 pull request #977
Opened 2020-12-03 11:49 UTC by Tocyn

![Screen Shot 2020-12-03 at 12 42 24 PM](https://user-images.githubusercontent.com/70757475/101014290-f0a13d80-3565-11eb-9cc0-bed194684bf6.png)

2020-12-03 14:07 UTC, adaugochi requested changes

2020-12-03 14:07 UTC, adaugochi commented on submissions/oluwatosinOke/domManipulation/contactForm.js
> +    if (field.value === "") {
There is no need doing this check. `required()` function already handles that

2020-12-03 14:42 UTC, Tocyn commented
Hi @adaugochi 
i have effected the changes as requested.

2020-12-04 09:17 UTC, adaugochi requested changes

2020-12-04 09:17 UTC, adaugochi commented on submissions/oluwatosinOke/domManipulation/contactForm.js
> +    const emailRegex = /^\w+([-]?\w+)*@\w+([-]?\w+)*(\w{2,10})+$/,
Declare this variable outside of the function

2020-12-04 09:17 UTC, adaugochi commented on submissions/oluwatosinOke/domManipulation/contactForm.js
> +    required(subject, "Please enter a message subject", event);
You are not calling this `required()` function for `email, fullName`

2020-12-04 17:25 UTC, Tocyn commented
@adaugochi 
I have effected the requested changes.

![Screen Shot 2020-12-04 at 6 00 22 PM](https://user-images.githubusercontent.com/70757475/101194114-d77bb800-365d-11eb-88da-926a4ea0107b.png)
![Screen Shot 2020-12-04 at 6 09 15 PM](https://user-images.githubusercontent.com/70757475/101194124-d9de1200-365d-11eb-9a01-4db8f7b6a976.png)

2020-12-05 16:26 UTC, adaugochi requested changes
Well done.

But, you don't need to write separate functions for each input field validate. Functions are meant to be reusable. Since some of the functions you have written do the same thing, you can simply write a single function and pass in those things that make them differ a little as a parameter.

2020-12-05 16:31 UTC, Tocyn commented
@adaugochi, doing that did not give me the result I wanted.

On Sat, 5 Dec 2020, 5:26 pm Maryfaith Mgbede, <notifications@github.com>
wrote:

> *@adaugochi* requested changes on this pull request.
>
> Well done.
>
> But, you don't need to write separate functions for each input field
> validate. This defeat the use of functions. Functions are meant to be
> reusable. Since some of the functions you have written do the same thing,
> you can simply write a single function and pass in those things that make
> them differ a little as a parameter.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp20/pull/977#pullrequestreview-545599001>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQ32YY3RE36LJ3HDIAA7LITSTJNLDANCNFSM4UL3U5CQ>
> .
>

2020-12-05 17:00 UTC, Tocyn commented
@adaugochi, i have reverted to using functions.
Kindly review

![Screen Shot 2020-12-05 at 5 58 32 PM](https://user-images.githubusercontent.com/70757475/101258584-b2ea1380-3723-11eb-9026-60f8d6d6185f.png)

2020-12-05 17:09 UTC, Tocyn commented
@adaugochi 

![Screen Shot 2020-12-05 at 6 04 48 PM](https://user-images.githubusercontent.com/70757475/101258751-db264200-3724-11eb-9acf-9d133c286fd9.png)

2020-12-07 09:20 UTC, adaugochi requested changes

2020-12-07 09:20 UTC, adaugochi commented on submissions/oluwatosinOke/domManipulation/contactForm.js
> +    if (!field.value.match(regExp)) {
put this in an `else if` statement

2020-12-07 09:25 UTC, Tocyn commented
@adaugochi 
else if correction effected

2020-12-07 14:40 UTC, adaugochi requested changes

2020-12-07 14:40 UTC, adaugochi commented on submissions/oluwatosinOke/domManipulation/contactForm.js
> +    }else if (!field.value.match(regExp)) {
add indentation on this block of code.

2020-12-07 14:40 UTC, adaugochi commented on submissions/oluwatosinOke/domManipulation/contactForm.js
> +    textRegex=  /^[a-zA-Z0-9]/
Add `;` at the end of the `textRegex`

2020-12-07 14:40 UTC, adaugochi commented on submissions/oluwatosinOke/domManipulation/contactForm.js
> +    "This field is required",
Since this statement (`"This field is required"`) is repeated more than ones, kindly place it in a variable so that you can reuse it

2020-12-07 14:51 UTC, Tocyn commented
@adaugochi 
i have requested the requested changes.

2020-12-07 20:25 UTC, adaugochi approved these changes

2020-12-07 20:25 UTC, merged