[58] Develop an E-commerce Store Database
Dufuna-CodeCamp/Dufuna-CodeCamp20 pull request #985
Opened 2020-12-04 02:22 UTC by kazeemerinfolami

## Task: `[58] Develop an E-commerce Store Database`
- `Created and E-commerce Store Database`

2020-12-04 10:02 UTC, adaugochi requested changes

2020-12-04 10:02 UTC, adaugochi commented on submissions/kazeemErinfolami/database/init.sql
> +CREATE TABLE products (
Kindly rework this products table again. Some column(s) is/are not supposed to be part of this table

2020-12-04 10:02 UTC, adaugochi commented on submissions/kazeemErinfolami/database/init.sql
> +CREATE TABLE orders_items (
Kindly rework this order_items table again. Some column(s) is/are not supposed to be part of this table

2020-12-08 09:46 UTC, adaugochi requested changes

2020-12-08 09:46 UTC, adaugochi commented on submissions/kazeemErinfolami/database/init.sql
> +    admin_id INT NOT NULL,
An order item cannot have `admin_id`. There is still one missing column on this table. Kindly read through the task again. Well done @kazeemerinfolami

2020-12-08 11:11 UTC, kazeemerinfolami commented
I have made the changes. Thank you

On Tue, 8 Dec 2020 at 10:46, Maryfaith Mgbede <notifications@github.com>
wrote:

> *@adaugochi* requested changes on this pull request.
> ------------------------------
>
> In submissions/kazeemErinfolami/database/init.sql
> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp20/pull/985#discussion_r538185107>
> :
>
> > +("Apple", "Be classy", "../html/images/vegetables.jpg", 650.00, 6, 'in stock', 9, 5 ),
> +("Windows 10 pro", "feel free and code.", "../html/images/laptop.jpg", 190.00, 3, 'in stock', 6, 4 ),
> +("IPhone", "Be classy", "../html/images/vegetables.jpg", 650.00, 6, 'in stock', 5, 5 ),
> +("Zara shoes", "selection of Loafers, Formal Shoes, Boots, Sneakers & more", "../html/images/brogues_shoes.jpg", 490.00, 6, 'out of stock', 1, 4 ),
> +("lip stick", "selection of Loafers, Formal Shoes, Boots, Sneakers & more", "../html/images/women acc.jpg", 50.00, 6, 'in of stock', 3, 3 ),
> +("LG", "feel free and code.", "../html/images/laptop.jpg", 190.00, 3, 'in stock', 5, 2 ),
> +("lip stick", "selection of Loafers, Formal Shoes, Boots, Sneakers & more", "../html/images/women acc.jpg", 50.00, 6, 'in of stock', 3, 1 );
> +
> +SELECT * FROM products;
> +
> +
> +/*ORDERS ITEMS...*/
> +CREATE TABLE orders_items (
> +	id INT NOT NULL AUTO_INCREMENT,
> +    order_id INT NOT NULL,
> +    admin_id INT NOT NULL,
>
> An order item cannot have admin_id. There is still one missing column on
> this table. Kindly read through the task again. Well done
> @kazeemerinfolami <https://github.com/kazeemerinfolami>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp20/pull/985#pullrequestreview-546960823>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/APEJWD4X67VHBDW5YX3K4KTSTXYYVANCNFSM4UM2KNHQ>
> .
>

2020-12-09 09:01 UTC, adaugochi approved these changes

2020-12-09 09:01 UTC, merged