[165] Sign-Up Form Validation- Frontend
Dufuna-CodeCamp/Dufuna-CodeCamp20 pull request #996
Opened 2020-12-04 19:30 UTC by Onyinye101

## Task: `[165] Sign-Up Form Validation`
- `Validated the sign-up form using Javascript`

2020-12-05 16:17 UTC, adaugochi reviewed
Well done.

But, you don't need to write separate functions for each input field validate. This defeat the use of functions. Functions are means to be reusable.

2020-12-05 16:17 UTC, adaugochi commented on submissions/onyinyeChukwuka/javascript/signup.js
> +    if (emailValid && numberValid && passwordValid && confirmPasswordValid && firstNameValid && lastNameValid) {
This check should be for debugging purpose. There is no need for this to be in your code

2020-12-05 16:17 UTC, adaugochi commented on submissions/onyinyeChukwuka/javascript/signup.js
> +    let emailValid = validateEmail(email);
Kindly remove all variable names

2020-12-07 09:24 UTC, adaugochi requested changes

2020-12-07 09:24 UTC, adaugochi commented on submissions/onyinyeChukwuka/javascript/signup.js
> +signupbutton.addEventListener('click', () => {
kindly listen for a `submit` event

2020-12-10 09:47 UTC, adaugochi requested changes
Well done.

But, you don't need to write separate functions for each input field validate. Functions are meant to be reusable. Since almost all the function you have written do the same thing or are exactly alike, you can simply write a single function and pass in those things that make them differ a little as a parameter.

2020-12-11 09:20 UTC, adaugochi requested changes

2020-12-11 09:20 UTC, adaugochi commented on submissions/onyinyeChukwuka/javascript/signup.js
> +    if (element === phoneNumber || element === email || element === password) {
Well done. 

You don't need to do this checks i.e `element === phoneNumber || element === email || element === password`

2020-12-11 09:20 UTC, adaugochi commented on submissions/onyinyeChukwuka/javascript/signup.js
> +        if (!validationRegex.test(element.value)) {
This line is where your code should start from

2020-12-11 09:20 UTC, adaugochi commented on submissions/onyinyeChukwuka/javascript/signup.js
> +    else {
The code on the else block is irrelevant. the code on line 31 is already handling the validation of regex for all elements field whether firstname, lastname, email and so on

2020-12-11 09:20 UTC, adaugochi commented on submissions/onyinyeChukwuka/javascript/signup.js
> +    } else if (element === confirmPassword) {
Confirm password should be done in a separate function

2020-12-14 13:44 UTC, ToluAkin requested changes
Well done on the work done so far.

2020-12-14 13:44 UTC, ToluAkin commented on submissions/onyinyeChukwuka/javascript/signup.js
> +    // validateInput(confirmPassword, "Please confirm your Password", "Your passwords don't match", passwordRegex);
Remove this unused comment. @Onyinye101

2020-12-14 13:47 UTC, ToluAkin approved these changes

2020-12-14 13:48 UTC, merged