[174] Calculate Product Shipping Cost - Fullstack
Dufuna-CodeCamp/Dufuna-CodeCamp20 pull request #997
Opened 2020-12-05 10:36 UTC by kojusola

## Task: `created a file to calculate the product price and shipping cost`
- `Calculated the product shipping cost, total cost and product price`

2020-12-05 16:13 UTC, adaugochi requested changes
Well done. Kindly format your code properly. closing curly brackets should be properly placed. The opening curly bracket should be after the closing bracket `) {`

2020-12-05 16:13 UTC, adaugochi commented on submissions/adeolaFafemi/dom/productCost.js
> +var alphaExp = /^[0-9]+$/;
This variable name is confusing. `alpha` sounds like it is alphabetical expression

2020-12-05 16:13 UTC, adaugochi commented on submissions/adeolaFafemi/dom/productCost.js
> +    var total = 0;
I don't think there is a need for this variable

2020-12-05 18:47 UTC, kojusola commented
made the corrections 
thank you

2020-12-07 09:28 UTC, adaugochi requested changes

2020-12-07 09:28 UTC, adaugochi commented on submissions/adeolaFafemi/dom/productCost.js
> +    if (prodprice < 1000){
This block code is confusing. i.e line `32 - 43`. Are you wrapping the `else if` statements inside the `if` block? If yes, that is wrong. If no, kindly format your code to look well align

2020-12-07 20:13 UTC, kojusola commented
already reformatted it.
Thank you

2020-12-08 09:38 UTC, adaugochi approved these changes

2020-12-08 09:38 UTC, merged